.gitignore, AUTHORS, ChangeLog, gitlab, gitlab.py
Hi!
I implentend a useful way for using argparse library for parsing the argument of command line. In this way I think that the code is more clean and you don't have to think all exceptions about argument invalid or not correct.
Tell me your opinion about it!
=> Used argparse library

setup.py, test/test_gitlab.py, test/test_gitlabobject.py
Uses httmock library to abstract away requests-library.
Uses nose to actually run tests.
=> Added tests.

tools/build_test_env.sh, tools/functional_tests.sh, tools/py_functional_tests.sh
Here are a bunch of commits to fix and clean up some minor issues in the `tools/*.sh` scripts.
=> Test script cleanups

gitlab/objects.py
* `build_events`
* `enable_ssl_verification`
See the two links below:
* https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#add-project-hook
* https://github.com/pyapi-gitlab/pyapi-gitlab/pull/173
=> Adding new `ProjectHook` attributes:

gitlab/exceptions.py, gitlab/objects.py
Add methods subscribe and unsubscribe in ProjectIssue to let the user control subscription in issues.
=> Add support for subscribe and unsubscribe in issues

gitlab/__init__.py, gitlab/config.py
Support for HTTP basic authentication
The username and password can be specified in the configuration file
```
http_username
http_password
```
=> Added support for HTTP basic authentication

gitlab/__init__.py
Hi @gpocentek , thanks for merging the previous method (and adding the documentation, I didn't thought about that). This pull request adds HTTPauth support for the remaining methods, which should cover pretty much all.
Thanks in advance,
Peter
=> Added HTTPauth support for even more methods :)

gitlab/__init__.py, gitlab/objects.py
Hello,
I needed the ability to list projects under a group. I believe this is where the code should belong, please correct/advise me if there are any changes that need to be made.
This will allow me to list some/all of the projects that belong to a group.
`p = gl.groups.list_projects(37, all=True)`
Thanks.
=> List projects in a group

gitlab/cli.py, gitlab/objects.py
=> Add support for build artifacts and trace

gitlab/objects.py
=> add `note_events` to project hooks attributes

docs/gl_objects/projects.py, gitlab/objects.py
This feature is coming in 8.12 and already in nightly.
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/6213
=> Add the ability to fork to a specific namespace

docs/gl_objects/branches.rst
You can pass developers_can_push and developers_can_merge to the protect function. Handy!
=> Add branch protection notes

docs/gl_objects/projects.rst
Just a sketch, feel free to toss it and do it in the right way.
=> Create a project in a group

README.rst
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>
=> edit doc badge url in README.rst

gitlab/__init__.py, gitlab/objects.py, gitlab/tests/test_gitlabobject.py
new API, that should be coming in Gitlab 8.15
cf [Gitlab-CE MR !6373](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/6373)
=> Added support for Snippets

gitlab/objects.py
Ran tests, all passed.
This will fix #219
=> Added pipeline_events to ProjectHook attrs

docs/gl_objects/issues.py, docs/gl_objects/issues.rst, gitlab/exceptions.py, gitlab/objects.py
This adds support for gitlabs time tracking feature #221
=> Time tracking

docs/gl_objects/projects.py, docs/gl_objects/projects.rst, gitlab/objects.py
* Integrate with BaseManager
* Add doc about how to create a pipeline
Reference:
* https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline
=> Implement create pipeline API

gitlab/objects.py
#242 
Pull request to [bug 242](https://github.com/gpocentek/python-gitlab/issues/242)
=> Change to correct logic of functions

gitlab/objects.py
=> Make GroupProject inherit from Project

gitlab/objects.py
The code was more or less copied from the equivalent function on
=> Add time_stats to ProjectMergeRequest

docs/cli.rst
Just fixed some spelling/typos in documentation
=> Fixed spelling mistakes

docs/cli.rst, gitlab/config.py, gitlab/tests/test_config.py
- Also updates documentation
- See issues #204 and #270
=> Support SSL verification via internal CA bundle

gitlab/__init__.py, gitlab/exceptions.py, gitlab/v4/objects.py
* Tag can get by id
* on_http_error bring `error_message`, `response_code`, `response_body`
=> Fix tag api

gitlab/v4/objects.py
=> Fix trigger variables in v4 API

gitlab/__init__.py
=> Allow per_page to be used with generators.

README.rst
This is probably enough. Thanks for your help. Closes #402
=> Adding the supported version badge

gitlab/v3/objects.py, gitlab/v4/objects.py
Hi,
I've started to implement support for pipeline schedules and wanted to ask if this is wanted to be picked up and reviewed. It allows to add pipeline schedules as well as variables. Any feedback is welcome as I am not so familiar with the code base.
Best regards
=>  Feature/pipeline schedules

docs/gl_objects/projects.rst
Minor fix: Exammples -> Examples
=> docs(projects): fix typo

gitlab/v4/objects.py, tools/python_test_v4.py
Add support for project badges https://docs.gitlab.com/ee/api/project_badges.html
=> Add support for Project badges

docs/gl_objects/projects.rst, gitlab/v4/objects.py, tools/python_test_v4.py
Added support for listing forks of a project 
https://gitlab.cecs.anu.edu.au/help/api/projects.md#list-forks-of-a-project
=> Added support for listing forks of a project 

gitlab/cli.py
=> fix(cli): print help and usage without config file

tools/build_test_env.sh, tools/python_test_v4.py
This images is updated to the latest GitLab CE.
Fix the diff() test to match the change in the API output.
=> Use the pythongitlab/test-python-gitlab docker image for tests

docs/gl_objects/groups.rst
=> docs(groups): fix typo

docs/gl_objects/milestones.rst
=> [docs] Fix the milestone filetring doc (iid -> iids)

docs/gl_objects/users.rst
=> [docs] Fix typo in custom attributes example

docs/gl_objects/groups.rst, docs/gl_objects/projects.rst, gitlab/v4/objects.py, tools/python_test_v4.py
=> [feature] Add support for members all() method

docs/gl_objects/labels.rst, docs/gl_objects/projects.rst, gitlab/v4/objects.py, tools/python_test_v4.py
=> Add support to resource label events

README.rst
=> docs(readme): provide commit message guidelines

gitlab/mixins.py
=> fix(api): make reset_time_estimate() work again

.travis.yml
=> chore: release tags to PyPI automatically

gitlab/base.py, gitlab/tests/test_base.py
To ease lists and sets manipulations.
=> Implement __eq__ and __hash__ methods

.travis.yml
Thanks to @bittner for the tip.
=> chore(ci): don't try to publish existing release

RELEASE_NOTES.rst, gitlab/v4/objects.py
=> fix(api): Make *MemberManager.all() return a list of objects

docs/gl_objects/projects.rst, gitlab/v4/objects.py
This PR address #722 
Not entirely sure how to implement the update functionality, as it requires an additional argument in the http request on the end so I've left that out for now.
=> add project releases api

docs/api-objects.rst, docs/gl_objects/repositories.rst, docs/gl_objects/repository_tags.rst, gitlab/v4/objects.py
this is for #723. 
Im willing to add documentation too
=> registry api implementation

gitlab/mixins.py, gitlab/tests/test_utils.py, gitlab/utils.py
Refactor a bit to handle this change, and add unit tests.
Closes #779
=> fix: convert # to %23 in URLs

docs/gl_objects/builds.rst
=> docs: Add an example of trigger token usage

docs/gl_objects/builds.rst, gitlab/v4/objects.py
It adds a new endpoint which was released in the Gitlab CE 11.11.
=> Add new endpoint to get the variables of a pipeline

docs/api-usage.rst
=> docs(api-usage): fix project group example

docs/gl_objects/builds.rst
Documentation to delete a pipeline
=> Doc: delete a pipeline

gitlab/v4/objects.py
=> feat: add support for board update

docs/gl_objects/issues.rst, gitlab/v4/objects.py, tools/python_test_v4.py
=> feat: add support for issue.related_merge_requests

docs/gl_objects/builds.rst, gitlab/v4/objects.py
=> feat: get artifact by ref and job

docs/gl_objects/mrs.rst, gitlab/exceptions.py, gitlab/v4/objects.py, tools/python_test_v4.py
Hi all. This MR adds the rebase method for an MR. Also adds an example in the documentation.
=> Resolve #822, add mr rebase

gitlab/mixins.py, tools/cli_test_v4.sh
=> fix(cli): fix update value for key not working

gitlab/cli.py, gitlab/tests/test_cli.py, gitlab/v4/cli.py
=> fix(cli): don't fail when the short print attr value is None

gitlab/v4/objects.py
=> fix(cli): allow --recursive parameter in repository tree

README.rst
six URL was pointing to 404
Fixes #829
=> docs(readme): fix six url

gitlab/base.py, gitlab/tests/test_base.py
=> fix: improve pickle support

docs/gl_objects/snippets.rst
=> docs(snippets): fix project-snippets layout

.gitignore, docs/gl_objects/users.rst, gitlab/v4/objects.py, tools/python_test_v4.py
=> feat(user): add status api

docker-entrypoint.sh, docs/api-usage.rst, docs/cli.rst, gitlab/__init__.py, gitlab/cli.py, gitlab/config.py, gitlab/tests/test_gitlab.py
See https://docs.gitlab.com/ee/api/jobs.html#get-job-artifacts for usage
=> Add support for job token

docs/gl_objects/repository_tags.rst
=> docs(repository-tags): fix typo

gitlab/v4/objects.py
fix https://github.com/python-gitlab/python-gitlab/issues/881
author of code fix @carleski
https://github.com/python-gitlab/python-gitlab/pull/669
But his request has not been accepted for a year and there is a need for rebase.
I made a new PR with the same fix
=> fix cli command user-project list

docs/gl_objects/projects.rst
=> docs(projects): add note about project list

docs/gl_objects/projects.rst, gitlab/v4/objects.py, tools/python_test_v4.py
=> feat (project): add file blame api

gitlab/base.py, gitlab/cli.py, gitlab/config.py, gitlab/tests/test_base.py
I checked the code and it was pretty clean. I found and fixed some minor improvements. Please reflect if you wish.
=> Remove unused code and simplify string format.

gitlab/__init__.py
Closes #900
Thanks for the MR @jalr
=> fix: fix not working without auth

MANIFEST.in
=> chore(dist): add test data

docs/gl_objects/deployments.rst, gitlab/tests/test_gitlab.py, gitlab/v4/objects.py
Added in GitLab 12.4
Fixes #917
=> feat: add deployment creation

.gitlab-ci.yml
=> chore(ci): update latest docker image for every tag

docs/gl_objects/groups.rst, gitlab/v4/objects.py
=> Add support for include_subgroups filter

docs/gl_objects/pipelines_and_jobs.rst
docs(builds): add pipeline custom variables usage example
=> docs(pipelines_and_jobs): add pipeline custom variables usage example

gitlab/v4/objects.py
Reference: https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-configuration
Missing attributes:
* merge_requests_author_approval
* merge_requests_disable_committers_approval
=> Added missing attributes for project approvals

ChangeLog.rst
=> docs(changelog): add notice for release-notes on Github

gitlab/v4/objects.py
fix for #942 - path computation wasn't working.
=> #942: fix up path computation for project-fork list

docs/api-objects.rst, gitlab/v4/objects.py, tools/python_test_v4.py
Resolve issue #551. @max.wittig@siemens.com
This is the only gitlab api type that has nested json. You may have trouble using this feature from the command line as the nested-json parameter will be interpreted as a string which will cause the request to fail.
=> feat: add project and group clusters

docs/gl_objects/clusters.rst
add cluster docs for issue #551. @max.wittig@siemens.com
=> docs: add project and group cluster examples

docs/gl_objects/snippets.rst
=> docs(snippets): fix snippet docs

gitlab/__init__.py, gitlab/v4/objects.py
Added audit events feature used for gitlab EE.
As requested in this issue:
https://github.com/python-gitlab/python-gitlab/issues/948
This code was tested and is working properly.
=> feat: add audit endpoint

docs/gl_objects/users.rst, gitlab/tests/test_gitlab.py, gitlab/v4/objects.py, tools/cli_test_v4.sh, tools/python_test_v4.py
Closes #1009, introduced in GitLab 12.8.
=> feat: add support for user memberships API (#1009)

README.rst, docs/api-usage.rst
Closes #1029.
I sneaked in an update for a few broken links.
=> docs: add reference to REQUESTS_CA_BUNDLE usage

docs/api-usage.rst, gitlab/__init__.py
Reverts python-gitlab/python-gitlab#1003
=> Revert "feat: use keyset pagination by default for `all=True`"

gitlab/__init__.py, gitlab/base.py
It shoud be `prev`, not `next`.
=> docs: fix comment of prev_page()

docs/api-objects.rst, docs/gl_objects/remote_mirrors.rst, gitlab/tests/objects/test_projects.py, gitlab/v4/objects.py, tools/python_test_v4.py
=> feat(api): add support for remote mirrors API (#1056)

gitlab/__init__.py, gitlab/config.py, gitlab/exceptions.py, gitlab/tests/test_exceptions.py, gitlab/v4/objects.py
Closes #939. Trying to close some older issues that can be fixed with small changes. :P
=> chore: use raise..from for chained exceptions (#939)

.gitignore, .testr.conf, .travis.yml, MANIFEST.in, test-requirements.txt, tox.ini
I closed this one earlier thinking I'd include it in a later PR, but I guess it doesn't hurt to add it already, what do you think @max-wittig? :)
=> chore: use pytest to run unit tests and coverage

docs/gl_objects/pipelines_and_jobs.rst, gitlab/exceptions.py, gitlab/tests/objects/test_projects.py, gitlab/v4/objects.py
I have added a custom play command to the project pipeline schedules. 
I made a previous pull request #1068 but the commits were incorrect. I also fixed the lint errors.
Please let me know if I am missing anything else.
=> feat: Add play command to project pipeline schedules

gitlab/config.py
=> fix(config): fix duplicate code

README.rst, docs/gl_objects/runners.rst, gitlab/tests/conftest.py, gitlab/tests/objects/test_runners.py, gitlab/v4/objects.py, test-requirements.txt
Fixes https://github.com/python-gitlab/python-gitlab/issues/1083
=> feat: add group runners api

docs/gl_objects/remote_mirrors.rst
Fix command create for remote_mirrors
=> Update doc for remote_mirrors

gitlab/v4/objects.py
Add masked parameter for project-variable and group-variable
=> Add masked parameter for project-variable and group-variable

gitlab/__init__.py
Pass kwargs to subsequent queries in GitlabList (fixes: #1123)
=> Pass kwargs to subsequent queries in GitlabList (fixes: #1123)

tools/functional/test_cli_v4.py
=> fix: tests fail when using REUSE_CONTAINER option

docs/cli.rst
=> docs(cli): add examples for group-project list

gitlab/tests/objects/test_resource_label_events.py
Hi! I propose to add another few unit test cases. At this time is for resource label events.
=>  Add unit tests for resource label events API

.readthedocs.yml
=> chore(ci): add .readthedocs.yml

gitlab/v4/objects/__init__.py
Added filter param to allow searching merge requests using `wip` query param
=> Added MR wip filter param

gitlab/tests/objects/test_badges.py
Hi! Take a look at the unit tests inside. At that time for project and group badges.
=> test: add unit tests for badges API

docs/cli-usage.rst, gitlab/v4/cli.py, tools/functional/cli/test_cli_artifacts.py, tools/functional/conftest.py, tools/functional/fixtures/docker-compose.yml
=> fix(cli): write binary data to stdout buffer

docs/gl_objects/projects.rst
=> docs(projects): correct fork docs

README.rst
Otherwise the whole testsuite will refuse to run
=> docs(readme): also add hint to delete gitlab-runner-test

docs/gl_objects/issues.rst
=> docs(issues): add admin, project owner hint

docs/_templates/breadcrumbs.html
There is no way to edit the raw commit
=> chore(docs): always edit the file directly on master

gitlab/base.py, gitlab/tests/test_base.py
This fixes and error, where deleted attributes would not show up
Fixes #1155
=> fix(base): really refresh object

gitlab/__init__.py, gitlab/v4/objects/__init__.py, requirements.txt, setup.py
Closes https://github.com/python-gitlab/python-gitlab/pull/1004
Closes https://github.com/python-gitlab/python-gitlab/issues/646
=> feat: support multipart uploads

docs/cli-usage.rst
see codeblock below, it's about issues, not snippets
=> cli-usage readme: fixed term

gitlab/tests/objects/test_issues.py, gitlab/v4/objects/__init__.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1222
=> feat(issues): add missing get verb to IssueManager

docs/gl_objects/personal_access_tokens.rst, gitlab/__init__.py, gitlab/tests/objects/test_personal_access_tokens.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/personal_access_tokens.py
See: https://docs.gitlab.com/ee/api/personal_access_tokens.html
=> feat: add personal access token API

gitlab/cli.py, gitlab/client.py
As we only support the v4 Gitlab API, explicitly import
gitlab.v4.objects instead of dynamically importing it depending on the
API version.
This has the added benefit of mypy being able to type check the Gitlab
__init__() function as currently it will fail if we enable type
checking of __init__() it will fail.
=> chore: explicitly import gitlab.v4.objects/cli

.github/workflows/lint.yml, .mypy.ini, gitlab/base.py, gitlab/cli.py, gitlab/client.py, test-requirements.txt, tox.ini
Add an initial mypy test to test gitlab/base.py and gitlab/__init__.py
=> Enable mypy type checking and add type hints to gitlab/base.py

gitlab/v4/objects/ldap.py, gitlab/v4/objects/projects.py
Discovered that there were some undefined names.
=> fix: undefined name errors

gitlab/cli.py
Discovered this when I ran flake8 on the file. Unfortunately I was the
one who introduced this wrong variable name :(
=> fix: wrong variable name

gitlab/base.py, gitlab/client.py
Adding some initial type-hints to gitlab/client.py
Unsure about my usage of assert to identify the type of the object. Feedback appreciated.
=> chore: add type-hints to gitlab/client.py

gitlab/client.py
Was able to figure out better type-hints for gitlab/client.py
=> chore: add and fix some type-hints in gitlab/client.py 

gitlab/mixins.py
* Added type-hints for gitlab/mixins.py
* Changed use of filter with a lambda expression to
list-comprehension. mypy was not able to understand the previous
code. Also list-comprehension is better :)
=> chore: add type-hints for gitlab/mixins.py

docs/gl_objects/packages.rst, gitlab/tests/objects/test_packages.py, gitlab/v4/objects/packages.py
Add ProjectPackageFile and the ability to list project package package_files.
Fixes #1372
=> feat: add ProjectPackageFile

gitlab/__version__.py
@nejch I think it's time again to release. It's been a while
=> chore: bump version to 2.7.0

gitlab/v4/objects/groups.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1431.
=> fix(objects): add missing group attributes

.github/workflows/test.yml, codecov.yml, tox.ini
Trying out codecov flags to see how much the whole suite covers.
=> test(functional): start tracking functional test coverage

docs/api-usage.rst, docs/faq.rst
=> docs(api): add behavior in local attributes when updating objects

docs/gl_objects/groups.rst, gitlab/tests/objects/test_members.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/members.py
=> feat(objects): add support for billable members

gitlab/v4/cli.py
Code was using inspect.getmro() to replicate the functionality of the
built-in function issubclass()
Switch to using issubclass()
=> chore: use built-in function issubclass() instead of getmro()

gitlab/v4/objects/pipelines.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1354
=> fix(cli): add missing list filter for jobs

docs/gl_objects/issues.rst, docs/gl_objects/projects.rst, gitlab/client.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/projects.py, gitlab/v4/objects/statistics.py, tests/unit/objects/test_issues.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1261
=> feat(objects): support all issue statistics endpoints

.mypy.ini, gitlab/v4/cli.py
* Add type-hints to gitlab/v4/cli.py
* Add required type-hints to other files based on adding type-hints
to gitlab/v4/cli.py
=> chore: add type-hints to gitlab/v4/cli.py

docs/gl_objects/wikis.rst, gitlab/v4/objects/groups.py, gitlab/v4/objects/wikis.py, tests/functional/api/test_groups.py
This pull request adds support for wikis on Group level
Closes https://github.com/python-gitlab/python-gitlab/issues/1224
=> feat(objects): add support for Group wikis

docs/api-objects.rst, docs/gl_objects/keys.rst, gitlab/client.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/keys.py, tests/functional/api/test_keys.py, tests/unit/objects/test_keys.py
While this endpoint may be a little niche, it was useful for a project I was involved in recently.
=> feat: add keys endpoint

.mypy.ini, gitlab/v4/objects/projects.py
Adding type-hints to gitlab/v4/objects/projects.py
=>  chore: add type-hints to gitlab/v4/objects/projects.py

docs/gl_objects/groups.rst, gitlab/v4/objects/groups.py, gitlab/v4/objects/hooks.py, tests/functional/api/test_groups.py, tests/unit/objects/test_hooks.py, tests/unit/objects/test_projects.py
=> feat(api): add group hooks

gitlab/mixins.py
Also note what should be changed
=> fix(mixins): improve deprecation warning

.github/workflows/docs.yml, .github/workflows/test.yml, setup.py, tox.ini
Just added this as `feat` so it shows up in the changelog but I can change it as well.
=> feat(build): officially support and test python 3.10

gitlab/client.py
types-requests==2.25.9 changed a type-hint. Update code to handle this
change.
=> chore: fix type-check issue shown by new requests-types

docs/api-objects.rst, docs/gl_objects/merge_trains.rst, gitlab/v4/objects/__init__.py, gitlab/v4/objects/merge_trains.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_merge_trains.py
Add support for [merge trains](https://docs.gitlab.com/ee/api/merge_trains.html)
=> feat(api): add merge trains

docs/gl_objects/notes.rst, gitlab/v4/objects/award_emojis.py, gitlab/v4/objects/notes.py
Added support for notes/emojis/discussions on group epics
(also fixed `ProjectSnippetNote` to use the correct `AwardEmojiManager`)
=> feat(api): add support for epic notes

.github/workflows/lint.yml, .github/workflows/pre_commit.yml, .pre-commit-config.yaml, gitlab/v4/objects/merge_request_approvals.py, gitlab/v4/objects/projects.py, pyproject.toml, requirements-lint.txt, tox.ini
Initial pylint check is added. A LONG list of disabled checks is also
added. In the future we should work through the list and resolve the
errors or disable them on a more granular level.
=> chore: add initial pylint check

.github/workflows/test.yml, tests/unit/test_config.py
Add running the unit tests on windows-latest and macos-latest with
Python 3.10.
=> chore: add running unit tests on windows/macos

tests/unit/test_config.py
=> chore: fix unit test if config file exists locally

.renovaterc.json
https://docs.renovatebot.com/modules/manager/pre-commit/#additional-information
Related to https://github.com/python-gitlab/python-gitlab/pull/1753
=> chore(ci): enable renovate for pre-commit

docs/gl_objects/discussions.rst
docs: correct documentation for updating discussion note
Issue #1777
=> docs: correct documentation for updating discussion note

tests/unit/test_gitlab.py
Explicitly registering the responses inside the test cases ended up actually being a little less verbose than writing dedicated fixtures, and also helps with header cleanup in  #1788 as well as reducing the code changes migrating from httmock.
=> test: drop httmock dependency in test_gitlab.py

tests/unit/test_gitlab.py
Built on top of https://github.com/python-gitlab/python-gitlab/pull/1787.
I tried parametrizing tests at first but this seemed cleaner in the end, it would get overly complicated because of https://github.com/pytest-dev/pytest/issues/349.
=> test: reproduce missing pagination headers in tests 

tests/functional/cli/test_cli.py
Fix functional test failure if config present and configured with
token.
Closes: #1791
=> chore: fix functional test failure if config present

docs/conf.py
To avoid unnecessary issues being reported for people who dont read release notes :grin:
=> chore: add temporary banner for v3

tests/functional/api/test_merge_requests.py
Add a functional test of test mergerequest.get() and
mergerequest.get(..., lazy=True)
Closes: #1425
=> chore: add functional test of mergerequest.get()

.gitignore
Leftover from https://github.com/python-gitlab/python-gitlab/pull/1824
=> chore: ignore intermediate coverage artifacts

gitlab/exceptions.py, gitlab/v4/objects/groups.py, tests/functional/api/test_groups.py, tests/functional/fixtures/.env, tests/unit/objects/test_groups.py
This is all @sattlerc's work, with added tests based on the project transfer tests.
=> feat: add support for Groups API method transfer()

tests/unit/mixins/test_mixin_methods.py
Convert from httmock to responses in test_mixins_methods.py
This leaves only one file left to convert
=> test: use 'responses' in test_mixins_methods.py

docs/gl_objects/releases.rst
Fixes #1850 
@max-wittig @nejch willing to have a look on it?
=> Enhance releases API docs for CI_JOB_TOKEN usage

tests/meta/test_v4_objects_imported.py
Add a test to make sure that all of the `gitlab/v4/objects/` files are
imported in `gitlab/v4/objects/__init__.py`
=> test: add a meta test to make sure that v4/objects/ files are imported

docs/ext/docstrings.py, gitlab/base.py, gitlab/cli.py, gitlab/client.py, gitlab/config.py, gitlab/mixins.py, gitlab/types.py, gitlab/utils.py, gitlab/v4/cli.py, gitlab/v4/objects/appearance.py, gitlab/v4/objects/files.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/keys.py, gitlab/v4/objects/merge_requests.py, gitlab/v4/objects/repositories.py, gitlab/v4/objects/runners.py, gitlab/v4/objects/services.py, gitlab/v4/objects/settings.py, setup.py, tests/functional/api/test_gitlab.py, tests/functional/api/test_projects.py, tests/functional/api/test_users.py, tests/functional/conftest.py, tests/meta/test_mro.py, tests/smoke/test_dists.py, tests/unit/objects/test_packages.py, tests/unit/objects/test_todos.py, tests/unit/test_base.py
This mostly makes https://codereview.doctor/python-gitlab/python-gitlab happy, except for a few things we might disagree with. Did a tiny bit of cleanup along the way.
I kind of like the idea of using the dataclass there in case we want to have some common attributes shared between group/projects and then extend them, but let's see if that makes sense.
I split each type of fix into a separate commit for easier review just in case.
=> chore: fix code-review-doctor findings

gitlab/v4/objects/services.py, tests/functional/api/test_services.py, tests/functional/conftest.py
Closes https://github.com/python-gitlab/python-gitlab/issues/191
=> fix(services): use slug for id_attr instead of custom methods

gitlab/client.py
Some endpoints are not returning the `Retry-After` header when
rate-limiting occurrs. In those cases use the `RateLimit-Reset` [1]
header, if available.
Closes: #1889
[1] https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#response-headers
=> fix: support RateLimit-Reset header

docs/gl_objects/deploy_tokens.rst, gitlab/v4/objects/deploy_tokens.py, tests/functional/api/test_deploy_tokens.py
Part of https://about.gitlab.com/releases/2022/03/22/gitlab-14-9-released/#new-api-endpoints-for-keys-and-tokens
=> feat(objects): support getting project/group deploy tokens by id

.commitlintrc.json, .github/workflows/lint.yml, .gitignore, .pre-commit-config.yaml, requirements-lint.txt, tox.ini
See https://github.com/python-gitlab/python-gitlab/pull/1996#issue-1221171591
This also needs a small change in required checks temporarily
=> chore(ci): replace commitlint with commitizen

gitlab/v4/cli.py
Python 3.11 added an additional check in the argparse libary which
detected duplicate subparsers being added. We had duplicate subparsers
being added.
Make sure we don't add duplicate subparsers.
Closes: #2015
=> fix: duplicate subparsers being added to argparse

.github/workflows/release.yml
Oops, forgot the prefix, silly me.
=> chore(ci): fix prefix for action version

gitlab/mixins.py, gitlab/types.py, gitlab/utils.py, gitlab/v4/objects/epics.py, gitlab/v4/objects/files.py, gitlab/v4/objects/issues.py, tests/unit/mixins/test_mixin_methods.py
See the commit messages for more details.
- Use an f-string instead of % formatting
- Move `validate_attrs` to be part of the `RequiredOptional` class.
=> Clean-up the `validate_attrs` method/function

docs/api-usage.rst, docs/ext/manager_tmpl.j2
Add the mutually exclusive attributes feature to documentation.
=> docs: update docs to reflect addition of mutually exclusive attributes

.dockerignore, .gitlab-ci.yml, Dockerfile, README.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/1852.
Tested in https://gitlab.com/nejc/python-gitlab/-/pipelines/453883269 with a fake tag, resulting images:
https://gitlab.com/nejc/python-gitlab/container_registry/2676067
@rassie hopefully this covers your use case.
=> feat(docker): provide a Debian-based slim image

docs/api-objects.rst, docs/gl_objects/environments.rst, docs/gl_objects/protected_environments.rst, gitlab/v4/objects/environments.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_environments.py
- https://docs.gitlab.com/ee/api/protected_environments.html
- https://github.com/python-gitlab/python-gitlab/issues/1130
no write operation are implemented yet as I have no use case right now
and am not sure how it should be done
=> feat: Add support for Protected Environments

.pre-commit-config.yaml, docs/api/gitlab.rst, docs/conf.py, gitlab/__init__.py, gitlab/const.py, gitlab/exceptions.py, pyproject.toml
Closes https://github.com/python-gitlab/python-gitlab/issues/2063
=> chore(gitlab): fix implicit re-exports for mypy

tests/functional/conftest.py
Have been seeing timeout issues more and more. Increase timeout from
200 seconds to 300 seconds (5 minutes).
=> chore(ci): increase timeout for docker container to come online

docs/gl_objects/users.rst, gitlab/exceptions.py, gitlab/v4/objects/users.py, tests/unit/objects/test_users.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1604.
Follow-up to https://github.com/python-gitlab/python-gitlab/pull/2064.
=> feat(users): add approve and reject methods to User

tests/unit/conftest.py, tests/unit/objects/test_project_import_export.py, tests/unit/objects/test_projects.py
Closes #1708
:hammer_and_wrench: with :heart: by [Siemens](https://opensource.siemens.com/)
=> test(projects): add unit tests for projects

gitlab/base.py
Instead of have a multi-nested series of try blocks. Convert it to a
more readable series of `if` statements.
=> chore: simplify multi-nested try blocks

docs/gl_objects/groups.rst, docs/gl_objects/projects.rst
Update the return type of pushrules to surround None with back-ticks
to make it code-formatted.
=> docs: update return type of pushrules

docs/gl_objects/projects.rst, gitlab/v4/objects/projects.py, tests/unit/objects/test_projects.py
Add support for validating a project's CI configuration [1]
[1] https://docs.gitlab.com/ee/api/lint.html
=> feat: add Project CI Lint support

docs/api-objects.rst, docs/cli-examples.rst, docs/cli-usage.rst, docs/gl_objects/ci_lint.rst, docs/gl_objects/projects.rst, gitlab/client.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/ci_lint.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_ci_lint.py, tests/unit/objects/test_projects.py
Built on top of #1896,  does most of the prep work for https://github.com/python-gitlab/python-gitlab/issues/546.
=> feat(cli): add support for global CI lint

gitlab/v4/objects/merge_request_approvals.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2135
=> fix(cli): remove irrelevant MR approval rule list filters

gitlab/v4/objects/epics.py
This is a quick fix for the epic notes feature. If more is needed I'll have to follow up with this later.
Closes https://github.com/python-gitlab/python-gitlab/issues/1142.
=> Fix epic notes

gitlab/v4/objects/users.py, pyproject.toml, tests/functional/api/test_users.py
Enable the `mypy` `strict_equality` check.
=> chore: enable mypy check `strict_equality`

docs/gl_objects/repositories.rst, gitlab/client.py, gitlab/v4/objects/container_registry.py, gitlab/v4/objects/groups.py, tests/unit/objects/test_registry_repositories.py
Related: https://github.com/python-gitlab/python-gitlab/issues/774
=> feat(groups): add support for group-level registry repositories

gitlab/v4/objects/jobs.py
See: 'scope' here: https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs
=> feat: add support for filtering jobs by scope

gitlab/config.py, tests/unit/test_gitlab.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2164.
=> fix(config): raise error when gitlab id provided but no config file or section found

AUTHORS
It's been a while since I've looked at that file :sweat_smile:
=> chore(authors): fix email and do the ABC

docs/gl_objects/projects.rst, gitlab/exceptions.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_projects.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2070
=> feat(projects): add support for project restore API

docs/api-objects.rst, docs/gl_objects/invitations.rst, gitlab/exceptions.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/invitations.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_invitations.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1229.
This was a bit more tedious than I expected, the endpoint feels kind of messy to me :thinking:
=> feat: add support for group and project invitations API

docs/gl_objects/namespaces.rst, gitlab/v4/objects/namespaces.py, tests/functional/api/test_gitlab.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1972
=> feat(namespaces): add support for namespace existence API

tests/functional/conftest.py, tests/functional/fixtures/docker-compose.yml
This reverts commit 67ab24fe5ae10a9f8cc9122b1a08848e8927635d.
=> chore: revert "test(functional): simplify token creation"

tests/conftest.py, tests/functional/cli/test_cli_variables.py, tests/unit/test_config.py, tests/unit/test_gitlab.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2177
=> test: always ensure clean config environment

docs/gl_objects/groups.rst, gitlab/v4/objects/groups.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_groups.py
=> feat(groups): add support for shared projects API

docs/api-objects.rst, docs/gl_objects/iterations.rst, gitlab/v4/objects/__init__.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/iterations.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_iterations.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1417
=> feat: add support for iterations API

gitlab/v4/objects/releases.py
See: https://docs.gitlab.com/ee/api/releases/#list-releases
=> feat: allow sort/ordering for project releases

gitlab/base.py, gitlab/cli.py, gitlab/client.py, gitlab/mixins.py, pyproject.toml, tests/unit/objects/test_projects.py, tests/unit/test_cli.py
Update code so that the `warn_return_any` check passes.
=> chore: enable mypy check `warn_return_any`

docs/cli-examples.rst, docs/gl_objects/personal_access_tokens.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/2200.
If you'd like a wrapper as I mentioned in the issue just let me know and we can add a feature commit.
=> docs: describe self-revoking personal access tokens

docs/cli-examples.rst, docs/gl_objects/projects.rst, gitlab/v4/objects/repositories.py, tests/functional/api/test_repository.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1495
Replaces https://github.com/python-gitlab/python-gitlab/pull/1577
Depended on https://github.com/python-gitlab/python-gitlab/pull/1699
=> feat: add support for merge_base API

.github/workflows/test.yml, requirements-test.txt, tox.ini
=> chore(ci): make pytest annotations work

gitlab/v4/objects/merge_requests.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2282
=> fix(cli): add missing attribute for MR changes

docs/gl_objects/topics.rst, gitlab/exceptions.py, gitlab/v4/objects/topics.py, tests/unit/objects/test_topics.py
https://docs.gitlab.com/ee/api/topics.html#merge-topics
=> feat(api): add support for topics merge API

tests/functional/api/test_topics.py
A followup to @nejch's contribution #2310
=> chore: topic functional tests

CONTRIBUTING.rst, requirements-docker.txt, requirements-test.txt, tests/functional/fixtures/docker.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2328
Closes https://github.com/python-gitlab/python-gitlab/issues/2330
=> chore: revert compose upgrade

tests/functional/api/test_push_rules.py
Make the `test_project_push_rules` test work.
=> test: fix `test_project_push_rules` test

docs/api-objects.rst, docs/gl_objects/statistics.rst, gitlab/client.py, gitlab/v4/objects/statistics.py, tests/functional/api/test_statistics.py, tests/functional/conftest.py, tests/unit/objects/test_statistics.py
=> feat(api): add application statistics

docs/gl_objects/projects.rst, gitlab/v4/objects/projects.py, tests/functional/api/test_import_export.py, tests/unit/objects/test_project_import_export.py
=> feat: add import project from remote support

.github/workflows/rerun-test.yml, CONTRIBUTING.rst
=> feat(ci): Re-Run Tests on PR Comment workflow

docs/gl_objects/groups.rst, gitlab/v4/objects/groups.py, tests/functional/api/test_groups.py, tests/unit/objects/test_groups.py
=> feat: add saml group links

docs/gl_objects/issues.rst, gitlab/v4/objects/events.py, gitlab/v4/objects/issues.py, tests/unit/objects/test_resource_iteration_events.py
* see https://docs.gitlab.com/ee/api/resource_iteration_events.html
=> feat: add resource iteration events

gitlab/client.py, gitlab/http_backends/__init__.py, gitlab/http_backends/requests_backend.py
Initial implementation of http engine concept. The long-term target is to shift all requests/response processing from the client to the http engine. When that is done for requests then it would be easy enough to add another engine, like httpx.
=> feat(client): bootstrap the http backends concept

docs/api-usage.rst, docs/faq.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/2402
Also adds some headings to the FAQ so we have a table of content now that there's a bit more in there.
Feel free to merge whoever gets to this first :)
=> docs(faq): describe and group common errors

requirements-lint.txt, requirements-test.txt, tox.ini
=> chore(tox): ensure test envs have all dependencies

gitlab/v4/objects/pipelines.py
See: https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines
Added in GitLab 14.3
=> feat: allow filtering pipelines by source

docs/api-objects.rst, docs/gl_objects/resource_groups.rst, gitlab/v4/objects/__init__.py, gitlab/v4/objects/projects.py, gitlab/v4/objects/resource_groups.py, tests/unit/objects/test_resource_groups.py
Closes #2395 
Feel free to merge whoever gets to this first :)
=> feat(api): add support for resource groups

tests/functional/api/test_gitlab.py, tests/functional/conftest.py
Mainly for https://github.com/python-gitlab/python-gitlab/pull/2392.
Feel free to merge whoever sees/approves this first ;)
=> test(functional): do not require config file

docs/api-objects.rst, docs/gl_objects/bulk_imports.rst, docs/gl_objects/projects.rst, gitlab/client.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/bulk_imports.py, tests/functional/api/test_bulk_imports.py, tests/unit/conftest.py, tests/unit/objects/test_bulk_imports.py
=> feat(api): add support for bulk imports API

gitlab/http_backends/requests_backend.py
main is broken. This PR is fixing it.
=> refactor: add reason property to RequestsResponse

docs/gl_objects/groups.rst, gitlab/v4/objects/groups.py, tests/unit/objects/test_groups.py
For issue 
https://github.com/python-gitlab/python-gitlab/issues/2453
=> feat(group): add support for group restore API

docs/gl_objects/issues.rst
=> docs: fix typo in issue docs

gitlab/cli.py, requirements-lint.txt, requirements-test.txt
Update the `requirements-*` files.
In order to update mypy==1.0.0 we need to also update
responses==0.22.0
Fix one issue found by `mypy`
Leaving updates for `precommit` to be done in a separate commit by
someone.
=> chore(deps): update mypy (1.0.0) and responses (0.22.0)

.renovaterc.json
Closes https://github.com/python-gitlab/python-gitlab/issues/2482
=> chore(renovate): bring back custom patterns

docs/api-usage-advanced.rst
Closes #2425 
Noticed we also had the docs scattered a bit, consolidated them a bit here.
=> docs(advanced): clarify netrc, proxy behavior with requests

gitlab/client.py, gitlab/utils.py, tests/unit/test_utils.py
=> fix(client): properly parse content-type when charset is present

.pre-commit-config.yaml, .renovaterc.json
Bumping versions for mypy pre-commit hook and fixing renovate config file to pick up
mypy repo versions
=> chore(pre-commit): Bumping versions

docs/gl_objects/issues.rst, gitlab/v4/objects/events.py, gitlab/v4/objects/issues.py, tests/functional/api/test_issues.py
Add support for resource_weight_event in ProjectIssue see https://docs.gitlab.com/ee/api/resource_weight_events.html
=> feat: add resource_weight_event for ProjectIssue

docs/gl_objects/personal_access_tokens.rst, gitlab/v4/objects/personal_access_tokens.py, tests/unit/objects/test_personal_access_tokens.py
=> feat(objects): support fetching PATs via id or `self` endpoint

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/pre_commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, .pre-commit-config.yaml, requirements-lint.txt, requirements-precommit.txt, requirements-test.txt, requirements.txt
=> chore(deps): update all non-major dependencies

gitlab/__init__.py, gitlab/_version.py
=> chore: update copyright year to include 2023

requirements-docs.txt
=> chore: update sphinx from 5.3.0 to 6.2.1

docs/gl_objects/group_access_tokens.rst, docs/gl_objects/project_access_tokens.rst
expires_at is now required
Upstream MR: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124964
=> docs(access_token): adopt token docs to 16.1

requirements-docker.txt, requirements-lint.txt, requirements-test.txt, setup.py
Fixes issue with CI having error:
`AttributeError: cython_sources`
=> chore: update PyYAML to 6.0.1

requirements-test.txt, requirements.txt, tests/unit/objects/conftest.py, tests/unit/objects/test_badges.py, tests/unit/objects/test_group_access_tokens.py, tests/unit/objects/test_groups.py, tests/unit/objects/test_job_artifacts.py, tests/unit/objects/test_members.py, tests/unit/objects/test_packages.py, tests/unit/objects/test_personal_access_tokens.py, tests/unit/objects/test_project_access_tokens.py, tests/unit/objects/test_project_merge_request_approvals.py, tests/unit/objects/test_projects.py, tests/unit/objects/test_registry_repositories.py, tests/unit/objects/test_releases.py, tests/unit/objects/test_secure_files.py, tests/unit/objects/test_todos.py, tests/unit/objects/test_topics.py, tests/unit/objects/test_users.py, tests/unit/objects/test_variables.py
~~At the moment need to pin `urllib3<2` as unit tests break.~~
Closes: #2626
=>  chore(deps): update dependency requests to v2.31.0 [security]

tests/functional/cli/conftest.py, tests/functional/cli/test_cli.py, tests/functional/cli/test_cli_projects.py, tests/functional/cli/test_cli_variables.py
Warnings were being raised. Resolve those warnings.
=> test: correct calls to `script_runner.run()`

.readthedocs.yml
Closes https://github.com/python-gitlab/python-gitlab/issues/2652
=> chore(rtd): fix docs build on readthedocs.io

.readthedocs.yml
=> chore(rtd): use readthedocs v2 syntax

docs/gl_objects/projects.rst, docs/gl_objects/snippets.rst, gitlab/v4/objects/snippets.py, tests/functional/api/test_snippets.py
=> fix(snippets): allow passing list of files

docs/api-objects.rst, docs/gl_objects/job_token_scope.rst, gitlab/mixins.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/job_token_scope.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_job_token_scope.py
=> feat(api): add support for job token scope settings

docs/api-usage.rst, gitlab/client.py, gitlab/utils.py, tests/functional/cli/test_cli.py, tests/unit/test_utils.py
Tiny step towards https://github.com/python-gitlab/python-gitlab/issues/2080
=> feat(client): mask tokens by default when logging

.github/workflows/release.yml, MANIFEST.in, tests/smoke/test_dists.py
=> fix(build): include py.typed in dists

gitlab/v4/objects/artifacts.py
=> Fix argument docstring in artifacts

docs/gl_objects/protected_branches.rst, gitlab/v4/objects/branches.py, tests/functional/api/test_projects.py
Closes #2390
p_b.allow_force_push = True
p_b.save()
=> feat(api): allow updating protected branches

gitlab/cli.py, tests/functional/cli/conftest.py, tests/functional/cli/test_cli.py
Related to https://github.com/python-gitlab/python-gitlab/issues/2775
=> feat(cli): allow skipping initial auth calls

CONTRIBUTING.rst, docs/cli-examples.rst, tests/functional/api/test_boards.py, tests/functional/api/test_bulk_imports.py, tests/functional/api/test_current_user.py, tests/functional/api/test_deploy_keys.py, tests/functional/api/test_deploy_tokens.py, tests/functional/api/test_epics.py, tests/functional/api/test_gitlab.py, tests/functional/api/test_groups.py, tests/functional/api/test_import_export.py, tests/functional/api/test_issues.py, tests/functional/api/test_lazy_objects.py, tests/functional/api/test_merge_requests.py, tests/functional/api/test_projects.py, tests/functional/api/test_releases.py, tests/functional/api/test_repository.py, tests/functional/api/test_services.py, tests/functional/api/test_snippets.py, tests/functional/api/test_topics.py, tests/functional/api/test_users.py, tests/functional/api/test_variables.py, tests/functional/cli/test_cli_repository.py, tests/functional/cli/test_cli_resource_access_tokens.py, tests/functional/cli/test_cli_users.py, tests/functional/cli/test_cli_v4.py, tests/functional/conftest.py, tests/functional/fixtures/.env, tests/functional/fixtures/set_token.rb, tests/functional/helpers.py
- Updates tests to use Gitlab 16 image
- Updates test to handle changes to the underlying APIs
- Adds programmatic date times to Access Token tests
=> test: update integration tests to run using Gitlab 16

gitlab/v4/objects/files.py
=> chore: add type info for ProjectFile.content

pyproject.toml
Update the minimum versions of the dependencies in the pyproject.toml file.
This is related to PR #2878
=> fix(deps): update minimum dependency versions

docs/gl_objects/variables.rst
Add a note about using `filter` when updating a variable.
Closes: #2835
Closes: #1387
Closes: #1125
=> docs: variables: add note about `filter` for updating

docs/api-objects.rst, docs/gl_objects/cluster_agents.rst, gitlab/v4/objects/__init__.py, gitlab/v4/objects/cluster_agents.py, gitlab/v4/objects/projects.py, tests/unit/objects/test_cluster_agents.py
=> feat(api): add support for project cluster agents

docs/faq.rst
Fix a wrong variable name in example code in the FAQ. This should help people understand that example more easily.
This pull request fixes documentation. No additional tests are necessary, apart from a human review.
=> docs(faq): correct the attribute fetching example

gitlab/client.py, gitlab/utils.py, tests/unit/test_retry.py
Needed for #1357 
Follow-up to #2967
=> refactor(client): move retry logic into utility

gitlab/client.py, gitlab/utils.py, requirements-lint.txt, requirements-test.txt, tests/unit/test_graphql.py, tests/unit/test_retry.py
Related to https://github.com/python-gitlab/python-gitlab/issues/1357
=> feat(client): add retry handling to GraphQL client

gitlab/client.py, tests/unit/test_graphql.py
Related to https://github.com/python-gitlab/python-gitlab/issues/1357
Follow-up to and depends on #2973
=> feat(client): make retries configurable in GraphQL

docs/gl_objects/pipelines_and_jobs.rst
Fixed documentation typo in pipeline and jobs section.
=> docs(objects): fix typo in get latest pipeline

.gitlab-ci.yml
As documented in https://blog.siemens.com/2022/07/building-a-multi-arch-container-image-in-unprivileged-containers/.
Requested by our colleagues at Siemens for use in CI components.
=> feat(build): build multi-arch images

gitlab/v4/objects/files.py
=> fix(files): correctly raise GitlabGetError in get method

docs/gl_objects/pagesdomains.rst, gitlab/v4/objects/pages.py, gitlab/v4/objects/projects.py, tests/functional/api/test_projects.py
Implements https://docs.gitlab.com/ee/api/pages.html
Closes https://github.com/python-gitlab/python-gitlab/issues/2832
=> feat(api): add support for project Pages API

docs/gl_objects/users.rst
=> docs(users): update Gitlab docs links

tests/unit/base/test_rest_object.py
This should get us to 100% test coverage on `gitlab/base.py`
=> test: add test for `to_json()` method

gitlab/const.py
See https://docs.gitlab.com/ee/api/members.html#roles
Context: https://about.gitlab.com/blog/2024/11/25/introducing-gitlabs-new-planner-role-for-agile-planning-teams/
=> feat(const): add new Planner role to access levels

.renovaterc.json
Reverts https://github.com/python-gitlab/python-gitlab/pull/3064
See https://github.com/lundberg/respx/pull/278
=> chore(renovate): update httpx and respx again

.pre-commit-config.yaml, gitlab/const.py, requirements-lint.txt
mypy 1.14 has a change to Enum Membership Semantics: https://mypy.readthedocs.io/en/latest/changelog.html
Resolve the issues with Enum and typing, and update mypy to 1.14
=> chore(deps): update mypy to 1.14 and resolve issues

gitlab/v4/objects/snippets.py, tests/functional/api/test_gitlab.py, tests/functional/api/test_snippets.py, tests/functional/conftest.py
As seen in:
https://github.com/python-gitlab/python-gitlab/pull/3069/files
Resolve the warnings seen.
=> Fix multiple deprecation and warnings seen in the CI

docs/gl_objects/deploy_keys.rst, gitlab/v4/objects/deploy_keys.py, tests/functional/api/test_deploy_keys.py
Closes https://github.com/python-gitlab/python-gitlab/issues/3118.
=> feat(api): add support for adding instance deploy keys

docs/api-objects.rst, docs/gl_objects/member_roles.rst, gitlab/client.py, gitlab/v4/objects/__init__.py, gitlab/v4/objects/groups.py, gitlab/v4/objects/member_roles.py, tests/functional/api/test_member_roles.py, tests/unit/objects/test_member_roles.py
Implements https://github.com/python-gitlab/python-gitlab/issues/2801
=> feat: adds member role methods

tests/functional/conftest.py, tests/functional/fixtures/docker-compose.yml
=> test(functional): switch to new runner registration API

docs/ext/docstrings.py, requirements-docs.txt
https://github.com/sphinx-doc/sphinx/commit/7ba762870f83175848ff1cd94a1b783ecde57f9a
broke us
=> chore: upgrade to sphinx 8.2.1 and resolve issues

docs/gl_objects/job_token_scope.rst
Just cleaning up what looks to be a few copy&paste leftovers
=> docs(job_token_scope): fix typo/inconsistency

gitlab/v4/objects/notes.py
Add ListMixin to ProjectIssueDiscussionNoteManager and ProjectMergeRequestDiscussionNoteManager
=> Update notes api for ProjectIssueDiscussionNoteManager and ProjectMergeRequestDiscussionNoteManager

gitlab/v4/objects/jobs.py
See: https://docs.gitlab.com/api/jobs/#list-project-jobs
=> feat(api): add missing ProjectJob list filters
