- gitlab/__init__.py
Sorry, I hit enter too early.
Fetching a single Merge Request didn't work because of the wrong url. I was puzzled by this gitlab inconsistency, but it is like that. See 
https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/merge_requests.md
I am working with gitlab 7.13.4
Regards Stefan
> Fix error when fetching single MergeRequests

- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
This implements iteration/pagination of list() results for #63
> python-gitlab Issue #63 - implement pagination for list()

- gitlab/__init__.py
GitLab add 'confirm' field support to its API since 7.9.0. However, it takes `'false'` string only when the content type of request is set to 'application/json'. So I just add `confirm` to `optionalCreateAttrs` list and override `_data_for_gitlab` to make sure `confirm` is converted to boolean string.
It has been tested on GitLab HQ 7.14.3 and API is v3.
Additional info: <https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1281>
> Can bypassing confirm when creating new user now

- gitlab/cli.py
Sort types explicitly by name to fix unorderable types TypeError in
Python 3.
The call to sort() on cli.py line 259 produced the error:
TypeError: unorderable types: type() < type()
> Use name as sort key to fix Python 3 TypeError

- gitlab/__init__.py
- gitlab/objects.py
- Forks a project into the user namespace of the authenticated user.
- Allows modification of the forked relationship between existing projects (for admins)
> add fork project support (#Refs 74)

- gitlab/objects.py
Support commit status updates.  Commit status can be set by a POST to
the appropriate commit URL.  The status can be updated by a subsequent
POST to the same URL with the same `name` and `ref`, but different
values for `state`, `description`, etc.
> Support setting commit status

- gitlab/objects.py
A couple of bugs are preventing `User.json()` from working:
* the `Gitlab` class has not been imported into `objects.py`
* the `jsonEncoder` class does not skip over `BaseManager` attributes, causing `json.dumps()` to raise an exception
These commits fix the above issues.
> Fix User.json()

- gitlab/objects.py
call GitlabObject.__init__(self, gl, ...)
with self.gitlab(gitlab.Gitlab) instread self(BaseManager)
> fix GitlabObject creation in _custom_list

- gitlab/objects.py
- gitlab/tests/test_manager.py
- tools/python_test.py
Add support for `/users?search=foo` and `/users?username=foo`.
Also, in order to make it easier to write tests for these new features, add:
* `GitlabObject.as_dict()`, which is the same as calling `json.loads()` on the output of `GitlabObject.json()`
* `GitlabObject.__eq__()` and `GitlabObject.__ne__()`, which checks the dictionaries returned by `GitlabObject.as_dict()` for equivalence
> Add support for searching for users and getting a user by username

- gitlab/objects.py
More informations regarding this issue:
Operating system: Debian Wheezy, with Python 3.2 and the last
version of python-gitlab.
The gitlab module raised this exception, because of the 'u' (Unicode):
Traceback (most recent call last):
File "push_settings.py", line 14, in <module>
from helper import ROOT_EMAIL, ADMINS, git, old_git
File "/opt/scripts/gitlab/helpers/helper.py", line 25, in <module>
from gitlab import Gitlab
File "/opt/scripts/gitlab/helpers/gitlab/__init__.py", line 32, in <module>
from gitlab.objects import *  # noqa
File "/opt/scripts/gitlab/helpers/gitlab/objects.py", line 546
selfdict.pop(u'password', None)
^
SyntaxError: invalid syntax
It is a recent change:
01802c0 (Richard Hansen 2016-02-11 22:43:25 -0500 546) selfdict.pop(u'password', None)
01802c0 (Richard Hansen …
> Fix the 'invalid syntax' on Python 3.2, because of u'password'

- gitlab/__init__.py
The session instance will make it easier for setting up once headers, including
the authentication payload, and it's also making it easier to override HTTP queries
handling, when using [betamax](https://github.com/sigmavirus24/betamax) for recording
and replaying the test suites.
> Adding a Session instance for all HTTP requests

- gitlab/objects.py
According to the [GitLab API Docs][1] Issue comments can be updated by api calls. This very minor change enables this in python-gitlab
This is useful to me and perhaps others for things like annotating comments with references to external issue trackers not supported in GitLab already. This change would allow notes on issues to be modified and saved, for example:
```python
import os
from gitlab import Gitlab
gl = Gitlab(os.environ['GITLAB_HOST'], os.environ['GITLAB_TOKEN'])
note = gl.project.get('adamreid/test').issues.get(1).notes.get(1)
note.body = note.body.replace('issue:1234','issue:[1234](http://issues.example.com/issue/1234)')
note.save()
```
[1]:http://doc.gitlab.com/ce/api/notes.html#modify-existing-issue-note
> Enable updates on ProjectIssueNotes

- gitlab/__init__.py
I had troubles iterating through all projects and changing some settings. The save method failed and I figured out that the 'next_url' attribute is still set and used in the _construct_url method.
This is an attempt to fix this, I might have missed something ...
> Remove 'next_url' from kwargs before passing it to the cls constructor.

- gitlab/objects.py
I add one line that includes "title" to be an optional command line argument.
> Fix: --title is required argument, when in reality optional

- gitlab/objects.py
Do you handle incompatible changes between GitLab versions somehow?
> Added a new project attribute to enable the container registry.

- gitlab/objects.py
The api_url attribute is mandatory at least since GitLab 8.11. Otherwise
server returns gitlab.exceptions.GitlabUpdateError: 400: 400 (Bad request) "api_url" not given.
Keeps the parameter as optional to maintain backward compatibility with older GitLab
versions.
> JIRA service - add api_url to optional attributes

- gitlab/objects.py
'enabled_git_access_protocolgravatar_enabled' were two distinct values in ApplicationSettings.optionalUpdateAttrs.
> Missing coma concatenates array values

- docs/gl_objects/builds.py
- docs/gl_objects/builds.rst
- gitlab/exceptions.py
- gitlab/objects.py
This adds `ProjectBuild.erase()`.
We can't use the existing delete() functionality, because GitLab uses
`POST /projects/:id/builds/:build_id/erase` to erase a build. Instead of
overriding delete(), we add a separate erase() method to keep the naming
consistent, and allow potentially more fine-grained operations in the
future.
- https://docs.gitlab.com/ce/api/builds.html#erase-a-build
This fixes #158
> Add ProjectBuild.erase()

- gitlab/objects.py
Running play on ProjectBuild raises a GitlabBuildPlayError although the request was successful. It looks like gitlab returns a 200-OK instead of 201-CREATED response and as such always raises an exception.
> Fix ProjectBuild.play raising error even on success

- .gitignore
- gitlab/objects.py
When you fetch tags from a project and try to access the builds through a tag commit object like in the following snippet:
```
client = gitlab.Gitlab(..)
project = client.projects.get('some-id')
tag = project.tags.list()[0]
tag.commit.builds()
```
… then python-gitlab raises an AttributeError in line 1128 in objects.py. This happens because it tries to construct the request url and cannot find `self.project_id`.
```
url = '/projects/%s/repository/commits/%s/builds' % (self.project_id, self.id)
```
When you fetch tags python-gitlab constructs Tag-objects which call `_set_from_dict` internally. Then this method checks if it contains data for subobjects and calls subsequently `_get_object` . At this point the subobjects will be created from the gitlab response data but do not receive any …
> Pass kwargs to object factory

- gitlab/objects.py
Solves #160 
It is questionable though if the iid check should be located here as iids are specific and not available with all gitlab resources.
> Convert response list to single data source for iid requests

- gitlab/objects.py
Erroneously a merge request would return its commit when being queried for its changes. Fixes #177.
> fix bug when retrieving changes for merge request

- docs/gl_objects/deploy_keys.py
- docs/gl_objects/deploy_keys.rst
- gitlab/exceptions.py
- gitlab/objects.py
To solve the issue https://github.com/gpocentek/python-gitlab/issues/179 I added 2 new features to the class ProjectKeyManager: enable_deploy_key() and disable_deploy_key() .
> Feature: enable / disable the deploy key in a project

- gitlab/objects.py
I'm getting the following 400 error when using `merge`:
```
File "/usr/local/lib/python2.7/site-packages/gitlab/objects.py", line 1533, in merge
raise_error_from_response(r, errors)
File "/usr/local/lib/python2.7/site-packages/gitlab/exceptions.py", line 168, in raise_error_from_response
response_body=response.content)
gitlab.exceptions.GitlabOperationError: 400: {"error":"should_remove_source_branch is invalid"}
```
It seems like Gitlab has changed their validations - using `True` seems to work.
> Fix `should_remove_source_branch`

- gitlab/objects.py
GitLab simplified the configuration for JIRA service and renamed most of
the fields. To maintain backward compatibility all mandatory fields were
moved to optional section. 
See: https://docs.gitlab.com/ce/api/services.html#jira
**Example of exception it fixes**:
`gitlab.exceptions.GitlabUpdateError: 400: 400 (Bad request) "url" not given`
> Fix JIRA service editing for GitLab 8.14+

- docs/gl_objects/projects.py
- docs/gl_objects/projects.rst
Docs haven't been updated since archive() and unarchive() have been reintroduced.
> Update project.archive() docs

- gitlab/objects.py
The Gitlab API provides the possibility to check the option "delete source branch when merge is accepted" [(here)](https://docs.gitlab.com/ce/api/merge_requests.html#create-mr). This PR allows to make use of this API feature.
> add 'delete source branch' option when creating MR

- docs/gl_objects/commits.py
- docs/gl_objects/commits.rst
- gitlab/cli.py
- gitlab/exceptions.py
- gitlab/objects.py
This is a possible implementation for addressing #235. It allows to cherry pick individual commits through the Gitlab API both from the python code as well as from the command line. The documentation has been updated.
> Provide API wrapper for cherry picking commits

- gitlab/objects.py
- tools/python_test.py
Add `parent_id` attribute support when creating groups, so we can create nested groups.
I'm not sure if this is the only change needed, but it is working on my local copy and I have successfully created nested groups while migrating SVN to GitLab.
> Add support for nested groups

- gitlab/objects.py
This is done to enable support for paths with spaces and other special characters
> Fixed repository_tree and repository_blob path encoding

- gitlab/v3/objects.py
- gitlab/v4/objects.py
Fixes AttributeError on Python 3, as `urlencode` function has been moved from `urllib` to `urllib.parse` module.
`six.moves.urllib.parse.urlencode()` is an py2.py3 compatible alias of `urllib.parse.urlencode()` on Python 3, and of `urllib.urlencode()` on Python 2.
> import urlencode() from six.moves.urllib.parse instead of from urllib

- gitlab/v4/objects.py
These are being returned in the live API, but can't set them.
> Add new event types to ProjectHook

- gitlab/v4/objects.py
optionalCreateAttrs was set twice in GroupMember due to possible copy-paste error. This corrects the second call from optionalCreateAttrs to optionUpdateAttrs.
> Missing expires_at in GroupMembers update

- .travis.yml
- tox.ini
Add Python 3.6 environments to `tox.ini` and `.travis.yml`.
> Declare support for Python 3.6

- docs/cli.rst
I find these sort of links very user friendly 😅
> Docs 📖: Add link to gitlab docs on obtaining a token

- gitlab/__init__.py
- gitlab/base.py
- gitlab/tests/test_base.py
- gitlab/tests/test_gitlab.py
- gitlab/tests/test_gitlabobject.py
Addresses and closes https://github.com/python-gitlab/python-gitlab/issues/345
Make gitlab.Gitlab, base.GitlabObject and base.RESTObject instances pickle-able.
> Module`s base objects serialization

- gitlab/v3/objects.py
- gitlab/v4/objects.py
Add support for mattermost service.
I hope this is all I need to do:)
> Add mattermost service support

- gitlab/__init__.py
Addresses #163 
Small change that adds support for Oauth tokens.  Follows the same flow as the standard private token - instead of setting the`PRIVATE-TOKEN` header sets `Authorization`.  Deprecated methods have not been updated/changed.  Existing open PR's for this issue haven't been used as they're over a year old and the codebase seems to have changed rather dramatically. 
There's possibly a slight issue with providing both `private_token` and `oath_token`, as `private_token` will silently take precedence maybe a warning or error would be clearer. I think the chance of a user actually doing that is pretty slim though.
I've verified against a v0.10 gitlab (v4 API). Shouldn't be any break to the existing interface.
Let me know if you've got any questions.
> Oauth token support

- gitlab/v3/objects.py
It seems that the GitLab API gives HTTP response code 201 ("created") when
successfully subscribing to an object, not 200.
> Expected HTTP response for subscribe is 201

- gitlab/mixins.py
When saving an issue we send the updated data only. 
However the server expect at least one parameter to be provided,
otherwise it fails with an exception.
Check whether we have some update to send, otherwise skip
the update altogether.
> mixins.py: Avoid sending empty update data to issue.save

- docs/gl_objects/builds.py
- docs/gl_objects/builds.rst
- gitlab/v4/objects.py
This PR adds a manager for jobs within a pipeline, so you can say `gl.projects.get(prid).pipelines.get(plid).jobs.list()` to list all of the jobs within a single pipeline (in GitLab v4).
Please let me know if there are any tests I should add. The existing UTs still pass.
> Add manager for jobs within a pipeline.

- docs/gl_objects/builds.py
- docs/gl_objects/builds.rst
Going through an object adds a lot of complication.
Adding example for unzipping on the fly
> Simplify the example for streamed artifacts

- gitlab/v4/objects.py
Trigger_pipeline returns nothing, which makes it difficult to track the pipeline being trigger.
Next PR will be about updating a pipeline object to get latest status (not sure yet the best way to do it)
> make trigger_pipeline return the pipeline

- docs/gl_objects/projects.py
- gitlab/v3/cli.py
- gitlab/v3/objects.py
- gitlab/v4/objects.py
This PR introduces support for project.unshare()
It relies on the https://docs.gitlab.com/ee/api/projects.html#delete-a-shared-project-link-within-a-group API. I needed only the v4 API support but I also added v3 just in case (https://gitlab.com/gitlab-org/gitlab-ce/blob/8-16-stable/doc/api/projects.md). v4 is operational, and v3 may be but is untested.
> Add support for unsharing projects with groups

- docs/gl_objects/builds.py
- docs/gl_objects/builds.rst
- gitlab/mixins.py
- gitlab/tests/test_mixins.py
- gitlab/v4/objects.py
RefreshMixin allows to update a REST object so that you can poll on it.
This is mostly useful for pipelines and jobs, but could be set on most of other objects, with unknown usecases.
> introduce RefreshMixin

- docs/api-usage.rst
- gitlab/__init__.py
- tools/python_test_v4.py
This PR enables python-gitlab to wait if the GitLab rate-limit is hit.
It waits as long as GitLab specifies via the [Retry-After header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After)
GitLab lacks documentation about this feature, but rate-limits can be set in the Admin UI (see screenshot)
and via the settings API.
```json
{
"throttle_authenticated_api_enabled": false,
"throttle_authenticated_api_requests_per_period": 2,
"throttle_authenticated_api_period_in_seconds": 10,
}
```
It can be disabled using the `obey_rate_limit=False` parameter
> feat: obey the rate limit

- gitlab/__init__.py
- gitlab/config.py
- gitlab/mixins.py
- gitlab/tests/test_config.py
> add per_page config option

- gitlab/cli.py
- gitlab/tests/test_cli.py
- gitlab/tests/test_gitlab.py
before
```
............foobar
./home/cjouve/work/gitlab/python-gitlab/gitlab/cli.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmporr_ffy7' mode='r' encoding='UTF-8'>
return open(v[1:]).read()
[Errno 2] No such file or directory: '/thisfileprobablydoesntexist'
......./usr/lib/python3.6/unittest/case.py:1126: DeprecationWarning: assertDictContainsSubset is deprecated
DeprecationWarning)
....................................................................
----------------------------------------------------------------------
Ran 88 tests in 0.562s
OK
```
after:
```
........................................................................................
----------------------------------------------------------------------
Ran 88 tests in 0.533s
OK
```
> silence logs/warnings in unittests

- docs/gl_objects/mr_approvals.rst
- gitlab/mixins.py
- gitlab/v4/objects.py
This PR introduces support for [project-level MR approval configuration](https://docs.gitlab.com/ee/api/merge_request_approvals.html#project-level-mr-approvals).
The 'GET/POST /projects/:id/approvals' and 'PUT /projects/:id/approvers' API endpoint are a bit unusual, so I chose to keep the Python API consistent with them.
Travis build was [ok](https://travis-ci.org/esabouraud/python-gitlab/builds/388814353) before I merged the latest changes from master.
> Add support for project-level MR approval configuration.

- docs/gl_objects/projects.rst
- gitlab/mixins.py
- gitlab/v4/cli.py
- gitlab/v4/objects.py
This PR introduces support for [project push rules](https://docs.gitlab.com/ee/api/projects.html#push-rules) configuration.
>  Add project push rules configuration 

- gitlab/v4/objects.py
Adds missing transfer_project function to the Project object, which provides for an ergonomic way to move projects around.
See https://docs.gitlab.com/ee/api/projects.html#transfer-a-project-to-a-new-namespace
> Add support for project transfers from the projects interface.

- docs/cli.rst
This change fixes a minor type in the table of possible values for options in the global section.
> Minor typo "ou" vs. "or"

- gitlab/v4/objects.py
Was trying to create issues set to a milestone via the CLI. The current code creates a help text of ` [--assignee-idssmilestone-id ASSIGNEE_IDSSMILESTONE_ID]` and then ignores the value. Have tested the change in my PIP user install.
> add missing comma in ProjectIssueManager _create_attrs

- docs/gl_objects/projects.rst
- gitlab/v4/objects.py
This PR introduces support for [protected tags](https://docs.gitlab.com/ce/api/protected_tags.html) management.
> Add project protected tags management

- docs/gl_objects/discussions.rst
Hello,
I think there was typo in the discussions docs as the resource has no "discussion" attribute only "discussions"
> [docs] fix discussions typo

- gitlab/__init__.py
- gitlab/exceptions.py
* Depending on the request Gitlab has a 'message' or 'error' attribute
in the json data, handle both
* Add some consistency by converting messages to unicode or str for
exceptions (depending on the python version)
Closes #616
> Improve error message handling in exceptions

- docker-entrypoint.sh
Fixes the problem of passing spaces in the arguments to the docker entrypoint.
Before this fix, there was virtually no way to pass spaces in arguments such as task description.
> fix: docker entry point argument passing

- Dockerfile
In order to use the YAML output, PyYaml needs to be installed on the docker image.
This commit adds the installation to the dockerfile as a separate layer.
> fix: enable use of YAML in the CLI

- docs/gl_objects/protected_branches.rst
- gitlab/v4/objects.py
This PR introduces support for protected branches [access control options introduced in GitLab 10.3](https://docs.gitlab.com/ee/api/protected_branches.html#example-with-user--group-level-access).
Fix #653
> Issue 653 Add access control options to protected branch creation

- docs/api-usage.rst
- gitlab/__init__.py
- tools/python_test_v4.py
This PR does two things: a) implements an exponential backoff in the case that we are throttled and "Retry-After" isn't in the response header (this currently causes a `KeyError`), b) fix an integration test because we were decoding something that was already a string.
Closes https://github.com/python-gitlab/python-gitlab/issues/632.
> Fix missing "Retry-After" header and fix integration tests

- RELEASE_NOTES.rst
- docs/api-usage.rst
- docs/gl_objects/commits.rst
- docs/gl_objects/users.rst
- gitlab/__init__.py
- tools/python_test_v4.py
Provide another way to send data to gitlab with a new `query_parameters`
argument. This parameter can be used to explicitly define the dict of
items to send to the server, so that **kwargs are only used to specify
python-gitlab specific parameters.
Closes #566
Closes #629
> fix(api): avoid parameter conflicts with python and gitlab

- gitlab/__init__.py
- gitlab/v4/objects.py
http_get always tries to interpret the retrieved data if the
content-type is json. In some cases (artifact download for instance)
this is not the expected behavior.
This patch changes http_get and download methods to always get the raw
data without parsing.
Closes #683
> fix(api): Don't try to parse raw downloads

- gitlab/v4/objects.py
I'm sorry for the merge, but I noticed too late that #685 actually removed the merge request pipelines method. This re-adds it
> fix: re-add merge request pipelines

- gitlab/__init__.py
`all` kwarg is used to manage GitlabList generator behaviour.
However, as it is not pop'ed from kwargs, it is sent to Gitlab API.
Some endpoints such as [the project commits](https://docs.gitlab.com/ee/api/commits.html#list-repository-commits) one,
support a `all` attribute.
This means a call like `project.commits.list(all=True, ref_name='master')`
won't return all the master commits as one might expect but all the
repository's commits.
To prevent confusion, the same kwarg shouldn't be used for 2 distinct
purposes.
Moreover according to [the documentation](https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html#examples),
the `all` project commits API endpoint attribute doesn't seem supported.
> Fix all kwarg behaviour

- gitlab/v4/objects.py
This is a proposed fix for #716. While the id-s are integers when gitlab is used as a library, they are strings when used from the CLI. 
Replacement of %d by %s should be safe.
> Fix for #716: %d replaced by %s

- gitlab/cli.py
This makes sure that the global help message wont be printed instead of the command specific one unless we fail to read the configuration file
Currently if you try, for example:
gitlab project list --help
you only get the global argument help message
> Re-enable command specific help messages

- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
When calling from_config on a subclass of gitlab.Gitlab, a gitlab.Gitlab instance was returned, not the subclass.
I've changed the from_config method to a classmethod, so to return the proper class when called.
I've also added 2 tests to test "from_config".
> Make gitlab.Gitlab.from_config a classmethod

- gitlab/v4/objects.py
As of Gitlab 11.6 it is now possible to delete a pipeline - https://docs.gitlab.com/ee/api/pipelines.html#delete-a-pipeline
> feat(GitLab Update): delete ProjectPipeline

- gitlab/__init__.py
- gitlab/v4/objects.py
Errors have not been detected by broken travis runs.
> fix: pep8 errors

- .gitlab-ci.yml
- .travis.yml
- tools/Dockerfile-test
We currently still need to rely on Travis for the docker tests, but I will look into changing that.
Job succeeded on GitLab.com: https://gitlab.com/python-gitlab/python-gitlab/pipelines/60606601
I'm using the GitLab feature to report back to GitHub for my own open source project and it works pretty well: https://github.com/max-wittig/gitlab-languages/commits/master (certainly better than travis)
> chore(ci): use reliable ci system

- gitlab/v4/cli.py
run into 2 cli custom actions related issues while wokring on #759 
- `*Manager` custom actions (`in_obj`=False) ask for *managed* object id for example:
* `$ gitlab project-key enable --help` or
* `$ gitlab runner all --help`
- `*Manager` custom actions (`in_obj`=False) dont get -/_ method name replaced
> Custom cli actions fix

- gitlab/v4/cli.py
Reverts python-gitlab/python-gitlab#760
@gpocentek I'm not sure how to fix the project creation error, when running:
```sh
gitlab project-file create --project-id <id> --file-path README --branch master --content "TEST" --commit-message "test"
```
> Revert "Custom cli actions fix"

- tools/python_test_v4.py
Changes in GitLab make the functional tests fail:
* Some actions add new notes and discussions: do not use hardcoded
values in related listing asserts
* The feature flag API is buggy (errors 500): disable the tests for now
> test: update the tests for GitLab 11.11

- docs/gl_objects/builds.rst
- gitlab/v4/objects.py
- tools/python_test_v4.py
> feature: Implement artifacts deletion

- docs/gl_objects/projects.rst
Having exactly 20 internal and 5 private projects in the group
spent some time debugging this issue.
Hopefully that helped: https://github.com/python-gitlab/python-gitlab/issues/93
Imho should be definitely mention about `all=True` parameter.
Fixes #784
> docs(projects): add mention about project listings

- gitlab/mixins.py
- gitlab/v4/objects.py
- tools/cli_test_v4.sh
- tools/python_test_v4.py
This is a fix to support group labels. It is a fix for #698. This pull request is like the one published recently by @sathieu https://github.com/python-gitlab/python-gitlab/pull/845 with a minor extra change to support subscribable features for GroupLabels. I have used it to programmatically work on group labels for a while now with no issues so far.
This patch extends python-gitlab to support group labels. Take into account that [Gitlab GroupLabels API V4](https://docs.gitlab.com/ee/api/group_labels.html) has currently some shortcomings due to inheritance of group labels from parent groups. For instance, the label id is not used to identify a group label in the API, which is a problem as you may retrieve more than one label with the same name and there is no way to distinguish among …
> feat: Add grouplabel support with subscribable mixin

- gitlab/__init__.py
- gitlab/mixins.py
- gitlab/v4/objects.py
Using mutable default arguments (e.g. `{}` or `[]`) will produce shared instances. More info e.g. [here](https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/).
- Remove empty list default arguments.
- Remove empty dict default arguments.
> Fix mutable default arguments

- docs/gl_objects/projects.rst
- gitlab/v4/objects.py
The `avatar` attribute was already set for projects but it wasn't working because the type was missing.
> Fix avatar uploading for projects

- docs/gl_objects/environments.rst
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
Gitlab supports this: https://docs.gitlab.com/ce/api/environments.html#get-a-specific-environment
I'm using the same `ProjectEnvironment` object, even though retrieving an environment has wildly more attributes (including nested ones). Please let me know if I should add anything else to this.
> feat: add methods to retrieve an individual project environment

- tools/build_test_env.sh
- tools/generate_token.py
- tools/python_test_v4.py
- tools/reset_gitlab.py
* add a new flag -k to reuse the container
* adapt python_test_v4 to be run multiple times
* add reset_gitlab.py to undo changes made by python_test_v4
* use gitlab container from gitlab
* new check when gitlab is started (instead of long sleep)
* simplify generate_token.py with requests-html
> improve functionnal tests

- gitlab/tests/test_gitlab.py
When running unittests python warns that the json file from test_todo()
was still open. Use with to open, read, and create encoded json data
that is used by resp_get_todo().
> Remove warning about open files from test_todo()

- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
session endpoint was removed in gitlab api v4 and api v3 support was removed in python-gitlab 1.5.0
> remove deprecated session auth

- docs/gl_objects/projects.rst
GroupManager.search is removed since 9a66d78, use list(search='keyword') instead
> docs(project): fix group project example

- docs/gl_objects/projects.rst
Also, add an example value for project_id to the other `projects.get()` example.
Resolves #913
> Remove inaccurate projects.get() example

- docs/gl_objects/mr_approvals.rst
- gitlab/v4/objects.py
- tools/ee-test.py
The `approvers` API endpoint is deprecated [1]. GitLab instead uses
the `approval_rules` API endpoint to modify approval settings for
merge requests. This adds the functionality for project-level
merge request approval settings.
Note that there does not exist an endpoint to 'get' a single
approval rule at this moment - only 'list'.
[1] https://docs.gitlab.com/ee/api/merge_request_approvals.html
> fix(projects): support `approval_rules` endpoint for projects

- gitlab/v4/objects.py
Otherwise, we get:
```
File "gitlabracadabra/mixins/labels.py", line 67, in _process_labels
current_label.save()
File "gitlab/exceptions.py", line 267, in wrapped_f
return f(*args, **kwargs)
File "gitlab/v4/objects.py", line 896, in save
self._update_attrs(server_data)
File "gitlab/base.py", line 131, in _update_attrs
self.__dict__["_attrs"].update(new_attrs)
TypeError: 'NoneType' object is not iterable
```
Because `server_data` is `None`.
> fix(labels): ensure label.save() works

- README.rst
v1.8.0 is not available.
```
Unable to find image 'registry.gitlab.com/python-gitlab/python-gitlab:v1.8.0' locally
docker: Error response from daemon: manifest for registry.gitlab.com/python-gitlab/python-gitlab:v1.8.0 not found: manifest unknown: manifest unknown.
```
> README.rst: fix the upstream Docker image reference

- docs/api-usage.rst
- gitlab/__init__.py
> Retry transient HTTP errors

- docs/gl_objects/projects.rst
The function `file.delete()` requires `branch` argument in addition to `commit_message`.
Closes #965
> docs(projects): fix file deletion docs

- gitlab/v4/objects.py
Add more flags for CI variables Create and Update operations.
> feat: add more options for project/group ci variables manipulation

- gitlab/__init__.py
Otherwise the stacktrace is like:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gitlab/__init__.py", line 832, in next
item = self._data[self._current]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "./bot.py", line 241, in <module>
main(sys.argv)
File "./bot.py", line 209, in main
for project in projects:
File "/usr/local/lib/python3.6/site-packages/gitlab/base.py", line 184, in __next__
return self.next()
File "/usr/local/lib/python3.6/site-packages/gitlab/base.py", line 187, in next
data = self._list.next()
File "/usr/local/lib/python3.6/site-packages/gitlab/__init__.py", line 837, in next
self._query(self._next_url)
File …
```
> Nicer stacktrace

- docs/api-usage.rst
- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
Addresses #952
This adds a method to the `ProjectManager` called `import_github`, which maps to the `/import/github` API endpoint. Calling `import_github` will trigger an import operation from <repo_id> into <target_namespace>, using <personal_access_token> to authenticate against github. In practice a gitlab server may take many 10's of seconds to respond to this API call, so we also take the liberty of increasing the default timeout (only for this method invocation).
Unfortunately since `import` is a protected keyword in python, I was unable to follow the endpoint structure with the manager namespace (eg: `gitlab.import.github` is not allowed`). I'm open to suggestions on a more sensible interface.
I'm successfully using this addition to batch-import hundreds of github repositories into …
> feat: add support for /import/github

- docs/cli.rst
- gitlab/cli.py
- setup.py
> feat: add autocompletion support

- rtd-requirements.txt
Stepping thru Sphinx versions from 1.6.5 to 1.7.5 build_sphinx fails.  Once Sphinx == 1.7.6 build_sphinx finished.
> chore: build_sphinx needs sphinx >= 1.7.6

- docs/api-usage.rst
- gitlab/__init__.py
Hi, I removed the docs regarding `email/password` auth since it's no longer supported by `python-gitlab`.
> Update auth docs

- gitlab/__init__.py
- gitlab/v4/objects.py
This also workarounds an GitLab issue, where private_profile, would reset to false if not supplied
> chore(user): update user attributes

- docs/gl_objects/features.rst
- gitlab/utils.py
- gitlab/v4/objects.py
Currently GitLab Features API supports configuring features not only globally or per user, but also per group or project. `python-gitlab` is currently missing this option, thus this PR.
Additionally fixed issue when setting up feature with `None `(null) values, e.g. none `feature_group` or `user`. It caused GitLab to respond with HTTP 500. Thus now we're filtering out `None` values from data.
> Add capability to control GitLab features per project or group

- docs/gl_objects/commits.rst
- gitlab/exceptions.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
- tools/cli_test_v4.sh
- tools/python_test_v4.py
> feat: add support for commit revert API (#991)

- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
Closes #913. This helps with some reverse proxies that return 404 on double slashes.
> Fix: remove trailing slash in base URL 

- tools/build_test_env.sh
I saw this was already tried and discussed in an older PR. I tried to use the readiness endpoint for this, but it turns out gitlab starts reporting OK on all healthchecks before it's fully reconfigured on startup (if you try `docker container logs --follow gitlab-test` in another shell it'll still be restarting services when the script is already at "Pausing to give GitLab some time to finish starting up...".
So it seems waiting for gitlab to report that it's reconfigured might be better. If this isn't enough for CI, then it's when gitlab logs start popping up in the container that it's 100% reliably up and running, so those could be grepped as well.
I can remove the additional log if it's too verbose, I just remember wondering if the script was hanging the first time I ran it so this …
> perf: wait for gitlab to reconfigure instead of using hardcoded sleep

- tools/build_test_env.sh
I had really weird behavior (tests failing, omnibus config wouldn't load properly) until I realized I had a super old gitlab image locally that wasn't being pulled for tests.
This does an explicit docker pull instead of `--pull` since that's only been added [recently](https://github.com/docker/cli/pull/1498) and might not work for everyone, and it should only be a tiny penalty anyway.
I added a CLI flag so this should make it easy to build a CI matrix with tox that tests against several GitLab versions (e.g. latest + 3 last minor releases etc) or to explicitly test against a version reported in an issue. (Although I see currently Travis is excruciatingly slow so not sure if that's desired :D)
> chore: ensure developers use same gitlab image as CI

- docs/api-objects.rst
- docs/gl_objects/applications.rst
- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
GitLab can be used as an OAuth authentication provider. GitLab API allows creating Applications which could benefit from this feature. Currently `python-gitlab` does not support managing OAuth Apps, so I added this here.
Reference: https://docs.gitlab.com/ce/api/applications.html
> feat(api): add support for GitLab OAuth Applications using Applications API

- gitlab/v4/objects.py
The new gitlab api needs a name for the approval rules, added a default one to maintain the python-gitlab api.
The prior pull request wasn't ready for merge, needed this fix.
> fix(objects): Added approval rule name to data

- docs/gl_objects/projects.rst
Using `get()['fetches']['total']` in the example will raise an error:
```
TypeError: 'ProjectAdditionalStatistics' object is not subscriptable
```
Updated to use new method with `get().fetches['total']`
> fix(docs): additional project statistics example

- gitlab/v4/objects.py
This is migating an GitLab issue, which resets the user theme and color scheme, when nothing is provided via the API.
> chore(user): update user attributes to 12.8

- gitlab/tests/objects/test_projects.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
- tools/python_test_v4.py
This will need to be changed for #1025 but I'd like to have some tests before refactoring Export code for #1037.
> test: update tests and params for project export/import

- docs/cli.rst
- docs/gl_objects/commits.rst
- gitlab/tests/objects/test_commits.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
- tools/cli_test_v4.sh
- tools/python_test_v4.py
Closes #1050.
The functional tests currently only test that the server returns the correct 404 response for unsigned commits, since creating signed commits without the API would be a bit convoluted, maybe this can be added later? https://gitlab.com/gitlab-org/gitlab/-/issues/19185 might also help with this.
However, I've tested this against real signed and unsigned commits on gitlab.com:
```python
>>> import gitlab
>>> gl = gitlab.Gitlab("https://gitlab.com")
>>> project = gl.projects.get("gitlab-org/gitlab")
>>> signed_commit = project.commits.get("387572e7aa7768e2be539215e453d474d067e20d")
>>> signed_commit.signature()
{'gpg_key_id': None, 'gpg_key_primary_keyid': 'B89F5B74C808CB29', 'gpg_key_user_name': 'Daniel Paul Searles', 'gpg_key_user_email': 'dsearles@gitlab.com', …
```
> feat: add support for commit GPG signature

- .travis.yml
- README.rst
- tools/build_test_env.sh
- tox.ini
In #1052 and in some previous PRs, we've had to wait for a release to test new features on `latest`.
This PR allows contributors and CI (via either command-line flags or env variables) to define the image and tag to test against, and removes references to older python test environments.
Since `nightly` might be unstable I've added it to `allow_failures` so it's not blocking but at least provides some feedback on new features. This can later be combined with `@skipif` (or similar) to run tests only against versions equal or higher than a specific GitLab version to improve development for upcoming features.
> chore: improve test environment for upcoming features

- gitlab/v4/objects.py
This commit adds the v4 Create project attributes necessary to create a
project from a project, instance, or group level template as documented
in https://docs.gitlab.com/ee/api/projects.html#create-project
> feat: add create from template args to ProjectManager

- gitlab/tests/test_types.py
- gitlab/types.py
- tools/python_test_v4.py
Closes #1057.
See test https://travis-ci.org/github/python-gitlab/python-gitlab/jobs/668135438#L248-L250 for previous behavior.
> Fix: ListAttribute get_for_api() splits strings

- docs/cli.rst
- docs/gl_objects/deploy_tokens.rst
- gitlab/__init__.py
- gitlab/tests/test_gitlab.py
- gitlab/v4/objects.py
- tools/cli_test_v4.sh
- tools/python_test_v4.py
There is a conflict between the required parameters of `POST /projects/:id/deploy_tokens` (and `POST /groups/:id/deploy_tokens`) as documented here : `https://docs.gitlab.com/ce/api/deploy_tokens.html#create-a-project-deploy-token` and required parameters that the API waits for: `gitlab.com` that is uses 12.9.0-pre 4b94245907d (As I write these lines) and the docker image `gitlab/gitlab-ce:nightly` require four parameters: `name`, `expires_at`, `username` and `scopes`.
Creating a deploy token from `gitlab.com` UI agrees with the Deploy Token API documentation: only the `name` and the `scopes` are required.
The managers I added require the four parameters to make tests pass with `gitlab/gitlab-ce:nightly`.
the documentation on the other hand reflects the provided Deploy Token API …
> feat(api): add support for Gitlab Deploy Token API

- gitlab/base.py
This change adds the `__dir__` magic method to the `RESTObject` class in order to expose and allow introspection on the attributes that the object might have.
This is very useful to me when exploring the API in an interactive console. 
Normally I'll call `dir(obj)` (or `obj?` in iPython shell) to try to discover what methods and attributes exist for the object. However, the attributes in the `.attributes` property are not currently exposed, requiring the extra step of checking `.attributes` on each object I explore this way.
Hope this makes sense and that this change, if accepted, will help others.
> feat(types): add __dir__ to RESTObject to expose attributes

- docs/cli.rst
- gitlab/config.py
- gitlab/tests/test_config.py
It can be useful (especially in scripts) to specify a configuration
location via an environment variable. If the "PYTHON_GITLAB_CFG"
environment variable is defined, treat its value as the path to a
configuration file and include it in the set of default configuration
locations.
> feat: Allow an environment variable to specify config location

- docs/gl_objects/groups.rst
- gitlab/v4/objects.py
Similar to the `UserManager` and `ProjectManager` the `GroupManager` now supports uploading avatar images. The `GroupManager` object was missing the `ImageAttribute` type.
The feature to upload avatars to groups was introduced in Gitlab 12.9.
See also https://docs.gitlab.com/ce/api/groups.html#new-group (Attribute "avatar")
> feat(api): added support in the GroupManager to upload Group avatars

- docs/cli.rst
- docs/gl_objects/commits.rst
- gitlab/v4/objects.py
- tools/cli_test_v4.sh
- tools/python_test_v4.py
The commit signature test was failing against nightly after some changes to commit signatures (https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27327). This fixes the test and some minor docs, since with 12.10 released we'll be getting failed builds without this (it was just a silly assert for the 404 :D).
I only left the unit test as is since the GPG response is one of the possible options.
> chore: bring commit signatures up to date with 12.10

- .travis.yml
- README.rst
We discussed adding some kind of coverage reporting, codecov seemed to be the easiest to add. After this is merged, codecov should also start reporting PR comments with a summary (on successful builds):
https://docs.codecov.io/docs/pull-request-comments
Edit: ah the summary is already here :) If this comment style is too intrusive, we can probably customize this to make it smaller with `codecov.yml`. Looks like there was an initial run a few years ago, since this reports against an old master commit. I'll look into adding this as a separate check as well. Seems like we can later split unit and functional tests into separate checks with flags.
> chore(ci): add codecov integration to Travis

- gitlab/v4/objects.py
Refer to #1120 
Merge request requests aren't working, as the request parameters `should_remove_source_branch` and `remove_source_branch` are parsed as `post_data`, when they should be send as query_string, as described in the official GitLab API documentation itself [GitLab API Accept Merge](https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr)
> fix(merge): parse arguments as query_data

- gitlab/const.py
This constant is useful for cases where no access is granted, e.g. when creating a protected branch.
The `NO_ACCESS` const corresponds to the definition in https://docs.gitlab.com/ee/api/protected_branches.html
> Added NO_ACCESS const

- docs/gl_objects/projects.rst
Showing how to delete without having to pull the file.
> docs: additional project file delete example

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/tests/objects/test_commits.py
- gitlab/tests/objects/test_job_artifacts.py
- gitlab/tests/objects/test_runners.py
- gitlab/v4/objects.py
- tools/python_test_v4.py
This adds support for an endpoint that was missing (artifacts from the latest pipeline per branch/tag):
https://docs.gitlab.com/ee/api/job_artifacts.html#download-the-artifacts-archive
The unrelated changes are there to keep black happy :) looks like there was a new release with different behavior
> Feat: Project job artifacts for latest successful pipeline

- .commitlintrc.json
- .pre-commit-config.yaml
- .travis.yml
- README.rst
Closes #1128. I was having this issue too sometimes when switching workstations and forgot to format :P
I went with `commitlint` to be consistent with CI but maybe `commitizen` makes sense in the future to keep dev dependencies Python-only.
> chore(env): add pre-commit and commit-msg hooks

- .renovaterc.json
- tools/build_test_env.sh
Closes #1148.
This would need the renovate app configured for this repo (https://github.com/apps/renovate).
I left a slightly older version to see if renovate updates properly, although I tested this on my fork: https://github.com/nejch/python-gitlab/commit/d9b7393cd50e2de58f6ed0ff053f548d8120d199
> chore(ci): pin gitlab-ce version for renovate

- .renovaterc.json
This should get some more sane defaults from the base config for PR frequency, and automerge for gitlab updates should make it more manageable (if status checks are green, so only need to care about failed upgrades).
> chore(ci): reduce renovate PR noise

- docs/gl_objects/users.rst
- gitlab/tests/objects/test_users.py
- gitlab/v4/objects/__init__.py
- tools/functional/api/test_users.py
Closes #1070.
This one is weird because the endpoint is kind of special (only supports delete, plus the creation of identities is inconsistent with this endpoint).
https://docs.gitlab.com/ee/api/users.html#delete-authentication-identity-from-user
I couldn't do `user.identities` for the manager because that's the attribute returned in the nested JSON. Maybe this could be done by having a `__repr__()` that returns that list from the attribute of the parent manager? But it felt like I would just be adding to the inconsistency, not sure. I didn't find any other examples that solved it for nested json.
I opted for `user.identityproviders.delete()` since its explicit and the provider is a required param. I also considered `user.identity.delete()`, `user.delete_identity()` (custom method) and …
> feat(api): add support for user identity provider deletion

- gitlab/v4/objects/__init__.py
> fix(api): add missing runner access_level param

- gitlab/v4/objects/__init__.py
Adds all the missing latest list filters (including last_activity_after) for projects, sorted following the table in https://docs.gitlab.com/ee/api/projects.html#list-all-projects
@max-wittig could we have a small version bump for this one so it's available on pypi? :)
> fix(cli): add missing args for project lists

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/tests/objects/test_bridges.py
- gitlab/v4/objects/__init__.py
Hi,
If you use child pipelines, in your project, i.e.:
```
security_scans:
stage: security_scanning
only:
- master
trigger:
include:
- local: ".gitlab-ci/security.yml"
```
, 
then API call `pipeline.jobs.list()` doesn't include child pipelines into output. 
There is a different API call for this: https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-bridges
With this PR you'll be able to exeute:
```bridges = pipeline.bridges.list()```
> Added support for pipeline bridges

- docs/api/gitlab.rst
- docs/cli-objects.rst
- docs/cli-usage.rst
- docs/conf.py
- docs/index.rst
- gitlab/cli.py
- rtd-requirements.txt
- test-requirements.txt
- tox.ini
This adds a generated page similar to the API reference, including all the possible commands. It's a _long_ list, but better than nothing. 😁 I wasn't able to group them into sections due to the way they are currently dynamically generated, but maybe there's a way.
I've noticed a lot of people still use the CLI even though it has some issues. I'm hoping this can help people/prevent opening issues that are simply due to missing docs (recent example: https://github.com/python-gitlab/python-gitlab/issues/1197), or at least we can more quickly close those by providing the link rather than providing examples every time.
Also means no more manual examples for the CLI are needed, hopefully.
Click also has a [drop-in replacement](https://sphinx-click.readthedocs.io) for the sphinx extension used …
> docs(cli): add auto-generated CLI reference

- gitlab/v4/objects/__init__.py
- tools/functional/api/test_projects.py
The ProjectLabelManager was missing the GetMixin, which made it impossible to get labels by name or ID, even though this is supported by the GitLab API.
> fix(api): add missing GetMixin to ProjectLabelManager

- gitlab/const.py
A "minimal access" access level was [introduced](https://gitlab.com/gitlab-org/gitlab/-/issues/220203) in GitLab 13.5.
It's currently undocumented. Its addition to GitLab's docs was approved in [this PR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49526).
> feat: Add MINIMAL_ACCESS constant

- docs/gl_objects/groups.rst
Follows the [GitLab API example](https://docs.gitlab.com/ee/api/groups.html#new-subgroup)
> docs(groups): add example for creating subgroups

- docs/cli-usage.rst
The links to "the official documentation" on tokens are currently broken in the [project documentation](https://python-gitlab.readthedocs.io/en/stable/cli.html).
There doesn't seem to be an obvious way to use an alias for identical text labels that link to different targets. With inline links we can work around this shortcoming. Until we know better.
> Use inline anonymous references for external links

- docs/api-usage.rst
- docs/cli-usage.rst
- gitlab/__init__.py
- gitlab/__version__.py
- gitlab/config.py
- gitlab/const.py
- gitlab/tests/test_config.py
- gitlab/tests/test_gitlab.py
- setup.py
I was thinking that some tools/libraries using python-gitlab (or people triggering the CLI in pipelines) might want to define their own user agent.
> feat(api,cli): make user agent configurable

- gitlab/tests/objects/test_projects.py
- gitlab/v4/objects/__init__.py
I'd like to use this libary to automate importing Bitbucket Server
repositories into GitLab.  There is a [GitLab API
endpoint](https://docs.gitlab.com/ee/api/import.html#import-repository-from-bitbucket-server)
to do this, but it is not exposed through this library.
* Add an `import_bitbucket_server` method to the `ProjectManager`.  This
method calls this GitLab API endpoint:
https://docs.gitlab.com/ee/api/import.html#import-repository-from-bitbucket-server
* Add a basic unit test for the existing `import_github` method
> feat: import from bitbucket server

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Let's save the earth a little CO2 by not triggering 22 jobs every time we push to PR's from this repo :grin: PR checks are safer anyway as they do a pre-merge checkout.
More context here https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
> chore(ci): deduplicate PR jobs

- gitlab/__init__.py
httplib is a Python 2 library. It was renamed to http.client in Python
3.
https://docs.python.org/2.7/library/httplib.html
> Remove Python 2 code

- gitlab/v4/objects/merge_requests.py
Gitlab allows setting the defaults for MR to delete the source. Also
the inline help of the CLI suggest that a boolean is expected, but no
matter what value you set, it will always delete.
To mimic the existing behavior as good as possible, we check for not false
instead of true. This way the impact on the cli will be minimal.
> fix: honor parameter value passed

- gitlab/__init__.py
The variable ALLOWED_KEYSET_ENDPOINTS was added in commit
f86ef3bbdb5bffa1348a802e62b281d3f31d33ad.
Then most of that commit was removed in commit
e71fe16b47835aa4db2834e98c7ffc6bdec36723, but ALLOWED_KEYSET_ENDPOINTS
was missed.
> chore: remove unused ALLOWED_KEYSET_ENDPOINTS variable

- gitlab/tests/objects/test_audit_events.py
- gitlab/v4/objects/audit_events.py
- gitlab/v4/objects/projects.py
Similar to #949 but specific to [project audit events](https://docs.gitlab.com/ee/api/audit_events.html#project-audit-events).
No previous issues for this exist.
The code was tested to verify it works.
> feat: add project audit endpoint

- tools/functional/cli/test_cli_v4.py
Since there are two groups we can't depend on the one we changed to
always be the first one returned.
Instead fetch the group we want and then test our assertion against
that group.
> fix: test_update_group() dependency on ordering

- docs/api-objects.rst
- docs/gl_objects/projects.rst
- docs/gl_objects/releases.rst
- gitlab/tests/conftest.py
- gitlab/tests/objects/test_releases.py
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/releases.py
- gitlab/v4/objects/tags.py
- tools/functional/api/test_projects.py
- tools/functional/api/test_releases.py
- tools/functional/conftest.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1297
This splits a few things out:
- releases from `tags.py` into own module and adds release links
- releases from `projects.rst` into own module in the docs as well
- release functional tests from projects into own module, and adds a link test
Also made Project refreshable for convenience in functional tests but kept in a separate commit just in case (see #1313)
> feat: add release links API support

- gitlab/client.py
In gitlab/client.py remove usage of:
* from gitlab.const import *
* from gitlab.exceptions import *
Change them to:
* import gitlab.const
* import gitlab.exceptions
Update code to explicitly reference things in gitlab.const and
gitlab.exceptions
A flake8 run no longer lists any undefined variables. Before it listed
possible undefined variables.
> chore: remove usage of 'from ... import *' in client.py

- gitlab/client.py
The function _construct_url() was used by the v3 API. All usage of the
function was removed in commit
fe89b949922c028830dd49095432ba627d330186
> chore: remove unused function _construct_url()

- tox.ini
Previously running the pep8 target would fail as flake8 was not
installed.
Now install flake8 for the pep8 target.
NOTE: Running the pep8 target fails as there are many warnings/errors.
But it does allow us to run it and possibly work on reducing these
warnings/errors in the future.
In addition, add two checks to the ignore list as black takes care of
formatting. The two checks added to the ignore list are:
* E501: line too long
* W503: line break before binary operator
> fix: tox pep8 target, so that it can run

- docs/gl_objects/project_access_tokens.rst
- gitlab/tests/objects/test_project_access_tokens.py
- gitlab/v4/objects/project_access_tokens.py
- gitlab/v4/objects/projects.py
Fun Trivia: The **create** endpoint is totally useless btw. as it doesn't return the token and there is no way to get it
https://gitlab.com/gitlab-org/gitlab/-/issues/238991#note_516433443
> feat(projects): add project access token api

- gitlab/v4/objects/users.py
The classes UserStatus and UserStatusManager were each declared twice.
Remove the duplicate declarations.
> fix: remove duplicate class definitions in v4/objects/users.py

- gitlab/base.py
Determined the base class for obj_cls and adding type-hints for it.
> Improve type-hints for gitlab/base.py

- gitlab/__init__.py
Initially when extracting out the gitlab/client.py code we tried to
remove this but functional tests failed.
Later we fixed the functional test that was failing, so now remove the
unneeded import.
> chore: remove import of gitlab.utils from __init__.py

- README.rst
Add a section in the README.rst about the gitter community. The badge
already exists and is useful but very easy to miss.
> doc: add information about the gitter community

- gitlab/base.py
Add type-hints for the variables which are set via self.__dict__
mypy doesn't see them when they are assigned via self.__dict__. So
declare them in the class definition.
> chore: add additional type-hints for gitlab/base.py

- gitlab/v4/objects/projects.py
- gitlab/v4/objects/repositories.py
Prep work for #1306 because `projects.py` is getting bloated again already (I'm splitting this into two PRs just for clarity).
I noticed all the `/repository/` endpoints were just kind of slapped into the project manager as custom methods. For now this just splits the methods into a separate Mixin, but perhaps later namespacing them with a separate manager would make it cleaner:
```python
project.repository.tree()
project.repository.blob()
project.repository.compare()
project.repository.contributors()
```
The old methods could then just call the manager, and maybe raise a deprecation warning.
WDYT @max-wittig would that make sense? I'd open a follow-up later for the repository manager.
> chore(api): move repository endpoints into separate module

- .mypy.ini
- gitlab/base.py
- gitlab/cli.py
- gitlab/client.py
- gitlab/utils.py
Don't allow a partially annotated function definition. Either none of
the function is annotated or all of it must be.
Update code to ensure no-more partially annotated functions.
Update gitlab/cli.py with better type-hints. Changed Tuple[Any, ...]
to Tuple[str, ...]
> chore: disallow incomplete type defs

- gitlab/v4/objects/project_access_tokens.py
Remove usage of 'import *' in
gitlab/v4/objects/project_access_tokens.py.
> chore: del 'import *' in gitlab/v4/objects/project_access_tokens.py

- gitlab/client.py
To be safe that we don't assert while running, put the assert
statements, which are used by mypy to check that types are correct,
inside an 'if TYPE_CHECKING:' block.
Also, instead of asserting that the item is a dict, instead assert
that it is not a requests.Response object. Theoretically the JSON
could return as a list or dict, though at this time we are assuming a
dict.
> chore: Put assert statements inside 'if TYPE_CHECKING:'

- gitlab/base.py
Add some additional type hints to gitlab/base.py
> chore: add type hints to gitlab/base.py:RESTManager

- gitlab/tests/test_utils.py
- gitlab/utils.py
Git refnames are relatively free-form and can contain all sort for
special characters, not just `/` and `#`, see
http://git-scm.com/docs/git-check-ref-format
In particular, Debian's DEP-14 standard for storing packaging in git
repositories mandates the use of the `%` character in tags in some
cases like `debian/2%2.6-21`.
Unfortunately python-gitlab currently only escapes `/` to `%2F` and in
some cases `#` to `%23`. This means that when using the commit API to
retrieve information about the `debian/2%2.6-21` tag only the slash is
escaped before being inserted in the URL path and the `%` is left
untouched, resulting in something like
`/api/v4/projects/123/repository/commits/debian%2F2%2.6-21`. When
urllib3 seees that it detects the invalid `%` escape and then urlencodes
the whole string, …
> fix: handle tags like debian/2%2.6-21 as identifiers

- gitlab/base.py
- gitlab/mixins.py
- gitlab/v4/cli.py
We now create _types = {} in RESTManager class.
By making _types always present in RESTManager it makes the code
simpler. We no longer have to do:
types = getattr(self, "_types", {})
And the type checker now understands the type.
> chore: make _types always present in RESTManager

- gitlab/base.py
- gitlab/v4/cli.py
Prior to commit 3727cbd21fc40b312573ca8da56e0f6cf9577d08
RESTManager._from_parent_attrs did not exist unless it was explicitly
set. But commit 3727cbd21fc40b312573ca8da56e0f6cf9577d08 set it to a
default value of {}.
So the checks using hasattr() were no longer valid.
Update the checks to check if RESTManager._from_parent_attrs has a
value.
> fix: checking if RESTManager._from_parent_attrs is set

- gitlab/base.py
- gitlab/mixins.py
- gitlab/tests/mixins/test_mixin_methods.py
- gitlab/v4/cli.py
Add the attributes: _create_attrs and _update_attrs to the RESTManager
class. This is so that we stop using getattr() if we don't need to.
This also helps with type-hints being available for these attributes.
> chore: add _create_attrs & _update_attrs to RESTManager

- gitlab/tests/objects/test_audit_events.py
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/audit_events.py
- gitlab/v4/objects/events.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/projects.py
This adds group audit events, moves all audit events into one module and makes the class naming consistent.
Closes https://github.com/python-gitlab/python-gitlab/issues/1107, closes https://github.com/python-gitlab/python-gitlab/issues/948.
> Feat: cover all audit events

- gitlab/mixins.py
- gitlab/tests/objects/test_project_merge_request_approvals.py
```
Remove usage of getattr(self, "_update_uses_post", False)
Instead add it to class and set default value to False.
Add a test that shows it is set to True for the
ProjectMergeRequestApprovalManager class.
```
> chore: remove usage of getattr()

- docs/cli-usage.rst
- gitlab/config.py
- gitlab/tests/test_config.py
I have stored my personal access token with all other secrets in UNIX password store.  
For not having the token stored on the disk, I have implemented the option to let tokens be
looked up from a helper program.
Example:
```ini
[my_config]
url = https://gitlab.server
private_token = helper: ~/bin/pass-helper.sh
api_version = 4
```
whith a helper script ``~/bin/pass-helper.sh``:
```bash
#!/bin/bash
pass show path/to/token | head -n 1
```
> feat(config): option to configure a helper to lookup the token

- gitlab/v4/objects/merge_requests.py
While adding type-hints mypy flagged this as an issue. The third
argument to register_custom_action is supposed to be a tuple. It was
being passed as a string rather than a tuple of strings.
> fix: argument type was not a tuple as expected

- gitlab/mixins.py
Commit baea7215bbbe07c06b2ca0f97a1d3d482668d887 introduced type-hints
for gitlab/mixins.py.
After starting to add type-hints to gitlab/v4/objects/users.py
discovered a few errors.
Main error was using '=' instead of ':'. For example:
_parent = Optional[...] should be _parent: Optional[...]
Resolved those issues.
> fix: correct some type-hints in gitlab/mixins.py

- gitlab/tests/test_utils.py
- gitlab/utils.py
The function sanitize_parameters() was used when the v3 API was in
use. Since v3 API support has been removed there are no more users of
this function.
> chore: remove unused function sanitize_parameters()

- gitlab/base.py
- gitlab/tests/test_base.py
Fixes a small issue with the feature added in #1072 for `__dir__` to display rest object attributes.
In at least one case, classes have overlapping attributes with the attributes listed in `.attributes`. For example, the `Group` object has its own `projects` property for the `GroupProjectManager`. This shadows the name that would normally access `.attributes['projects']`. This causes `dir(some_group)`, as currently implemented, to list `projects` twice.
While this is unlikely to be problematic, it's ideal if duplicate attributes do not appear in the response for `__dir__`. This PR ensures that duplicates are not produced by the `__dir__` method.
Instead of _adding_ the list of attributes, we use the `|` operator to produce a set with the union of all the elements, ensuring there are no …
> fix(types): prevent __dir__ in RestObject from producing duplicates

- gitlab/client.py
Hi !
If we want to update email, avatar and do not send email confirmation change (`skip_reconfirmation` = True), `MultipartEncoder` will try to encode everything except None and bytes. So it tries to encode bools. 
Casting bool's values to their stringified int representation fix it.
Exemple to reproduce it:
```
user.skip_reconfirmation = True
user.email = user_data['email']
user.avatar = b'\xff\xd8\xff\xdb\x00C\x00\x06\x04\x0...'
user.save()
```
> fix: update user's bool data and avatar

- gitlab/v4/objects/files.py
ProjectFile.decode() returns 'bytes' and not 'str'.
Update the method's doc-string and add a type-hint.
ProjectFile.decode() returns the result of a call to
base64.b64decode()
The docs for that function state it returns 'bytes':
https://docs.python.org/3/library/base64.html#base64.b64decode
Fixes: #1403
> fix: correct ProjectFile.decode() documentation

- gitlab/client.py
Two related commits that fixed #1386 for me. Only the first commit is strictly necessary. The second is a "technically correct" fix so that `http_request` does not send extra query parameters.
> Improvements to HTTP requests

- gitlab/v4/objects/audit_events.py
When I added this in #1363 I missed that it always gets instantiated and everyone will be getting the warning. It's mostly an internal thing anyway and can be removed in 3.0.0.
Needed for 2.7.0 https://github.com/python-gitlab/python-gitlab/pull/1408 so people don't get spammed :grin:
> chore(objects): remove noisy deprecation warning for audit events

- gitlab/base.py
- gitlab/v4/cli.py
Always create RESTObject._short_print_attrs with a default value of
None.
This way we don't need to use hasattr() and we will know the type of
the attribute.
> chore: make RESTObject._short_print_attrs always present

- gitlab/mixins.py
- gitlab/v4/cli.py
Always create ListMixin._list_filters attribute with a default value
of tuple().
This way we don't need to use hasattr() and we will know the type of
the attribute.
> chore: make ListMixin._list_filters always present

- gitlab/__version__.py
- gitlab/tests/objects/test_repositories.py
- gitlab/v4/objects/files.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1416.
This is a quick fix for 2.7.0 but we should clean up with https://github.com/python-gitlab/python-gitlab/issues/1356 eventually :)
> fix(files): do not url-encode filepaths twice

- gitlab/mixins.py
- gitlab/v4/cli.py
Always create GetMixin/GetWithoutIdMixin._optional_get_attrs attribute
with a default value of tuple()
This way we don't need to use hasattr() and we will know the type of
the attribute.
> chore: make Get.*Mixin._optional_get_attrs always present

- gitlab/tests/test_types.py
- gitlab/types.py
Previously ListAttribute only support lists of integers. Now be more
flexible and support lists of items which can be coerced into strings,
for example integers.
This will help us fix issue #1407 by using ListAttribute for the
'iids' field.
> feat: add support for lists of integers to ListAttribute

- gitlab/tests/objects/test_mro.py
- gitlab/v4/objects/commits.py
- gitlab/v4/objects/deployments.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/releases.py
~~This should be merged after:
https://github.com/python-gitlab/python-gitlab/pull/1344~~  DONE
Add a check to ensure the MRO (Method Resolution Order) is correct for classes in
gitlab.v4.objects.
```
An example of an incorrect definition:
class ProjectPipeline(RESTObject, RefreshMixin, ObjectDeleteMixin):
^^^^^^^^^^ This should be at the end.
Correct way would be:
class ProjectPipeline(RefreshMixin, ObjectDeleteMixin, RESTObject):
Correctly at the end ^^^^^^^^^^
```
Also fix classes which have the issue.
> fix: add a check to ensure the MRO is correct

- gitlab/v4/objects/issues.py
- tools/functional/api/test_issues.py
Set the 'iids' values as type ListAttribute so it will pass the list
as a comma-separated string, instead of a list.
Closes: #1407
> fix: iids not working as a list in projects.issues.list()

- setup.py
By adding the file: py.typed
it indicates that python-gitlab is a typed package and contains
type-hints.
https://www.python.org/dev/peps/pep-0561/
> feat: indicate that we are a typed package

- docs/conf.py
- docs/ext/docstrings.py
- setup.py
- tools/functional/api/test_issues.py
- tools/functional/api/test_merge_requests.py
- tools/functional/api/test_projects.py
- tools/functional/api/test_releases.py
- tools/functional/api/test_repository.py
- tools/functional/api/test_users.py
- tools/functional/conftest.py
- tools/functional/ee-test.py
- tox.ini
Have flake8 run at the top-level of the projects instead of just the
gitlab directory.
> chore: have flake8 check the entire project

- tox.ini
This will ensure everything is formatted with black, including
setup.py.
> chore: have black run at the top-level

- gitlab/v4/objects/branches.py
Add `ProjectProtectedBranchManager.code_owner_approval_required` to mimick [GitLab API documentation](https://docs.gitlab.com/ce/api/protected_branches.html#protect-repository-branches):
Attribute | Type | Required | Description
-- | -- | -- | --
code_owner_approval_required | boolean | no | Prevent pushes to this branch if it matches an item in the CODEOWNERS file. (defaults: false)
Fixes #1436
> feat: add code owner approval as attribute

- ChangeLog.rst
- docs/api-objects.rst
- docs/cli-usage.rst
- docs/gl_objects/deploy_tokens.rst
- docs/gl_objects/milestones.rst
- docs/gl_objects/mr_approvals.rst
- docs/gl_objects/packages.rst
- docs/gl_objects/remote_mirrors.rst
- docs/gl_objects/runners.rst
- setup.cfg
I was hesitant to make it this strict first, but realized this is useful when docs aren't included in the toctree and the articles don't show up on RTD, unless users specifically search for those keywords. So we actually had some dead documentation this whole time.
Closes https://github.com/python-gitlab/python-gitlab/issues/1370.
> docs: fail on warnings during sphinx build

- docs/conf.py
This partially reverts https://github.com/python-gitlab/python-gitlab/commit/b498ebd804461031e2d2d391f77dfbbcf0d2e281. I noticed the builds are failing on RTD right now and it started with this commit.
Turns out RTD does not have `gitlab` in path because it does its own weird build, so we really need this hack. Here's requests doing the same: https://github.com/psf/requests/blob/c45a4dfe6bfc6017d4ea7e9f051d6cc30972b310/docs/conf.py#L23-L27
There might be cleaner solutions but if `psf` repos do it, I guess this is ok :rofl:
> chore(docs): fix import order for readthedocs build

- .mypy.ini
- gitlab/__main__.py
- gitlab/base.py
- gitlab/cli.py
- gitlab/config.py
- gitlab/exceptions.py
- gitlab/tests/test_cli.py
- gitlab/types.py
Be more strict and don't allow untyped definitions on the files we
check.
Also this adds type-hints for two of the decorators so that now
functions/methods decorated by them will have their types be revealed
correctly.
> chore: mypy: Disallow untyped definitions

- gitlab/tests/objects/test_jobs.py
- gitlab/tests/objects/test_pipelines.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/pipelines.py
Closes https://github.com/python-gitlab/python-gitlab/issues/825. It seems like it's something people want and saves a few extra API calls in some cases.
> fix(objects): return server data in cancel/retry methods

- gitlab/v4/objects/deploy_tokens.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/runners.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/users.py
- tools/functional/api/test_groups.py
Well, this was tedious :grin: Follow-up to https://github.com/python-gitlab/python-gitlab/pull/1413.
Long term I don't see this being a good idea to maintain manually. Maybe later we can just convert any list we get in the data for `ListMixin`. Either way - finding candidates was  `grep -r 'type: Array' lib/api` in the gitlab repo, and weeding out non-`GET` params and endpoints not implemented by python-gitlab:
```bash
lib/api/resource_access_tokens.rb:          requires :scopes, type: Array[String], desc: "The permissions of the token"
lib/api/deploy_tokens.rb:        requires :scopes, type: Array[String], coerce_with: ::API::Validations::Types::CommaSeparatedToArray.coerce, values: ::DeployToken::AVAILABLE_SCOPES.map(&:to_s),
lib/api/deploy_tokens.rb:        requires :scopes, type: …
```
> fix(objects): make lists work for filters in all objects

- .github/workflows/release.yml
- .gitlab-ci.yml
- README.rst
- pyproject.toml
Adds an automated release ~~every week~~ once a month + manual workflow if quick fixes are needed. I thought this would be a good compromise. I didn't want this on every push as otherwise all release notes just have only 1 PR entry and it's just really noisy. I see other people are also reconsidering that: https://github.com/renovatebot/renovate/issues/9709.
Also I just chose Monday so there's no Friday releases :rofl: but open to suggestions.
I tested this here (including all my derpy trial&error pushes):
https://github.com/nejch/python-gitlab-semantic-release
Resulting releases: https://github.com/nejch/python-gitlab-semantic-release/releases
testpypi package: https://test.pypi.org/project/python-gitlab/
changelog: https://github.com/nejch/python-gitlab-semantic-release/blob/master/CHANG …
> chore(ci): automate releases

- docs/gl_objects/groups.rst
- docs/gl_objects/projects.rst
- gitlab/mixins.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/projects.py
- tools/functional/api/test_groups.py
Hi!
First of all excuse me for inconvenience.  I failed my previous PR(https://github.com/python-gitlab/python-gitlab/pull/1187) branch during rebasing, so PR automatically were closed.
Briefly, PR about the same, feature #1133, and taking into account @nejch 's suggestion from (https://github.com/python-gitlab/python-gitlab/pull/1187)
Here I propose to introduce new custom managers ProjectMemberAllManager (/projects/:id/members/all/:user_id) and GroupMemberAllManager (/groups/:id/members/all/:user_id). Subsequently, in order to fetch a list or instance of members including inherited ones, you will need to:
```
project = gl.projects.get(project_id)
project.members_all.list()
project.members_all.get(member_id)
group = gl.groups.get(group_id)
group.members_all.list() …
```
> feat: add feature to get inherited member for project/group

- gitlab/cli.py
- gitlab/tests/test_cli.py
- gitlab/v4/cli.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1289. Not sure if relying on requests' internal `CaseInsensitiveDict` for this is the best idea here but I didn't want to reinvent the wheel. But it's needed since proper camelcase -> kebab-case conversions are not fully reversible (see https://stackoverflow.com/a/1176023)
Fixes the issue for:
CurrentUserGPGKey
LDAPGroup
UserGPGKey
> fix(cli): fix parsing CLI objects to classnames 

- gitlab/v4/objects/merge_requests.py
- tools/functional/api/test_merge_requests.py
- tools/functional/conftest.py
MR https://github.com/python-gitlab/python-gitlab/pull/1121 changed
mr.merge() to use 'query_data'. This appears to have been wrong.
From the Gitlab docs they state it should be sent in a payload body
https://docs.gitlab.com/ee/api/README.html#request-payload since
mr.merge() is a PUT request.
```
Request Payload
API Requests can use parameters sent as query strings or as a
payload body. GET requests usually send a query string, while PUT
or POST requests usually send the payload body
```
> Switch mr.merge() to use post_data (was using query_data)

- .gitignore
By explicitly NOT excluding the dotfiles we care about to the
.gitignore file we make those files searchable by tools like ripgrep.
By default dotfiles are ignored by ripgrep and other search tools (not
grep)
> chore: make certain dotfiles searchable by ripgrep

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_pipelines.py
Gitlab (since v13.0) now supports [test reports](https://docs.gitlab.com/ee/ci/unit_test_reports.html#unit-test-reports). Here is [the api description](https://docs.gitlab.com/ee/api/pipelines.html#get-a-pipelines-test-report).
> feat: add pipeline test report support

- docs/gl_objects/groups.rst
- gitlab/v4/objects/groups.py
- tests/functional/api/test_groups.py
- tests/unit/objects/test_groups.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1479.
I'm struggling to understand why gitlab didn't just add a `recursive` param to subgroups instead of a whole new endpoint, but maybe I'm missing something ¯\\\_(ツ)\_/¯ :grin:
> feat(objects): add support for descendant groups API

- .gitignore
- docs/gl_objects/deployments.rst
- gitlab/v4/objects/deployments.py
- gitlab/v4/objects/merge_requests.py
- tests/unit/objects/test_merge_requests.py
Hi,
I added the https://docs.gitlab.com/ee/api/deployments.html#list-of-merge-requests-associated-with-a-deployment API to `objects.py`.
Fixes #995 
Cheers
Ludwig
> Add deployment merge request api

- docs/cli-usage.rst
- docs/gl_objects/packages.rst
- gitlab/client.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/projects.py
- tests/functional/api/test_packages.py
- tests/functional/cli/test_cli_packages.py
- tests/unit/objects/test_packages.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1389.
I had to add a `raw` param to put/post like we have for get, instead of using `files` with the multipart encoder, to really ensure only the raw data ended up as the uploaded package :thinking:
Maybe it's just how `files` are handled currently and can still be refactored to take out redundant stuff if we want a raw upload. In the meantime I also cleaned out some code from `http_request` into a helper method and centralized the content_types there (`http_request` would be getting quite long and messy otherwise).
> feat(objects): add support for generic packages API

- gitlab/v4/objects/merge_request_approvals.py
Add missing optional create parameter ('protected_branch_ids') to the
project approvalrules.
https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule
> chore: add missing optional create parameter for approval_rules

- README.rst
- gitlab/client.py
- gitlab/mixins.py
- tests/functional/api/test_issues.py
- tests/functional/cli/test_cli_artifacts.py
- tests/functional/conftest.py
- tests/functional/fixtures/set_token.rb
While developing tests, waiting for a new GitLab container to spin up every run became a little frustrating, especially given I only wanted to run one file within the suite.
Added an optional flag which may be passed to pytest to keep the containers around after a test run.
> Optionally keep containers after running integration tests

- tests/functional/api/test_projects.py
- tests/functional/fixtures/.env
- tests/functional/fixtures/docker-compose.yml
```
The PR: https://github.com/python-gitlab/python-gitlab/pull/1462 was
not able to merge due to a change in the latest version of Gitlab.
More details here:
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61646
Update the functional test to first create the project service before
doing a get.
```
Also bring in the two commits from https://github.com/python-gitlab/python-gitlab/pull/1462
> fix: functional project service test

- .github/workflows/release.yml
Since we have a protected master branch the stock action doesn't work with the default auto-generated `GITHUB_TOKEN`. The workaround is described here:
https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html?highlight=administrator
This fixes what we discussed earlier this morning @max-wittig.
For now I've added my token as `RELEASE_GITHUB_TOKEN` but we should discuss creating something like a `python-gitlab-bot` user for the releases maybe?
> chore(ci): use PAT for release workflow

- gitlab/base.py
- tests/unit/test_base.py
```
Sometimes we have errors where we don't get a dictionary passed to
RESTObject.__init__() method. This breaks things but in confusing
ways.
Check in the __init__() method and raise an exception if it occurs.
```
> fix: catch invalid type used to initialize RESTObject

- requirements-lint.txt
New version of mypy flagged errors for missing types. Install the
recommended type-* packages that resolve the issues.
PR https://github.com/python-gitlab/python-gitlab/pull/1504 will fail until this is merged.
> chore: add new required type packages for mypy

- docs/gl_objects/mrs.rst
- gitlab/cli.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_merge_request_pipelines.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1312.
Closes https://github.com/python-gitlab/python-gitlab/issues/1239.
~~todo: technically this breaks the CLI `gitlab project-merge-request pipelines` and requires `project-merge-request-pipelines list` instead. I'll see if I can hack the `register_custom_action` decorator to accept custom action names, not just the current method name.~~ I had to remove it as there would be a namespace clash between the old method and the new manager.
Well, I've managed to hack `register_custom_action` a little so it takes an optional `custom_action` argument to override the current function name as the CLI action, so should be backwards compatible, but then realized the old method probably never worked in CLI due to missing CLI args …
> feat(api): add merge request pipeline manager and deprecate mr.pipelines() method

- gitlab/v4/objects/merge_requests.py
This is a first attempt at allowing users to create MRs with reviewers or edit an existing MR with the `reviewer_ids` parameter.
This is kind of unique in the sense that `reviewer_ids` doesn't appear in the rest response, but it is an accepted parameter.
A manager might be a better way to implement this, but I'm not sure it's appropriate since reviewers doesn't have its own API path, so reviewers are not really a rest object in their own right. The only example of a manager being used as a helper is the sidekiq manager.
API:
```python
mr.reviewer_ids = [1,2,3]
mr.save()
```
The property can be omitted and the same code as above works, however `mr.reviewer_ids` would be an attribute error, which may be an odd interface.
What I have here _works_ but I'm not sure it's an ideal interface. …
> feat(api):add support for creating/editing reviewers in project MRs

- docs/gl_objects/projects.rst
- docs/gl_objects/releases.rst
- gitlab/v4/objects/releases.py
- tests/functional/api/test_releases.py
- tests/unit/objects/test_releases.py
Following https://github.com/python-gitlab/python-gitlab/issues/1521: 
- Removal of the documentation for deprecated API
- Support the PUT function of the [release API](https://docs.gitlab.com/ee/api/releases/#update-a-release)
- Add documentation
- unit-test + integration test (well, I've tried)
Closes #1521
> Support Release edition API

- docs/gl_objects/projects.rst
Hello,
This is apparently not present in the documentation (I couldn't find it) while the API supports it and it's very useful.
I've tried to keep the terminology "name_with_namespace" from `project.attributes`.
Kind regards,
> docs(project): add example on getting a single project using name with namespace

- docs/gl_objects/mrs.rst
- gitlab/v4/objects/merge_requests.py
- tests/functional/api/test_merge_requests.py
Support merge_ref on merge requests that returns commit of attempted
merge of the MR.
Signed-off-by: Matej Focko <mfocko@redhat.com>
Needed to finish packit/ogr#584
> feat(api): Add merge_ref for merge requests

- gitlab/v4/objects/releases.py
- tests/functional/api/test_releases.py
This has not been required by the [GitLab API](https://docs.gitlab.com/ee/api/releases/#create-a-release) since v12.5, so should not be required here.
> Do not require Release name for creation

- setup.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1547.
We have already been testing with 2.25.x and 2.26.0 for a while (https://github.com/python-gitlab/python-gitlab/commits/master/requirements.txt), so I don't see an issue bumping this. Technically 2.25.0 already has the urllib3 fix though.
> fix(deps): upgrade requests to minimum 2.25.0 (CVE-2021-33503)

- docs/gl_objects/mrs.rst
Hello,
Quoting gitlab's official documentation: https://docs.gitlab.com/ce/api/merge_requests.html#list-merge-requests
> Get all merge requests the authenticated user has access to. By default it returns only merge requests created by the current user. To get all merge requests, use parameter scope=all. 
I've tried to adapt the documentation according to this fact.
Kind regards,
> docs(mergequests): gl.mergequests.list documentation was missleading

- .mypy.ini
- .pre-commit-config.yaml
- .renovaterc.json
- pyproject.toml
- tox.ini
Closes https://github.com/python-gitlab/python-gitlab/issues/1539.
Additionally, since mypy 0.910 doesn't bundle stubs anymore we need to track them for pre-commit's own virtualenv :/ See https://github.com/pre-commit/pre-commit/issues/730
> chore: fix mypy pre-commit hook

- docs/api-usage.rst
- gitlab/client.py
- gitlab/config.py
- tests/unit/conftest.py
- tests/unit/test_config.py
- tests/unit/test_gitlab_http_methods.py
Value set on the `Gitlab` object will be used as a default in case every
subsequent API call does not provide a `retry_transient_errors`
parameter.
This allows code to be succinct and the retry policy to be set for all
calls to the `Gitlab` instance.
> feat: allow global retry_transient_errors

- gitlab/v4/objects/repositories.py
repository_archive() returns 'bytes' not 'str'
https://docs.gitlab.com/ee/api/repositories.html#get-file-archive
Fixes: #1584
> docs: correct documented return type

- .github/workflows/test.yml
- pyproject.toml
- setup.py
- tests/smoke/test_dists.py
- tox.ini
Closes https://github.com/python-gitlab/python-gitlab/issues/1586.
This way tests are packaged in the source distribution (via includes in Manifest), but excluded from the wheel.
> fix(build): only package tests in source distribution

- docs/api-usage.rst
- docs/cli-usage.rst
- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
Before we raised an error if there was a 301, 302 redirect but only
from an http URL to an https URL.  But we didn't raise an error for
any other redirects.
This caused two problems:
1. PUT requests that are redirected get changed to GET requests
which don't perform the desired action but raise no error. This
is because the GET response succeeds but since it wasn't a PUT it
doesn't update. See issue:
#1432
2. POST requests that are redirected also got changed to GET
requests. They also caused hard to debug tracebacks for the user.
See issue:
#1477
Correct this by always raising a RedirectError exception and improve
the exception message to let them know what was redirected.
Closes: #1485
Closes: #1432
Closes: #1477
> fix: raise error if there is a 301/302 redirection

- docs/api-usage.rst
- docs/cli-usage.rst
- gitlab/client.py
- gitlab/const.py
- tests/unit/test_gitlab.py
The github CLI (`gh`) defaults to github.com if no arguments are given. Something similar would make sense here IMO, just for convenience :)
> feat(api): default to gitlab.com if no URL given

- CHANGELOG.md
- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_merge_request_pipelines.py
BREAKING CHANGE: remove deprecated pipelines() methods in favor of pipelines.list()
> chore(objects): remove deprecated pipelines() method

- docs/gl_objects/groups.rst
- docs/gl_objects/projects.rst
- gitlab/mixins.py
- gitlab/v4/objects/members.py
- tests/functional/api/test_groups.py
BREAKING CHANGE: remove deprecated members.all() method in favor of members_all.list()
> refactor(objects): remove deprecated members.all() method

- gitlab/v4/objects/projects.py
- tests/unit/objects/test_issues.py
BREAKING CHANGE: remove deprecated project.issuesstatistics in favor of project.issues_statistics
> refactor(objects): remove deprecated project.issuesstatistics

- gitlab/v4/objects/tags.py
- tests/functional/api/test_projects.py
BREAKING CHANGE: remove deprecated tag release API.
This was removed in cca. GitLab 14.0
> refactor(objects): remove deprecated tag release API

- gitlab/v4/objects/groups.py
BREAKING CHANGE: rename confusing `to_project_id` argument in transfer_project
to `project_id` (`--project-id` in CLI). This is used for the source project,
not for the target namespace.
Closes https://github.com/python-gitlab/python-gitlab/issues/1529.
> fix(objects): rename confusing `to_project_id` argument

- docs/gl_objects/personal_access_tokens.rst
- gitlab/v4/objects/personal_access_tokens.py
- gitlab/v4/objects/users.py
- tests/unit/objects/test_personal_access_tokens.py
Not super happy about the split between Users API/tokens API endpoints, but I hope the docs on this clear it up.
Closes https://github.com/python-gitlab/python-gitlab/issues/1540.
> feat(objects): support Create and Revoke personal access token API

- docs/gl_objects/deploy_tokens.rst
- gitlab/base.py
- gitlab/mixins.py
- gitlab/v4/objects/features.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/sidekiq.py
- gitlab/v4/objects/todos.py
There are small typos in:
- docs/gl_objects/deploy_tokens.rst
- gitlab/base.py
- gitlab/mixins.py
- gitlab/v4/objects/features.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/sidekiq.py
- gitlab/v4/objects/todos.py
Fixes:
- Should read `treatment` rather than `reatment`.
- Should read `transferred` rather than `transfered`.
- Should read `registered` rather than `registred`.
- Should read `occurred` rather than `occured`.
- Should read `overridden` rather than `overriden`.
- Should read `marked` rather than `maked`.
- Should read `instantiate` rather than `instanciate`.
- Should read `function` rather than `fonction`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.m …
> docs: fix a few typos

- docs/gl_objects/branches.rst
- gitlab/v4/objects/branches.py
BREAKING CHANGE: remove deprecated branch protect methods in favor of
the more complete Protected branches API.
Closes https://github.com/python-gitlab/python-gitlab/issues/821.
@max-wittig WDYT about removing this completely? Then people will stop getting confused about the two APIs like in https://github.com/python-gitlab/python-gitlab/issues/1355 and https://github.com/python-gitlab/python-gitlab/issues/821. The endpoint still technically works, but the GitLab API docs removed it ages ago and they point to the dedicated protected branches API now (https://docs.gitlab.com/ee/api/branches.html#protect-repository-branch). 
Last time we kept a deprecated endpoint (release via tags API) it bit us because GitLab then "silently" removed it. Just adding this to the list of breaking changes as …
> refactor(objects): remove deprecated branch protect methods

- gitlab/v4/objects/users.py
- pyproject.toml
Adding type-hints to gitlab/v4/objects/users.py
> chore: add type-hints to gitlab/v4/objects/users.py

- docs/gl_objects/milestones.rst
- gitlab/v4/objects/milestones.py
- tests/functional/api/test_projects.py
Adds promotion to Project Milestones
Fixes #1654
> feat(api): add project milestone promotion

- setup.py
- tests/smoke/test_dists.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1652 (which we forgot when we fixed tests in wheel)
> fix(build): do not include docs in wheel package

- codecov.yml
This fixes an annoyance where codecov keeps posting comments even if the coverage didn't change, because it first reports only unit tests so it's of course lower than the full report.
With this, we should only get comments by codecov if coverage actually changes.
> chore(ci): wait for all coverage jobs before posting comment

- gitlab/v4/objects/merge_requests.py
Add links to the GitLab API docs for merge_requests.py as it contains
code which spans two different API documentation pages.
> docs: add links to the GitLab API docs

- gitlab/v4/objects/merge_requests.py
- pyproject.toml
* Add type-hints to gitlab/v4/objects/merge_requests.py
* Add return value to cancel_merge_when_pipeline_succeeds() function
as GitLab docs show it returns a value.
* Add return value to approve() function as GitLab docs show it
returns a value.
* Add 'get()' method so that type-checkers will understand that
getting a project merge request is of type ProjectMergeRequest.
> chore: add type-hints to gitlab/v4/objects/merge_requests.py

- gitlab/v4/objects/groups.py
- pyproject.toml
* Add type-hints to gitlab/v4/objects/groups.py
* Add return value to share() function as GitLab docs show it returns
a value.
* Add 'get()' method so that type-checkers will understand that
getting a group is of type Group.
> chore: add type-hints to gitlab/v4/objects/groups.py

- gitlab/v4/objects/broadcast_messages.py
- gitlab/v4/objects/keys.py
- gitlab/v4/objects/merge_trains.py
- gitlab/v4/objects/namespaces.py
- gitlab/v4/objects/pages.py
- gitlab/v4/objects/triggers.py
- pyproject.toml
Add and/or check type-hints for the following files
gitlab.v4.objects.access_requests
gitlab.v4.objects.applications
gitlab.v4.objects.broadcast_messages
gitlab.v4.objects.deployments
gitlab.v4.objects.keys
gitlab.v4.objects.merge_trains
gitlab.v4.objects.namespaces
gitlab.v4.objects.pages
gitlab.v4.objects.personal_access_tokens
gitlab.v4.objects.project_access_tokens
gitlab.v4.objects.tags
gitlab.v4.objects.templates
gitlab.v4.objects.triggers
Add a 'get' method with the correct type for Managers derived from
GetMixin.
> chore: add type-hints to multiple files in gitlab/v4/objects/

- .github/workflows/lock.yml
See https://github.com/dessant/lock-threads for more info. The terraform repo also uses this action so.. must be ok :eyes:
> chore(ci): add workflow to lock old issues

- gitlab/client.py
- gitlab/v4/cli.py
- gitlab/v4/objects/appearance.py
- gitlab/v4/objects/badges.py
- gitlab/v4/objects/boards.py
- gitlab/v4/objects/clusters.py
- gitlab/v4/objects/container_registry.py
- gitlab/v4/objects/deploy_keys.py
- gitlab/v4/objects/environments.py
- gitlab/v4/objects/export_import.py
- gitlab/v4/objects/features.py
- gitlab/v4/objects/ldap.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/push_rules.py
- gitlab/v4/objects/releases.py
- gitlab/v4/objects/runners.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/todos.py
- gitlab/v4/objects/variables.py
- gitlab/v4/objects/wikis.py
- pyproject.toml
* Add type-hints to some of the files in gitlab/v4/objects/
* Fix issues detected when adding type-hints
* Changed mypy exclusion to explicitly list the 13 files that have
not yet had type-hints added.
> chore: enforce type-hints on most files in gitlab/v4/objects/

- pyproject.toml
Prior commit 06184daafd5010ba40bb39a0768540b7e98bd171 fixed the
type-hints for setup.py. But missed removing 'setup' from the exclude
list in pyproject.toml for mypy checks.
Remove 'setup' from the exclude list in pyproject.toml from mypy checks.
> chore: check setup.py with mypy

- tests/functional/api/test_groups.py
The test was checking twice if the same group3 was not in the returned
list.  Should have been checking for group3 and group4.
Also added a test that only skipped one group and checked that the
group was not in the returned list and a non-skipped group was in the
list.
> chore: correct test_groups.py test

- .commitlintrc.json
- .renovaterc.json
renovate is not upgrading the `black` package. There is an open
issue[1] about this.
Use suggested work-around from:
https://github.com/renovatebot/renovate/issues/7167#issuecomment-904106838
&
https://github.com/scop/bash-completion/blob/e7497f6ee8232065ec11450a52a1f244f345e2c6/renovate.json#L34-L38
1. https://github.com/renovatebot/renovate/issues/7167
> fix: have renovate upgrade black version

- .github/workflows/test.yml
- docs/install.rst
- setup.py
- tox.ini
Python 3.6 is End-of-Life (EOL) as of 2021-12 as stated in
https://www.python.org/dev/peps/pep-0494/
By dropping support for Python 3.6 and requiring Python 3.7 or higher
it allows python-gitlab to take advantage of new features in Python
3.7, which are documented at:
https://docs.python.org/3/whatsnew/3.7.html
Some of these new features that may be useful to python-gitlab are:
* PEP 563, postponed evaluation of type annotations.
* dataclasses: PEP 557 – Data Classes
* importlib.resources
* PEP 562, customization of access to module attributes.
* PEP 560, core support for typing module and generic types.
* PEP 565, improved DeprecationWarning handling
BREAKING CHANGE: As of python-gitlab 3.0.0, Python 3.6 is no longer
supported. Python 3.7 or higher is required.
> feat: remove support for Python 3.6, require 3.7 or higher

- gitlab/base.py
- gitlab/v4/objects/epics.py
- gitlab/v4/objects/files.py
- gitlab/v4/objects/geo_nodes.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/labels.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/services.py
- gitlab/v4/objects/sidekiq.py
- pyproject.toml
Fixed a bug in the auto-manager creation code if we added a type-hint for the `manager` attribute.
Add type-hints for the remainder of the code base.
Finally! 😊
> chore: add type-hints to remaining gitlab/v4/objects/*.py files

- requirements-lint.txt
- tests/meta/test_ensure_type_hints.py
Before we were generating 725 tests for the
meta/test_ensure_type_hints.py tests.  Which isn't a huge concern as
it was fairly fast. But when we had a failure we would usually get two
failures for each problem as the same test was being run multiple
times.
Changed it so that:
1. Don't add tests that are not for *Manager classes
2. Use a set so that we don't have duplicate tests.
After doing that our generated test count in
meta/test_ensure_type_hints.py went from 725 to 178 tests.
Additionally removed the parsing of `pyproject.toml` to generate files
to ignore as we have finished adding type-hints to all files in
gitlab/v4/objects/. This also means we no longer use the toml library
so remove installation of `types-toml`.
To determine the test count the following command was run:
$ tox -e …
> chore: remove duplicate/no-op tests from meta/test_ensure_type_hints

- docs/gl_objects/projects.rst
- gitlab/v4/objects/projects.py
- tests/functional/api/test_projects.py
Add support for `projects.groups.list()` endpoint.
Closes https://github.com/python-gitlab/python-gitlab/issues/1590
> feat: add support for `projects.groups.list()`

- tox.ini
Remove the pytest-console-scripts specific config from the global
'[pytest]' config section.
Move it to a command line option for the functional tests which use
the Docker container.
Closes #1713
> chore: remove pytest-console-scripts specific config

- docs/gl_objects/access_requests.rst
- docs/gl_objects/groups.rst
- docs/gl_objects/notifications.rst
- docs/gl_objects/projects.rst
- docs/gl_objects/protected_branches.rst
- docs/gl_objects/search.rst
- docs/gl_objects/snippets.rst
- gitlab/__init__.py
- gitlab/const.py
- gitlab/mixins.py
- tests/functional/api/test_gitlab.py
- tests/functional/api/test_snippets.py
- tests/unit/test_config.py
- tests/unit/test_gitlab.py
We are planning on adding enumerated constants into gitlab/const.py,
but if we do that than they will end up being added to the top-level
gitlab namespace. We really want to get users to start using
`gitlab.const.` to access the constant values in the future.
Explicitly add the current values defined in gitlab.const into the
top-level namespace and stop using the previous
'from gitlab.const import *' method.
> refactor: explicitly import gitlab.const values into top-level namespace

- docs/faq.rst
- gitlab/base.py
- gitlab/mixins.py
- tests/unit/test_base.py
A commonly reported issue from users on Gitter is that they get an
AttributeError for an attribute that should be present. This is often
caused due to the fact that they used the `list()` method to retrieve
the object and objects retrieved this way often only have a subset of
the full data.
Add more details in the AttributeError message that explains the
situation to users. This will hopefully allow them to resolve the
issue.
Closes #1138
> chore: attempt to be more informative for missing attributes

- gitlab/v4/cli.py
- pyproject.toml
Fix pylint error "expression-not-assigned" and remove check from the
disabled list.
And I personally think it is much more readable now and is less lines
of code.
> chore: fix pylint error "expression-not-assigned"

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/pre_commit.yml
- .github/workflows/test.yml
If new new push is done to a pull-request, then cancel any already
running github workflow jobs in order to conserve resources.
> chore: github workflow: cancel prior running jobs on new push

- gitlab/v4/objects/appearance.py
- gitlab/v4/objects/export_import.py
- gitlab/v4/objects/merge_request_approvals.py
- gitlab/v4/objects/notification_settings.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/push_rules.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/statistics.py
- gitlab/v4/objects/users.py
- tests/meta/test_ensure_type_hints.py
Add the get() methods for the GetWithoutIdMixin based classes.
Update the tests/meta/test_ensure_type_hints.py tests to check to
ensure that the get methods are defined with the correct return type.
> chore: add get() methods for GetWithoutIdMixin based classes

- .github/workflows/test.yml
Add a unit test for Python 3.11. This will use the latest version of
Python 3.11 that is available from
https://github.com/actions/python-versions/
At this time it is 3.11.0-alpha.2 but will move forward over time
until the final 3.11 release and updates. So 3.11.0, 3.11.1, ... will
be matched.
> chore: add Python 3.11 testing

- .pre-commit-config.yaml
- docs/cli-usage.rst
- gitlab/config.py
- requirements-test.txt
- tests/functional/cli/test_cli.py
- tests/unit/test_config.py
BREAKING CHANGE: A config file is no longer needed to run
the CLI. python-gitlab will default to https://gitlab.com
with no authentication if there is no config file provided.
python-gitlab will now also only look for configuration
in the provided PYTHON_GITLAB_CFG path, instead of merging
it with user- and system-wide config files. If the
environment variable is defined and the file cannot be
opened, python-gitlab will now explicitly fail.
Needed for https://github.com/python-gitlab/python-gitlab/pull/1296
> feat(cli): do not require config file to run CLI

- .gitignore
The `.env` file was not set as a file that should not be ignored by
search tools. We want to have the search tools search any `.env`
files.
> chore: add .env as a file that search tools should not ignore

- docs/gl_objects/projects.rst
This closes #1751 
Removing encoding parameter as - default is text which means you don't have to specify that parameter itself when you are creating a text file.
> docs(project): remove redundant encoding parameter

- gitlab/client.py
- gitlab/utils.py
- tests/unit/objects/test_packages.py
- tests/unit/objects/test_releases.py
- tests/unit/objects/test_repositories.py
- tests/unit/test_utils.py
Forcing the encoding of '.' to '%2E' causes issues. It also goes
against the RFC:
https://datatracker.ietf.org/doc/html/rfc3986.html#section-2.3
From the RFC:
For consistency, percent-encoded octets in the ranges of ALPHA
(%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),
underscore (%5F), or tilde (%7E) should not be created by URI
producers...
Closes #1006
Related #1356
Related #1561
BREAKING CHANGE: stop encoding '.' to '%2E'. This could potentially be
a breaking change for users who have incorrectly configured GitLab
servers which don't handle period '.' characters correctly.
> fix: stop encoding '.' to '%2E'

- .github/workflows/docs.yml
When building the docs store the created documentation as an artifact
so that it can be viewed.
This will create a html-docs.zip file which can be downloaded
containing the contents of the `build/sphinx/html/` directory. It can
be downloaded, extracted, and then viewed. This can be useful in
reviewing changes to the documentation.
See https://github.com/actions/upload-artifact for more information on
how this works.
> chore: generate artifacts for the docs build in the CI

- tests/functional/fixtures/docker-compose.yml
When running with docker-compose on Ubuntu 20.04 I got the error:
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.gitlab-network value Additional properties are not allowed ('name' was unexpected)
Changing the version in the docker-compose.yml file fro '3' to '3.5'
resolved the issue.
> chore: update version in docker-compose.yml

- tests/functional/api/test_repository.py
One of the tests requires Python 3.9 or higher to run. Mark the test
to be skipped if running Python less than 3.9.
> chore: skip a functional test if not using >= py3.9

- tests/functional/conftest.py
Ensure reset_gitlab() succeeds by waiting to make sure everything has
been deleted as expected. If the timeout is exceeded fail the test.
Not using `wait_for_sidekiq` as it didn't work. During testing I
didn't see any sidekiq processes as being busy even though not
everything was deleted.
> chore: ensure reset_gitlab() succeeds

- docs/api-usage.rst
- gitlab/base.py
- gitlab/client.py
- pyproject.toml
- tests/unit/test_gitlab.py
If a query returns more than 10,000 records than the following values
are NOT returned:
x.total_pages
x.total
Modify the code to allow no value to be set for these values. If there
is not a value returned the functions will now return None.
https://docs.gitlab.com/ee/user/gitlab_com/index.html#pagination-response-headers
Closes #1686
> fix: handle situation where gitlab.com does not return values

- .pre-commit-config.yaml
Not quite sure why renovate hasn't picked it up after configuring it, will check this later.
> chore(deps): upgrade mypy pre-commit hook

- docs/cli-usage.rst
- gitlab/cli.py
- gitlab/client.py
- gitlab/config.py
- tests/functional/cli/test_cli.py
- tests/unit/test_config.py
- tests/unit/test_gitlab_auth.py
Closes https://github.com/python-gitlab/python-gitlab/issues/960
Closes https://github.com/python-gitlab/python-gitlab/issues/893
Makes it easier to later introduce https://github.com/python-gitlab/python-gitlab/issues/715 hopefully, and maybe https://github.com/python-gitlab/python-gitlab/issues/1195.
BREAKING-CHANGE: The gitlab CLI will now accept CLI arguments
and environment variables for its global options in addition
to configuration file options. This may change behavior for
some workflows such as running inside GitLab CI and with
certain environment variables configured.
> feat(cli): allow options from CLI args or environment variables

- tests/functional/api/test_branches.py
Add a test case to show that a branch name with a period can be
fetched with a `get()`
Closes: #1715
> chore: add test case to show branch name with period works

- .github/workflows/stale.yml
Use the stale action to close issues and pull-requests with no
activity.
Issues: It will mark them as stale after 60 days and then close
them once they have been stale for 15 days.
Pull-Requests: It will mark pull-requests as stale after 90 days and then close
them once they have been stale for 15 days.
https://github.com/actions/stale
Closes: #1649
> chore: add a stale workflow

- MANIFEST.in
build_sphinx to fail due to setup.cfg warning-is-error
> chore(dist): add docs *.md files to sdist

- gitlab/v4/objects/commits.py
Fix the type-hints and use `http_list()` for the ProjectCommits methods:
- diff()
- merge_requests()
- refs()
This will enable using the pagination support we have for lists.
Closes: #1805
Closes: #1231
> fix: change to `http_list` for some ProjectCommit methods

- docs/cli-examples.rst
- docs/cli-usage.rst
Also, use pretty admonitions consistently :grin: 
Compare existing https://python-gitlab.readthedocs.io/en/stable/cli-examples.html with:
> docs(cli): make examples more easily navigable by generating TOC

- gitlab/v4/cli.py
- tests/functional/cli/conftest.py
- tests/functional/cli/test_cli.py
- tests/functional/cli/test_cli_variables.py
In the CLI we need to make sure the components put into the path
portion of the URL are url-encoded. Otherwise they will be interpreted
as part of the path. For example can specify the project ID as a path,
but in the URL it must be url-encoded or it doesn't work.
Also stop adding the components of the path as query parameters in the
URL.
Closes: #783
Closes: #1498
> fix(cli): url-encode path components of the URL

- gitlab/v4/objects/merge_requests.py
- tests/functional/api/test_merge_requests.py
The arguments `should_remove_source_branch` and
`merge_when_pipeline_succeeds` are optional arguments. We should not
be setting any default value for them.
https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr
Closes: #1750
> fix: remove default arguments for mergerequests.merge()

- gitlab/mixins.py
- gitlab/utils.py
- gitlab/v4/cli.py
- gitlab/v4/objects/features.py
- gitlab/v4/objects/files.py
- gitlab/v4/objects/repositories.py
- tests/functional/api/test_repository.py
- tests/unit/test_utils.py
We were using `str.replace()` calls to take care of URL encoding
issues.
Switch them to use our `utils._url_encode()` function which itself uses
`urllib.parse.quote()`
Closes: #1356
> fix: remove custom URL encoding

- .github/workflows/test.yml
- pyproject.toml
- tests/functional/conftest.py
- tox.ini
I have found trying to debug issues in the functional tests can be
difficult. Especially when trying to figure out failures in the CI
running on Github.
Add logging to `tests/functional/conftest.py` to have a better
understanding of what is happening during a test run which is useful
when trying to troubleshoot issues in the CI.
> chore: add logging to `tests/functional/conftest.py`

- docs/api-usage.rst
- gitlab/base.py
- tests/unit/test_base.py
This is useful in debugging and testing. As can easily print out the
values from an instance in a more human-readable form.
> chore: add `pprint()` and `pformat()` methods to RESTObject

- docs/gl_objects/project_access_tokens.rst
- tests/unit/objects/test_project_access_tokens.py
The project access tokens API reference page was moved, see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/77649.
/cc @max-wittig @nejch
> docs: update project access token API reference link

- docs/api-objects.rst
- docs/gl_objects/group_access_tokens.rst
- gitlab/v4/objects/group_access_tokens.py
- gitlab/v4/objects/groups.py
- tests/unit/objects/test_group_access_tokens.py
This MR adds support for the newly created Group Access Tokens API, see https://docs.gitlab.com/ee/api/group_access_tokens.html.
/cc @max-wittig @nejch
> feat: add support for Group Access Tokens API

- gitlab/base.py
```
The URL was missing a 'v' before the version number and thus the page
did not exist.
Previously the URL for python-gitlab 3.0.0 was:
https://python-gitlab.readthedocs.io/en/3.0.0/faq.html#attribute-error-list
Which does not exist.
Change it to:
https://python-gitlab.readthedocs.io/en/v3.0.0/faq.html#attribute-error-list
add the 'v' --------------------------^
```
> fix: broken URL for FAQ about attribute-error-list

- gitlab/v4/objects/services.py
- tests/functional/api/test_services.py
Commit 8da0b758c589f608a6ae4eeb74b3f306609ba36d added the `lazy`
parameter to the services `get()` method but missed then using the
`lazy` parameter when it called `super(...).get(...)`
Closes: #1828
> fix(api): services: add missing `lazy` parameter

- gitlab/v4/objects/members.py
- tests/functional/cli/test_cli_v4.py
Change it so that:
GroupMemberAllManager uses GroupMemberAll object
ProjectMemberAllManager uses ProjectMemberAll object
Create GroupMemberAll and ProjectMemberAll objects that do not support
any Mixin type methods. Previously we were using GroupMember and
ProjectMember which support the `save()` and `delete()` methods but
those methods will not work with objects retrieved using the
`/members/all/` API calls.
`list()` API calls:
GET /groups/:id/members/all
GET /projects/:id/members/all
`get()` API calls:
GET /groups/:id/members/all/:user_id
GET /projects/:id/members/all/:user_id
Closes: #1825
Closes: #848
[1] https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-and-invited-members
[2] …
> fix: members: use new *All objects for *AllManager managers

- gitlab/base.py
- gitlab/mixins.py
- gitlab/utils.py
- gitlab/v4/cli.py
- gitlab/v4/objects/commits.py
- gitlab/v4/objects/environments.py
- gitlab/v4/objects/epics.py
- gitlab/v4/objects/features.py
- gitlab/v4/objects/files.py
- gitlab/v4/objects/geo_nodes.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/merge_request_approvals.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/snippets.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_lazy_objects.py
- tests/functional/api/test_wikis.py
- tests/functional/conftest.py
- tests/unit/test_base.py
- tests/unit/test_utils.py
Make sure all usage of the ID in the URL path is encoded. Normally it
isn't an issue as most IDs are integers or strings which don't contain
a slash ('/'). But when the ID is a string with a slash character it
will break things.
Add a test case that shows this fixes wikis issue with subpages which
use the slash character.
Closes: #1079
> fix: use url-encoded ID in all paths

- .github/workflows/test.yml
If a CI job can't upload coverage results to codecov.com it causes the
CI to fail and code can't be merged.
> ci: don't fail CI if unable to upload the code coverage data

- gitlab/mixins.py
Return the new object data when calling `SaveMixin.save()`.
Also remove check for `None` value when calling
`self.manager.update()` as that method only returns a dictionary.
Closes https://github.com/python-gitlab/python-gitlab/issues/1081.
> feat(api): return result from `SaveMixin.save()`

- gitlab/v4/objects/projects.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_projects.py
- tests/unit/objects/test_groups.py
- tests/unit/objects/test_projects.py
Needed to bring things in line with https://github.com/python-gitlab/python-gitlab/pull/1807.
`transfer_project` was very confusing already as the direction of transfer can differ depending on the endpoint, see other PR for discussion.
> feat(api): add `project.transfer()` and deprecate `transfer_project()`

- gitlab/v4/objects/groups.py
- gitlab/v4/objects/projects.py
Updated a few remaining usages of `self.id` to use `self.encoded_id`
where it could be a string value.
> chore(objects): use `self.encoded_id` where could be a string

- gitlab/v4/objects/todos.py
- gitlab/v4/objects/users.py
Updated a few remaining usages of `self.id` to use `self.encoded_id`
as for the most part we shouldn't be using `self.id`
There are now only a few (4 lines of code) remaining uses of
`self.id`, most of which seem that they should stay that way.
> chore(objects): use `self.encoded_id` where applicable

- tests/functional/api/test_projects.py
When doing the functional tests use the new function
`projects.transfer` instead of the deprecated function
`projects.transfer_project()`
> chore(tests): use method `projects.transfer()`

- CHANGELOG.md
Looks like `python-semantic-release` had a bad day and didn't parse some of @fh1ch's commits and others :clown_face:
> docs(changelog): add missing changelog items

- gitlab/base.py
- gitlab/mixins.py
- gitlab/v4/objects/files.py
Create return type-hints for `RESTObject.get_id()` and
`RESTObject.encoded_id`. Previously was saying they return Any. Be
more precise in saying they can return either: None, str, or int.
> chore: create return type-hints for `get_id()` & `encoded_id`

- gitlab/v4/objects/__init__.py
- tests/functional/cli/test_cli_resource_access_tokens.py
This was a bit of an oversight from me a while ago and it's carried over to newer PRs.
> fix(objects): make resource access tokens and repos available in CLI

- gitlab/v4/cli.py
- tests/functional/cli/conftest.py
- tests/functional/cli/test_cli_projects.py
Closes #849 
@JohnVillalovos let me know if you're not available these days and I can re-assign :)
This is still a bit dirty - we need a `DeleteWithoutIdMixin` actually, hence the note in the test. But that's out of scope for this PR I'd say. Also I'm mocking the response in the functional CLI test because of the scaffolding required to get a full docker registry repo up for tests. It still tests the actual CLI not just units though. Maybe one day we add :)
> fix(cli): allow custom methods in managers

- gitlab/types.py
- gitlab/v4/objects/deploy_tokens.py
- gitlab/v4/objects/epics.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/runners.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/users.py
- tests/unit/test_types.py
This name more accurately describes what the type is. Also this is the
first step in a series of steps of our goal to add full support for
the GitLab API data types[1]:
* array
* hash
* array of hashes
[1] https://docs.gitlab.com/ee/api/#encoding-api-parameters-of-array-and-hash-types
> chore: rename `types.ListAttribute` to `types.CommaSeparatedListAttribute`

- gitlab/cli.py
- gitlab/v4/cli.py
This PR is mainly for fixing handling of `--timeout` / `GITLAB_TIMEOUT`.
**Before:**
```
$ docker run -it --rm python-gitlab:latest --timeout=10 project get --id gitlab-org/gitlab
Impossible to get object (Timeout value connect was 10, but it must be an int, float or None.)
$ docker run -it --rm -e GITLAB_TIMEOUT=10 python-gitlab:latest project get --id gitlab-org/gitlab
Impossible to get object (Timeout value connect was 10, but it must be an int, float or None.)
```
**After (with bbb7df526f4375c438be97d8cfa0d9ea9d604e7d):**
```
$ docker run -it --rm python-gitlab:latest --timeout 10 project get --id gitlab-org/gitlab
id: 278964
path: gitlab
$ docker run -it --rm -e GITLAB_TIMEOUT=10 python-gitlab:latest project get --id gitlab-org/gitlab
id: 278964
path: gitlab
$ docker run -it --rm …
```
> fix(cli): make 'timeout', 'per_page' and 'page' type explicit

- .github/workflows/release.yml
So we don't get scary emails from forks that we've rebased PRs for.
> chore(ci): do not run release workflow in forks

- docs/conf.py
Super minor change which allows accessing the changelog from the warning at the top from anywhere in the documentation.
Right now it's e.g. `https://python-gitlab.readthedocs.io/en/stable/api/changelog.html#breaking` instead of `https://python-gitlab.readthedocs.io/en/stable/changelog.html#breaking` when accessing it from the `API reference` page. This should fix that.
I simply tested it with the builtin Python server, not sure if the behavior is the same when deployed:
```bash
tox -e docs
cd build/sphinx/html
python -m http.server
```
> docs: revert temporary changelog link for v3

- gitlab/types.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/users.py
- tests/unit/test_types.py
Create a new ArrayAttribute class. This is to indicate types which are
sent to the GitLab server as arrays
https://docs.gitlab.com/ee/api/#array
At this stage it is identical to the CommaSeparatedListAttribute class
but will be used later to support the array types sent to GitLab.
This is the second step in a series of steps of our goal to add full
support for the GitLab API data types[1]:
* array
* hash
* array of hashes
Step one was: commit 5127b1594c00c7364e9af15e42d2e2f2d909449b
[1] https://docs.gitlab.com/ee/api/#encoding-api-parameters-of-array-and-hash-types
Related: #1698
> chore: create new ArrayAttribute class

- gitlab/v4/objects/labels.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_projects.py
The usage of deleting was incorrect according to the current API.
Remove custom `delete()` method as not needed.
Add tests to show it works with labels needing to be encoded.
Also enable the test_group_labels() test function. Previously it was
disabled.
Add ability to do a `get()` for group labels.
Closes: #1867
> fix: remove custom `delete` method for labels

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/artifacts.py
- gitlab/v4/objects/projects.py
- tests/functional/cli/test_cli_artifacts.py
- tests/unit/objects/test_job_artifacts.py
Part 1 of https://github.com/python-gitlab/python-gitlab/pull/1865
All this does is move the custom methods from `ProjectManager` into its own `ProjectArtifactManager` and deprecates the old ones. Along the way I had to fix the paths in the new manager. Also added a dummy object to make CLI custom_actions happy.
> feat(objects): add a complete artifacts manager

- gitlab/client.py
- gitlab/utils.py
The non-keyword arguments were a tiny bit confusing as the destination was
first and the source was second.
Change the order and require key-word only arguments to ensure we
don't silently break anyone.
> chore: require kwargs for `utils.copy_dict()`

- docs/api-usage.rst
Looking through code, If I understand correctly it looks like it won't retry forever but stops after max_retries count is reached.
I that correct, I would like to add that in doc.
> docs: add transient errors retry info

- gitlab/base.py
- gitlab/client.py
There are occasions where a GitLab `list()` call does not return the
`x-per-page` header. For example the listing of custom attributes.
Update the type-hints to reflect that.
> chore: correct type-hints for per_page attrbute

- tests/functional/api/test_gitlab.py
- tests/functional/api/test_projects.py
- tests/functional/fixtures/docker-compose.yml
When pagination occurs python-gitlab uses the URL provided by the
GitLab server to use for the next request.
We had previously set the GitLab server configuraiton to say its URL
was `http://gitlab.test` which is not in DNS. Set the hostname
in the URL to `http://127.0.0.1:8080` which is the correct URL for the
GitLab server to be accessed while doing functional tests.
Closes: #1877
> test(functional): fix GitLab configuration to support pagination

- gitlab/__init__.py
- gitlab/utils.py
- gitlab/v4/objects/artifacts.py
- gitlab/v4/objects/projects.py
- tests/unit/test_utils.py
Create a custom `warnings.warn` wrapper that will walk the stack trace
to find the first frame outside of the `gitlab/` path to print the
warning against. This will make it easier for users to find where in
their code the error is generated from
> chore: create a custom `warnings.warn` wrapper

- docs/gl_objects/pipelines_and_jobs.rst
- docs/gl_objects/runners.rst
- gitlab/mixins.py
- gitlab/v4/objects/artifacts.py
- tests/unit/objects/test_job_artifacts.py
- tests/unit/objects/test_runners.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1631
I started out this PR hoping we would have a generic DeleteMixin for both runners and artifacts, but of course the artifacts endpoint is inconsistent with the other ones. So again I had to add a tiny custom method :sweat_smile:
> feat(mixins): allow deleting resources without IDs

- README.rst
- docs/_static/js/gitter.js
- docs/conf.py
First ever pull request from aboard a plane :sweat_smile: 
When maintainers are away/on holiday I thought it might be good if we just have a community chat more visible and people can sort it out before opening issues. Or just in general to have simple questions resolved before opening issues
> docs: enable gitter chat directly in docs

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_pipelines.py
Hello !
This adds the support of the test report summary endpoint. See : [here](https://docs.gitlab.com/ee/api/pipelines.html#get-a-pipelines-test-report-summary)
> feat: Test report summary

- docs/gl_objects/applications.rst
Hi all,
I found a small hickup in the docs that took me a few minutes to understand. Looking at [API docs](https://docs.gitlab.com/ee/api/applications.html) and the code I have found out that the way we try to push the application scopes doesn't match the API. I'd like to leave an appropriate example in docs so that people don't get stuck on this
> docs:Small docs fixup for application scopes

- docs/gl_objects/topics.rst
- gitlab/v4/objects/topics.py
- tests/functional/api/test_topics.py
- tests/functional/conftest.py
- tests/functional/fixtures/.env
- tests/unit/objects/test_topics.py
This reverts commit e3035a799a484f8d6c460f57e57d4b59217cd6de.
When I was adding this initially I didn't realize they omitted the delete endpoint. That's handy now as it's been added in 14.9:
https://about.gitlab.com/releases/2022/03/22/gitlab-14-9-released/#api-endpoint-to-delete-project-topics
> Revert "chore(api): temporarily remove topic delete endpoint"

- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
Based off of https://github.com/python-gitlab/python-gitlab/pull/1648
This adds additional retries for the 52x caused by cloudflare.
This adds tests for the 52x range and the `requests.ConnectionError` exception
> Retry additional http transient errors

- gitlab/client.py
- tests/functional/api/test_gitlab.py
- tests/unit/test_gitlab_http_methods.py
A common cause of issues filed and questions raised is that a user
will call a `list()` method and only get 20 items. As this is the
default maximum of items that will be returned from a `list()` method.
To help with this we now emit a warning when the result from a
`list()` method is greater-than or equal to 20 (or the specified
`per_page` value) and the user is not using either `all=True`,
`all=False`, `as_list=False`, or `page=X`.
> feat: emit a warning when using a `list()` method returns max

- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
We've been seeing ChunkedEncodingErrors recently as well, I've added them to the list of retryable exceptions.
```
...
File redacted.py
return typing.cast(GitlabProject, project_manager.get(project_id))
File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 816, in get
return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 311, in wrapped_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 111, in get
server_data = self.gitlab.http_get(path, **kwargs)
File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 761, in http_get
result = self.http_request(
File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line …
```
> Add ChunkedEncodingError to list of retryable exceptions

- gitlab/client.py
Closes https://github.com/python-gitlab/python-gitlab/issues/987.
This was already fixed in https://github.com/python-gitlab/python-gitlab/commit/b9ecc9a8c5d958bd7247946c4e8d29c18163c578 but partially reintroduced with the global `retry_transient_errors` feature.
> fix: avoid passing redundant arguments to API

- .renovaterc.json
We have mostly dev- and typing dependencies getting updated by renovate, and I don't see that much value in getting 3 updates per day for `types-requests` etc. Maybe this will also help people who follow the repo, as they won't be spammed with frequent pushes and PRs.
> chore(renovate): set schedule to reduce noise

- docs/gl_objects/merge_requests.rst
merge request can have state locked
If the merge request is been merged the state is set to locked
> merge request can have state locked

- .github/workflows/test.yml
- tox.ini
Add the `cz` (`comittizen`) check by default.
Set skip_missing_interpreters = True so that when a user runs tox and
doesn't have a specific version of Python it doesn't mark it as an
error.
> chore: add `cz` to default tox environment list and skip_missing_interpreters

- pyproject.toml
The `build/` directory is created by the tox environment
`twine-check`. When the `build/` directory exists `mypy` will have an
error.
> chore: exclude `build/` directory from mypy check

- gitlab/v4/objects/projects.py
This change the repr from:
```
$ gitlab.projects.get(id=some_id)
<Project id:some_id>
```
To:
```
$ gitlab.projects.get(id=some_id)
<Project id:some_id name_with_namespace:"group_name / project_name">
```
This is especially useful when working on random projects or listing of
projects since users generally don't remember projects ids.
----
On a side note I've encountered this error when trying to do a commit:
```
An unexpected error has occurred: CalledProcessError: command: ('/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node', '/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr: …
```
> feat(ux): display project.name_with_namespace on project repr

- CONTRIBUTING.rst
Hello,
The distant file has been modified apparently.
Kind regards,
> doc(CONTRIBUTING.rst): fix link to conventional-changelog commit format documentation

- gitlab/base.py
- gitlab/v4/cli.py
- gitlab/v4/objects/applications.py
- gitlab/v4/objects/commits.py
- gitlab/v4/objects/events.py
- gitlab/v4/objects/files.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/hooks.py
- gitlab/v4/objects/issues.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/merge_request_approvals.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/snippets.py
- gitlab/v4/objects/tags.py
- gitlab/v4/objects/users.py
- gitlab/v4/objects/wikis.py
- tests/unit/test_base.py
This supersedes https://github.com/python-gitlab/python-gitlab/pull/1996 by reusing existing scaffolding we already have for many other objects.
As an aside this should have the added benefit of further decoupling the CLI because we actually use `_repr_attr` in the API itself which was not yet the case with `_short_print_attr` and it was a bit out of place in `base.py` IMO. Now, the CLi simply reuses it.
Note: @Psycojoker this replaces `name_with_namespace` in your PR with `path` because we already had it and it'd otherwise be a breaking change on the CLI. Let me know if you want to override that, otherwise we'll use `with_namespace` in the next major release which I hope we can have soon with some other features. In any case I think the least confusing option would be …
> feat: display human-readable attribute in `repr()` if present

- gitlab/cli.py
The `--job` argument could be interpreted as `--job-token`
Example failure:
$ gitlab \
--private-token ${GITLAB_API_KEY} -o json \
project-artifact download \
--project-id mdm/entities \
--job ${JOB} \
--ref-name ${REF} \
gitlab: error: argument --job-token: not allowed with argument
--private-token
> fix(cli): changed default `allow_abbrev` value to fix arguments collision problem

- docs/api-usage.rst
- docs/gl_objects/issues.rst
Updates to the documentation to include changes on the Gitlab API for `assignee_ids`, and explicitly reference how to extend an object for attributes not explicitly mentioned.
> docs: Update issue example and extend API usage

- .github/workflows/release.yml
Last night's release job failed because `python-semantic-release` parsed a renovate commit as our own version:
https://github.com/relekang/python-semantic-release/issues/442
Rolling back so we can have the release, but I wonder if we should just switch to the JS semantic-release as it only runs in CI and that offers more goodies like PR/issue comments on release to keep people informed when their fix/feature is available. For now let's get this in :)
> chore(ci): pin semantic-release version

- gitlab/mixins.py
- gitlab/utils.py
- tests/unit/test_utils.py
I'm trying to add support for multipart uploads to the generic package upload (see #2002), but unfortunately the logic for that is currently done directly in the `create()`/`update()` methods (processing the `data`/`files` dict for the `MultipartEncoder`).
This extracts that into a helper and handles `transform_files` so we can also use it for `list()` which doesn't need it. This PR preps the code so the generic package one should be smaller.
In the future I think we can simplify multipart encoding more and get rid of `files` altogether, and just process everything in `data` - but wanted to keep this PR simple.
> refactor(mixins): extract custom type transforms into utils

- docs/api-usage.rst
In the "Getting started with the API" section of the documentation,
use either `as_list=False` or `all=True` in the example usages of the
`list()` method.
Also add a warning about the fact that `list()` by default does not
return all items.
> docs: use `as_list=False` or `all=True` in Getting started

- docs/api-usage.rst
- docs/gl_objects/search.rst
- docs/gl_objects/users.rst
- gitlab/client.py
- gitlab/mixins.py
- gitlab/v4/objects/ldap.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/runners.py
- gitlab/v4/objects/users.py
- tests/functional/api/test_gitlab.py
- tests/functional/api/test_projects.py
- tests/unit/mixins/test_mixin_methods.py
- tests/unit/test_gitlab.py
- tests/unit/test_gitlab_http_methods.py
`as_list=False` is confusing as it doesn't explain what is being
returned. Replace it with `iterator=True` which more clearly explains
to the user that an iterator/generator will be returned.
This maintains backward compatibility with `as_list` but does issue a
DeprecationWarning if `as_list` is set.
> feat(client): introduce `iterator=True` and deprecate `as_list=False` in `list()`

- gitlab/cli.py
- gitlab/client.py
- tests/unit/test_gitlab.py
Previously in commit 233b79ed442aac66faf9eb4b0087ea126d6dffc5 I had
used the `name` argument for `ModuleNotFoundError()`. This basically
is the equivalent of not passing any message to
`ModuleNotFoundError()`. So when the exception was raised it wasn't
very helpful.
Correct that and add a unit-test that shows we get the message we
expect.
> chore: correct ModuleNotFoundError() arguments

- gitlab/mixins.py
- gitlab/v4/objects/appearance.py
- gitlab/v4/objects/export_import.py
- gitlab/v4/objects/merge_request_approvals.py
- gitlab/v4/objects/notification_settings.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/push_rules.py
- gitlab/v4/objects/settings.py
- gitlab/v4/objects/statistics.py
- gitlab/v4/objects/users.py
- tests/meta/test_ensure_type_hints.py
Commit f0152dc3cc9a42aa4dc3c0014b4c29381e9b39d6 removed situation
where `get()` in a `GetWithoutIdMixin` based class could return `None`
Update the type-hints to no longer return `Optional` AKA `None`
> chore: update type-hints return signature for GetWithoutIdMixin methods

- gitlab/utils.py
- tests/unit/test_utils.py
There is no reason to return an `int` as we can always return a `str`
version of the `int`
Change `EncodedId` to always return an `EncodedId`. This removes the
need to have `mypy` ignore the error raised.
> chore: have `EncodedId` creation always return `EncodedId`

- gitlab/base.py
- pyproject.toml
We previously converted all string formatting to use f-strings. Enable
pylint check to enforce this.
> chore: require f-strings

- gitlab/v4/cli.py
- pyproject.toml
Enable the 'consider-using-sys-exit' pylint check and fix errors
raised.
> chore: enable 'consider-using-sys-exit' pylint check

- gitlab/v4/cli.py
Less confusing to have it be a normal method.
> chore: rename `__call__()` to `run()` in GitlabCLI

- gitlab/cli.py
- gitlab/v4/cli.py
- tests/unit/test_cli.py
Naming a variable `what` makes it difficult to understand what it is
used for.
Rename it to `gitlab_resource` as that is what is being stored.
The Gitlab documentation talks about them being resources:
https://docs.gitlab.com/ee/api/api_resources.html
This will improve code readability.
> chore: rename `what` to `gitlab_resource`

- gitlab/cli.py
- gitlab/v4/cli.py
- tests/unit/test_cli.py
Rename the variables `whaction` and `action` to `resource_action` to
improve code-readability.
> chore: rename `whaction` and `action` to `resource_action` in CLI

- pyproject.toml
Use multiple processors when running PyLint. On my system it took
about 10.3 seconds to run PyLint before this change. After this change
it takes about 5.8 seconds to run PyLint.
> chore: use multiple processors when running PyLint

- gitlab/v4/cli.py
Make the parser name more user friendly by renaming from generic
"object" to "GitLab resource"
> chore(cli): rename "object" to "GitLab resource"

- docs/api-usage.rst
- docs/ext/manager_tmpl.j2
Turns out the index-based template and related docs have been outdated since https://github.com/python-gitlab/python-gitlab/commit/30117a3b6a8ee24362de798b2fa596a343b8774f and https://github.com/python-gitlab/python-gitlab/commit/147f05d43d302d9a04bc87d957c79ce9e54cdaed.
Also stop pointing to our own custom (non-existent) code and point people to upstream docs, which is the single source of truth.
> docs(ext): fix rendering for RequiredOptional and refer to upstream docs

- gitlab/client.py
A new error was reported when running pylint==2.14.3:
gitlab/client.py:488:0: W1404: Implicit string concatenation found in call (implicit-str-concat)
Fixed this issue.
> chore: fix issue found with pylint==2.14.3

- .github/workflows/lint.yml
Add a link to the Commitizen website in the Github workflow. Hopefully
this will help people when their job fails.
> chore: add link to Commitizen in Github workflow

- docs/conf.py
- setup.cfg
- tox.ini
Closes #1992 by ignoring nitpicky warnings because some will be out of our control anyway (at least without intersphinx).
Drops use of the now-deprecated `build_sphinx` command. One less config file!
> chore(docs): ignore nitpicky warnings, drop deprecated setuptools build_sphinx

- docs/gl_objects/merge_request_approvals.rst
The `set_approvers()` method is on the `ProjectApprovalManager` class.
It is not part of the `ProjectApproval` class.
The docs were previously showing to call `set_approvers` using a
`ProjectApproval` instance, which would fail. Correct the
documentation.
This was pointed out by a question on the Gitter channel.
> docs(api): fix incorrect docs for merge_request_approvals

- docs/api-usage.rst
See https://github.com/psf/requests/issues/6140 for more context.
python-requests.org is not owned by the current maintainers and doesn't seem like it's going to be reliable in the future.
> docs(api): stop linking to python-requests.org

- docs/api-usage.rst
- docs/gl_objects/projects.rst
- gitlab/client.py
- gitlab/exceptions.py
- gitlab/mixins.py
- tests/functional/api/test_projects.py
- tests/functional/api/test_repository.py
- tests/unit/mixins/test_mixin_methods.py
- tests/unit/test_gitlab_http_methods.py
Mainly used for checking file existence and size without actually fetching all the content (see linked issue). I made Gauvain author of the first commit as it's based on https://github.com/python-gitlab/python-gitlab/commit/f404d394960683d68ccaf3c129f75a2582a2fb77.
Closes https://github.com/python-gitlab/python-gitlab/issues/1447
Closes https://github.com/python-gitlab/python-gitlab/issues/682
Related - https://github.com/python-gitlab/python-gitlab/issues/985
> feat(api): support head() method for get and list endpoints

- gitlab/client.py
- gitlab/v4/cli.py
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/merge_request_approvals.py
- gitlab/v4/objects/pipelines.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/services.py
- pyproject.toml
Enable the pylint "unused-argument" check and resolve issues it found.
* Quite a few functions were accepting `**kwargs` but not then
passing them on through to the next level. Now pass `**kwargs` to
next level.
* Other functions had no reason to accept `**kwargs`, so remove it
* And a few other fixes.
> test(pylint): enable pylint "unused-argument" check

- gitlab/mixins.py
- gitlab/utils.py
- gitlab/v4/objects/artifacts.py
- gitlab/v4/objects/files.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/snippets.py
- tests/unit/test_utils.py
Commit b6447211754e126f64e12fc735ad74fe557b7fb4 inadvertently
introduced a possible breaking change as it added a new argument
`iterator` and added it in between existing positional arguments.
Move the `iterator` argument to the end of the argument list and also
require it to be a keyword-only argument.
> fix: iterator possible breaking change

- docs/gl_objects/access_requests.rst
- docs/gl_objects/groups.rst
- docs/gl_objects/notifications.rst
- docs/gl_objects/projects.rst
- docs/gl_objects/protected_branches.rst
- docs/gl_objects/search.rst
- docs/gl_objects/snippets.rst
- gitlab/__init__.py
- gitlab/const.py
- tests/functional/api/test_gitlab.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_projects.py
- tests/unit/objects/test_members.py
- tests/unit/test_gitlab.py
Since we now have enums, we shouldn't tell people to use the plain constants :) also cleans up the use of old constants in tests.
> refactor: do not recommend plain gitlab.const constants

- docs/gl_objects/merge_request_approvals.rst
Some tabs snuck into the documentation. Convert them to 4-spaces.
> chore(docs): convert tabs to spaces

- docs/gl_objects/merge_request_approvals.rst
- gitlab/v4/objects/merge_request_approvals.py
- tests/unit/objects/test_project_merge_request_approvals.py
In GitLab 14.10 they added support to get a single merge request
approval rule [1]
Add support for it to ProjectMergeRequestApprovalRuleManager
[1] https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-a-single-merge-request-level-rule
> feat(api): add support for `get` for a MR approval rule

- gitlab/base.py
- tests/functional/conftest.py
Ensure the path elements that are passed to the server are escaped.
For example a "/" will be changed to "%2F"
Closes: #2116
> fix: ensure path elements are escaped

- tests/functional/api/test_clusters.py
- tests/functional/api/test_current_user.py
- tests/functional/api/test_deploy_keys.py
- tests/functional/api/test_deploy_tokens.py
- tests/functional/api/test_gitlab.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_issues.py
- tests/functional/api/test_merge_requests.py
- tests/functional/api/test_projects.py
- tests/functional/api/test_releases.py
- tests/functional/api/test_repository.py
- tests/functional/api/test_snippets.py
- tests/functional/api/test_users.py
- tests/functional/api/test_variables.py
See https://github.com/python-gitlab/python-gitlab/pull/1784#issuecomment-1172730920.
I've felt a bit weird for a while about having these magic numbers in tests, and they don't really test whether the actual resource created is or isn't in the list. This should hopefully also help with some of the race conditions potentially introduced with async gitlab operations.
I've left a few where it would need some further refactoring (e.g. fixture factories for group/member creation) or where I thought `len()` was still useful. It was already quite tedious so it might be tedious to review, I can split it into multiple commits if needed :)
> test(functional): replace len() calls with list membership checks

- docs/gl_objects/groups.rst
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/push_rules.py
- tests/unit/objects/test_groups.py
Add classes to read and update push rules on groups
Closes #1259.
> #1259 Add GroupPushRules and GroupPushRulesManager classes

- docs/api-usage.rst
- docs/cli-usage.rst
Closes #2122. I was quite blunt about not using password flows here, I think we shouldn't insist on doing this in 2022, so I also removed any usage from the docs.
> docs: describe ROPC flow in place of password authentication

- docs/gl_objects/users.rst
Add docs about listing a user's projects.
Update docs on the membership API to update the URL to the upstream
docs and also add a note that it requires Administrator access to use.
> docs(users): add docs about listing a user's projects

- docs/cli-examples.rst
- docs/gl_objects/ci_lint.rst
- gitlab/exceptions.py
- gitlab/v4/cli.py
- gitlab/v4/objects/ci_lint.py
- tests/conftest.py
- tests/functional/cli/test_cli_v4.py
- tests/unit/objects/test_ci_lint.py
Closes https://github.com/python-gitlab/python-gitlab/issues/546.
There's a bit of duplication because of the inconsistent APIs between global/project endpoints.
> feat: support validating CI lint results

- .github/workflows/test.yml
- CONTRIBUTING.rst
- codecov.yml
- tox.ini
The CLI test is `cli_func_v4` and using `api_func_v4` matches with
that naming convention.
> chore: change name of API functional test to `api_func_v4`

- gitlab/base.py
- gitlab/mixins.py
- tests/unit/mixins/test_mixin_methods.py
This can be used to tell if a `RESTObject` was created using
`lazy=True`.
Add a message to the `AttributeError` if attribute access fails for an
instance created with `lazy=True`.
> chore: add a `lazy` boolean attribute to `RESTObject`

- docs/api-usage-advanced.rst
- docs/api-usage.rst
- docs/cli-examples.rst
- docs/faq.rst
- docs/gl_objects/commits.rst
- docs/gl_objects/groups.rst
- docs/gl_objects/projects.rst
- docs/gl_objects/users.rst
- gitlab/client.py
- gitlab/v4/cli.py
- tests/functional/api/test_gitlab.py
- tests/functional/api/test_repository.py
- tests/functional/api/test_snippets.py
- tests/functional/cli/test_cli_repository.py
- tests/functional/cli/test_cli_v4.py
- tests/functional/ee-test.py
- tests/unit/mixins/test_mixin_methods.py
- tests/unit/test_gitlab.py
- tests/unit/test_gitlab_http_methods.py
When the `all=True` option was originally added, it probably wasn't anticipated that the GitLab API would have the same for parameters, making it unusable in some cases as the library consumes the argument (especially with the CLI). Closes https://github.com/python-gitlab/python-gitlab/issues/751.
This is a follow-up in trying to lower the confusion around `all` params and endpoints (getting rid of the `all()` method was the first step IMO). 
Although currently there is an ugly workaround for this (https://github.com/python-gitlab/python-gitlab/issues/751#issuecomment-698855273), I think it'd be best if we have more explicit arguments that don't clash with GitLab API params. At the same time I didn't want to change this completely as `all=True` is probably the most widely used argument …
> fix: add `get_all` param (and `--get-all`) to allow passing all to API

- tests/functional/api/test_gitlab.py
Catch the deprecation warning for the call to `gl.lint()`, so it won't
show up in the log.
> test(api_func_v4): catch deprecation warning for `gl.lint()`

- tests/functional/conftest.py
- tests/functional/helpers.py
In our fixtures that create:
- groups
- project merge requests
- projects
- users
They delete the created objects after use. Now wait to ensure the
objects are deleted before continuing as having unexpected objects
existing can impact some of our tests.
> chore: fixtures: after delete() wait to verify deleted

- tests/functional/conftest.py
Saw issues in the CI where reset_gitlab() would fail. It would fail to
delete the group that is created when GitLab starts up. Extending the
timeout didn't fix the issue.
Changed the code to use the new `helpers.safe_delete()` function.
Which will delete the resource and then make sure it is deleted before
returning.
Also added some logging functionality that can be seen if logging is
turned on in pytest.
> chore: make reset_gitlab() better

- tox.ini
Users of `podman` will likely have `DOCKER_HOST` set to something like
`unix:///run/user/1000/podman/podman.sock`
Pass this environment variable so that it will be used during the
functional tests.
> test: allow `podman` users to run functional tests

- docs/cli-examples.rst
- docs/gl_objects/runners.rst
- gitlab/client.py
- gitlab/v4/objects/runners.py
- tests/unit/objects/test_runners.py
Makes listing all runners (admin endpoint) possible via the CLI and fixes arguments that were being ignored in `runners.all()` by reusing our standard `list()` from the mixin instead. I haven't deprecated yet to give people time to change before warnings start to emit.
Closes https://github.com/python-gitlab/python-gitlab/issues/593
Replaces https://github.com/python-gitlab/python-gitlab/pull/2115
> fix(runners): fix listing for /runners/all

- docs/gl_objects/projects.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/integrations.py
- gitlab/v4/objects/projects.py
- tests/unit/objects/test_services.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1676.
Keeps services for now as they are still available via the API. Also gives people time to migrate before warnings are emitted.
> refactor: migrate services to integrations

- tests/unit/test_gitlab.py
Use `monkeypatch` to ensure that no config files are reported for the
test.
Closes: #2172
> test: fix broken test if user had config files

- docs/gl_objects/issues.rst
- gitlab/v4/objects/issues.py
- tests/unit/objects/test_issues.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1675.
At some point it might be nice to get rid of the explicit arguments here for the same reason as https://github.com/python-gitlab/python-gitlab/issues/1982.
> feat(issues): add support for issue reorder API

- tests/functional/conftest.py
- tests/functional/fixtures/docker-compose.yml
- tox.ini
Inspired by discussions in https://github.com/python-gitlab/python-gitlab/pull/1778#discussion_r928321056, takes some of the docker stuff back into docker instead of writing to a file and executing it from the host.
> test(functional): simplify token creation

- tests/functional/api/test_groups.py
- tests/functional/conftest.py
- tests/functional/fixtures/.env
- tests/functional/fixtures/create_license.rb
- tests/functional/fixtures/docker-compose.yml
Enable using GitLab Enterprise Edition (EE) in the functional tests.
This will allow us to add tests for EE only features in the
functional tests.
Closes https://github.com/python-gitlab/python-gitlab/issues/1492
> chore: enable using GitLab EE in functional tests

- gitlab/mixins.py
- gitlab/types.py
- gitlab/utils.py
- tests/functional/api/test_groups.py
- tests/unit/mixins/test_mixin_methods.py
- tests/unit/test_types.py
- tests/unit/test_utils.py
1. If a value is of type ArrayAttribute then append '[]' to the name
of the value.
This is step 3 in a series of steps of our goal to add full
support for the GitLab API data types[1]:
* array
* hash
* array of hashes
Step one was: commit 5127b1594c00c7364e9af15e42d2e2f2d909449b
Step two was: commit a57334f1930752c70ea15847a39324fa94042460
Fixes: #1698
Related to https://github.com/python-gitlab/python-gitlab/issues/780
Closes https://github.com/python-gitlab/python-gitlab/issues/806
[1] https://docs.gitlab.com/ee/api/#encoding-api-parameters-of-array-and-hash-types
> fix: use the [] after key names for array variables in `params`

- tests/functional/api/test_merge_requests.py
https://github.com/python-gitlab/python-gitlab/issues/1698 has been
fixed. Add test to show that.
> test: add test to show issue fixed

- gitlab/cli.py
- gitlab/v4/cli.py
- tests/functional/cli/test_cli.py
Add a custom argparse help formatter which overrides output format
for long (over 10 elements) list of choices.
Formatter is derived from argparse.HelpFormatter with minimal necessary
changes.
Closes #456
> feat(cli): add a custom help formatter

- docs/cli-examples.rst
- gitlab/v4/objects/broadcast_messages.py
- gitlab/v4/objects/deploy_tokens.py
- gitlab/v4/objects/environments.py
- gitlab/v4/objects/group_access_tokens.py
- gitlab/v4/objects/invitations.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/members.py
- gitlab/v4/objects/personal_access_tokens.py
- gitlab/v4/objects/project_access_tokens.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/releases.py
- gitlab/v4/objects/statistics.py
- gitlab/v4/objects/users.py
- tests/functional/cli/test_cli_resource_access_tokens.py
- tests/functional/cli/test_cli_users.py
Closes https://github.com/python-gitlab/python-gitlab/issues/780.
I skipped `array of hashes` and I didn't touch some endpoints like merge requests that I think need another look at this topic (merge requests in particular). It's already a chunky PR, so I split it into fix/test/docs commits.
> fix: support array types for most resources

- gitlab/config.py
- tests/meta/test_v4_objects_imported.py
- tests/unit/objects/test_packages.py
- tests/unit/test_config.py
Use `encoding="utf-8"` in `open()` and open-like functions.
https://peps.python.org/pep-0597/
> chore: make code PEP597 compliant

- gitlab/v4/objects/repositories.py
https://docs.gitlab.com/ee/api/repositories.html#get-file-archive
The archive endpoint supports a `path` argument. This change adds support for it.
> Support downloading archive subpaths

- tests/functional/conftest.py
- tests/functional/fixtures/docker-compose.yml
The functional tests have been erratic. Current theory is that we are
starting the tests before the GitLab container is fully up and
running.
* Add checking of the Health Check[1] endpoints.
* Add a 20 second delay after we believe it is up and running.
* Increase timeout from 300 to 400 seconds
[1] https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html
> test: attempt to make functional test startup more reliable

- gitlab/v4/objects/projects.py
Previously `_repr_attr` was `path` but that only gives the basename of
the path.  So https://gitlab.com/gitlab-org/gitlab would only show
"gitlab". Using `path_with_namespace` it will now show
"gitlab-org/gitlab"
> chore: change `_repr_attr` for Project to be `path_with_namespace`

- gitlab/client.py
- tests/unit/test_gitlab.py
To enhance HTTP security our Gitlab is fronted by [IAP](https://cloud.google.com/iap) for example `https://gitlab.tools.domain.io` but for internal communication from runner to Gitlab API we create another endpoint that protected by firewall rules so then it only can be accessed from certain IP only, for example `https://runner.gitlab.tools.domain.io/` it actually using the reverse proxy that in the upstream destination will set `Host` header to the original one (`gitlab.tools.domain.io`). 
But when we run a python script inside Gitlab pipeline to the endpoint (`runner.gitlab.tools.domain.io`) and pass argument `all=True` or `iterator=True` [for loop all the data to all page](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination) will returning the base url as …
> fix: optionally keep user-provided base URL for pagination

- .github/workflows/release.yml
I'd like to push a hotfix for #2219. I checked upstream and https://github.com/relekang/python-semantic-release/issues/442 has been fixed.
I looked at also adding a dry run on `main` - I'd prefer if it was close to the github-action they use, but they don't have a `--no-op` option there. So I need to add that upstream first.
> chore(ci): bump semantic-release for fixed commit parser

- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
Closes #2218 
This provides a small generic fix at the http_request level instead of messing even more with our own flows.
(I've always thought it was a bit weird that GitLab returns a lot of boilerplate query params in ther `next` header links, so I think this will also make other things more robust in the future).
> fix(client): ensure encoded query params are never duplicated 

- gitlab/client.py
Use the `urlunparse()` function to reconstruct the URL without the
query parameters.
> chore: use `urlunparse` instead of string replace

- gitlab/client.py
- tests/functional/cli/test_cli.py
- tests/unit/test_gitlab.py
Closes https://github.com/python-gitlab/python-gitlab/issues/1978.
3 steps here:
* https://github.com/python-gitlab/python-gitlab/commit/7b61ae6a561ca39399e3feedbe9aa2a701ca8a1f removes a hack to handle gitlab's non-standard headers. That was only valid for 13.0 and fixed in 13.1 - super old now and I wouldn't say we're expected to support that.
* https://github.com/python-gitlab/python-gitlab/commit/31c9c2f00f49500de9c74c2eb3f7f06036521755 refactors the nested code out into a slightly more generic helper (that's where it should live anyway, as most of the attributes are from the Gitlab instance)
* https://github.com/python-gitlab/python-gitlab/commit/d71c1dbe349dca044bf9e236c937b2d4d6923d06 adds it to `auth()` so the user gets a warning ASAP.
Other than that I haven't changed any of the …
> feat(client): warn user on misconfigured URL in `auth()`

- AUTHORS
- README.rst
- docs/conf.py
- gitlab/__init__.py
- gitlab/_version.py
- gitlab/base.py
- gitlab/cli.py
- gitlab/client.py
- gitlab/config.py
- gitlab/const.py
- gitlab/exceptions.py
- gitlab/mixins.py
- gitlab/types.py
- gitlab/utils.py
- gitlab/v4/cli.py
- gitlab/v4/objects/__init__.py
- tests/unit/mixins/test_object_mixins_attributes.py
- tests/unit/test_base.py
- tests/unit/test_cli.py
- tests/unit/test_config.py
- tests/unit/test_gitlab.py
- tests/unit/test_types.py
- tests/unit/test_utils.py
First step towards https://github.com/python-gitlab/python-gitlab/issues/658.
Removes license headers from the few remaining source files as they were never applied consistently - plus it's 2022 and no one does that anymore, and we have 200 files in the repo now.
Even https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository has no word on that :)
I added Mika as a significant contributor instead, to have some kind of recognition somewhere other than git history.
This leaves the license duplicated only once, between COPYING and the root `__init__.py`, a bit more reasonable.
> chore: consolidate license and authors

- gitlab/config.py
Change "except Exception:" catching to more granular exceptions.
A step in enabling the "broad-except" check in pylint.
> chore: remove broad Exception catching from `config.py`

- gitlab/client.py
This is mostly relevant for people mocking the API in tests. The real API will always return these.
> fix(client): do not assume user attrs returned for auth()

- tests/functional/api/test_gitlab.py
Make it so can run just the test_gitlab.py functional test.
For example:
$ tox -e api_func_v4 -- -k test_gitlab.py
> chore: fix issue if only run test_gitlab.py func test

- docs/gl_objects/deployments.rst
- gitlab/exceptions.py
- gitlab/v4/objects/deployments.py
- tests/unit/objects/test_deployments.py
Add support for the deployment approval endpoint[1]
[1] https://docs.gitlab.com/ee/api/deployments.html#approve-or-reject-a-blocked-deployment
Closes: #2253
> feat: add support for deployment approval endpoint

- gitlab/v4/objects/merge_requests.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2281. Should have added it to the previous PR but saw too late how similar they were :facepalm: this sorts them following the upstream docs table.
> fix(cli): add missing attributes for creating MRs

- docs/gl_objects/merge_requests.rst
- gitlab/exceptions.py
- gitlab/v4/objects/merge_requests.py
- tests/functional/api/test_merge_requests.py
Added the newly added reset_approvals merge request api.
https://docs.gitlab.com/ee/api/merge_requests.html#reset-approvals-of-a-merge-request
Signed-off-by: Lucas Zampieri <lzampier@redhat.com>
> feat: Add reset_approvals api

- docs/gl_objects/merge_requests.rst
Typo: Author probably meant `mr_iid` (i.e. project-specific MR ID)
and **not** `mr_id` (i.e. server-wide MR ID)
Closes: https://github.com/python-gitlab/python-gitlab/issues/2295
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
> docs(api): Update `merge_requests.rst`: `mr_id` to `mr_iid`

- tests/functional/api/test_lazy_objects.py
- tests/functional/api/test_merge_requests.py
- tests/functional/api/test_users.py
- tests/functional/conftest.py
Simplify usage of `wait_for_sidekiq` by putting the assert if it timed out inside the function rather than after calling it.
> chore: simplify `wait_for_sidekiq` usage

- tests/functional/api/test_merge_requests.py
- tests/functional/cli/test_cli_v4.py
Have been seeing intermittent failures in the test:
tests/functional/api/test_merge_requests.py::test_merge_request_reset_approvals
Also saw a failure in:
tests/functional/cli/test_cli_v4.py::test_accept_request_merge[subprocess]
Add a call to `wait_for_sidekiq()` to hopefully resolve the issues.
> fix: intermittent failure in test_merge_request_reset_approvals

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue_template.md
* Have an option to go to the discussions
* Have an option to go to the Gitter chat
* Move the bug/issue template into the .github/ISSUE_TEMPLATE/ directory
> chore: update the issue templates

- .pre-commit-config.yaml
- CONTRIBUTING.rst
- docs/api-usage-advanced.rst
- docs/api-usage.rst
- docs/cli-usage.rst
- docs/gl_objects/runners.rst
A follow up from #2304
Also, added a rst lint precommit checks
> docs(api): describe the list() and all() runners' functions

- gitlab/v4/objects/notes.py
- tests/functional/ee-test.py
fixes #2234
Corresponding GitLab issue: https://gitlab.com/gitlab-org/gitlab/-/issues/351656 
This PR also fixes the same issue related to epic discussion notes, GitLab API ref: https://docs.gitlab.com/ee/api/discussions.html#epics
> fix: use epic id instead of iid for epic notes

- README.rst
- docs/api-levels.rst
- docs/index.rst
Continuation of #1846 and goes towards #1842.
> docs(api): describe use of lower-level methods

- tests/functional/conftest.py
- tests/functional/fixtures/docker.py
Splitting out the pytest-docker fixtures from conftest.py file. 
At first I was thinking to gather those functions in conftest.py file and adding a starting and closing comment. 
On a second thought, moving those functions to a second fixtures file might make more sense.
> refactor: pytest-docker fixtures

- docs/gl_objects/commits.rst
little problem in the documentation
> docs(commits): fix commit create example for binary content

- docs/gl_objects/merge_request_approvals.rst
- gitlab/v4/objects/merge_request_approvals.py
- pyproject.toml
The `project.approvals.set_approvals()` method used the
`/projects/:id/approvers` end point. That end point was removed from
GitLab in the 13.11 release, on 2-Apr-2021 in commit
27dc2f2fe81249bbdc25f7bd8fe799752aac05e6 via merge commit
e482597a8cf1bae8e27abd6774b684fb90491835. It was deprecated on
19-Aug-2019.
See merge request:
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57473
> fix: remove `project.approvals.set_approvals()` method

- .github/workflows/pre_commit.yml
- tox.ini
The project is using two liniting frameworks: tox and pre-commit.  Each has its own configuration files and a CI workflow. 
The purpose of this PR is to consolidate linting  into one framework: tox
Discussion -  #2321
This PR is a baby step towards a full transition
> refactor: pre-commit triggered from tox

- docs/api-usage.rst
Add some minimal documentation about the `enable_debug()` method.
> docs: add minimal docs about the `enable_debug()` method

- .pre-commit-config.yaml
- docs/api-usage-advanced.rst
- gitlab/client.py
- pyproject.toml
- requirements-lint.txt
- tests/conftest.py
- tests/functional/api/test_import_export.py
- tests/functional/api/test_keys.py
- tests/functional/api/test_merge_requests.py
- tests/functional/api/test_projects.py
- tests/functional/conftest.py
- tests/functional/helpers.py
- tests/meta/test_ensure_type_hints.py
- tests/smoke/test_dists.py
Related to https://github.com/python-gitlab/python-gitlab/issues/2338.
This was going to be the start of adding a bit of pragmatic/non-pedantic typing to tests, not so much to type the test code itself, but to catch typing issues in our own package before it gets to users, and then gradually removing suppressions with fixes.
In the end I think it might do more damage than good to readability and productivity because of the amount of additional boilerplate for `test_*` functions needed for no gain (as some maintainers suggested in https://github.com/pytest-dev/pytest/issues/5981). Maybe with some kind of plugin this can be avoided in an elegant way. It might make sense to at least type fixtures when explicitly used in tests eventually.
But since I started something might as well open a PR …
> chore: add basic typing to functional tests

- docs/gl_objects/merge_requests.rst
- gitlab/v4/objects/merge_requests.py
- tests/functional/api/test_merge_requests.py
- tests/functional/conftest.py
* Call was incorrectly using a `PUT` method when should have used a `POST` method.
* Changed return type to a `dict` as GitLab only returns {'status': 'success'} on success. Since the function didn't work previously, this should not impact anyone.
* Updated the test fixture `merge_request` to add ability to create a pipeline.
* Added functional test for `mr.cancel_merge_when_pipeline_succeeds()`
Fixes: #2349
> fix: `mr.cancel_merge_when_pipeline_succeeds()`

- docs/gl_objects/projects.rst
- gitlab/v4/objects/projects.py
- tests/functional/api/test_import_export.py
- tests/unit/objects/test_project_import_export.py
> feat: add remote import s3

- gitlab/v4/objects/projects.py
Expose `mr_default_target_self` to the CLI.
Example::
gitlab project update --id 616 --mr-default-target-self 1
References:
* https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58093
* https://gitlab.com/gitlab-org/gitlab/-/blob/v13.11.0-ee/doc/user/project/merge_requests/creating_merge_requests.md#new-merge-request-from-a-fork
* https://gitlab.com/gitlab-org/gitlab/-/blob/v14.7.0-ee/doc/api/projects.md#get-single-project
Closes #2360
> fix(cli): expose missing mr_default_target_self project attribute

- docs/gl_objects/projects.rst
- gitlab/v4/objects/projects.py
- tests/unit/objects/test_projects.py
Add the ability to get a project's pull mirror details. This was added in GitLab 15.5 and is a PREMIUM feature.
https://docs.gitlab.com/ee/api/projects.html#get-a-projects-pull-mirror-details
> feat(api): add support for getting a project's pull mirror details

- .github/workflows/lint.yml
Use https://github.com/PyCQA/pylint as the website for pylint.
> chore: correct website for pylint

- docs/gl_objects/groups.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/2372 (at least the gitlab.com aspect of it, otherwise nothing to do from our side)
> docs(groups): describe GitLab.com group creation limitation

- docs/gl_objects/secure_files.rst
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/secure_files.py
- tests/unit/objects/test_secure_files.py
This builds on https://github.com/python-gitlab/python-gitlab/pull/2370. During review I suggested `secure_files` instead of `project_secure_files` for the attribute, but I think we maybe went a bit too far, so this is just in case we get `GroupSecureFile` functionality in the future. This way we don't need breaking changes in the future. Using `refactor` as we have no release yet so no need for changelog entry.
> refactor: explicitly use ProjectSecureFile

- docs/gl_objects/groups.rst
- gitlab/v4/objects/groups.py
- tests/functional/api/test_groups.py
- tests/unit/objects/test_groups.py
This builds on https://github.com/python-gitlab/python-gitlab/pull/2371.
I realized https://github.com/python-gitlab/python-gitlab/pull/1612 already did something similar and the `list()` `create()` `delete()` interface is more intuitive for the user.
Additionally, https://github.com/python-gitlab/python-gitlab/pull/2367 will bring in a similar interface for SAML.
And finally, the delete endpoints used in the current method are actually deprecated upstream, so good to move away from that on our side
https://docs.gitlab.com/ee/api/groups.html#delete-ldap-group-link (deprecated)
https://docs.gitlab.com/ee/api/groups.html#delete-ldap-group-link-with-cn-or-filter (new endpoint)
> feat(groups): add LDAP link manager and deprecate old API endpoints

- docs/gl_objects/pipelines_and_jobs.rst
The GitLab docs refer to it as a log file:
https://docs.gitlab.com/ee/api/jobs.html#get-a-log-file
"trace" is the endpoint name but not a common term people will think of for a "log file"
> docs: Use the term "log file" for getting a job log file

- tests/functional/api/test_merge_requests.py
This is an attempt to fix the flaky test
`test_cancel_merge_when_pipeline_succeeds`.
Were seeing a: 405 Method Not Allowed error when setting the MR to
merge_when_pipeline_succeeds.
Closes: #2383
> test(api): fix flaky test `test_cancel_merge_when_pipeline_succeeds`

- gitlab/cli.py
Authentication issues are currently hard to debug since `--debug` only has effect after `gl.auth()` has been called.
For example, a 401 error is printed without any details about the actual HTTP request being sent:
$ gitlab --debug --server-url https://gitlab.com current-user get
401: 401 Unauthorized
By moving the call to `gl.enable_debug()` the usual debug logs get printed before the final error message.
> fix(cli): Enable debug before doing auth

- gitlab/v4/objects/releases.py
For the Release API Endpoint `description` is not a required attribute, see https://docs.gitlab.com/14.10/ee/api/releases/#create-a-release
> fix(api): Make description optional for releases

- gitlab/v4/objects/projects.py
The Project object was previously using the GroupIterationManager resulting in the incorrect API endpoint being used. Utilize the correct ProjectIterationManager instead.
Resolves #2403
> fix: Use the ProjectIterationManager within the Project object

- gitlab/config.py
Hello,
For the context, I'm creating myself a little tool to automate some things with our Gitlab instance. This instance has some "misconfiguration": it advertise a different domain name than the one we use to access it.
When developing my tool I used a gitlab token exposed as environment variable to authenticate to gitlab with the [gitlab.Gitlab class](https://python-gitlab.readthedocs.io/en/stable/api-usage.html#gitlab-gitlab-class) like this:
```python
gitlab.Gitlab(os.environ["GITLAB_URL"], os.environ["GITLAB_TOKEN"], keep_base_url=True)
```
As I said in the context section, our gitlab instance has some "misconfiguration" and I kept being warned about this by python-gitlab. I wanted to remove this so I used the `keep_base_url` flag as suggested by the warning.
When installing my tool …
> feat: add keep_base_url when getting configuration from file

- docs/api-usage-advanced.rst
- gitlab/client.py
- tests/functional/api/test_gitlab.py
- tests/unit/test_gitlab.py
This PR is needed for the validation of #2391
> feat: allow passing kwargs to Gitlab class when instantiating with `from_config`

- setup.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2263
> fix(deps): bump requests-toolbelt to fix deprecation warning

- gitlab/v4/cli.py
It is quite similar to issue #1425 , even though getattr call already provides default value.
It fixed following error:
```
gitlab -c gitlab.cfg user-event list --user-id 292
target_title: iozone
Traceback (most recent call last):
File "~/miniforge3/bin/gitlab", line 8, in <module>
sys.exit(main())
File "~/miniforge3/lib/python3.9/site-packages/gitlab/cli.py", line 376, in main
gitlab.v4.cli.run(
File "~/miniforge3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 549, in run
printer.display_list(data, fields, verbose=verbose)
File "~/miniforge3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 512, in display_list
self.display(get_dict(obj, fields), verbose=verbose, obj=obj)
File "~/miniforge3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 494, in display
value = …
```
> fix: change return value to "None" in case getattr returns None

- docs/api-usage-advanced.rst
- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
> feat(client): automatically retry on HTTP 409 Resource lock

- .github/workflows/test.yml
There are cases where unit tests are failing for a specific python version but not for all
> ci: Complete all unit tests even if one has failed

- tox.ini
tox > 4 no longer will re-use the tox directory :(  What this means is that with the previous config if you ran:
$ tox -e mypy; tox -e isort; tox -e mypy
It would recreate the tox environment each time :(
By removing the `envdir` values it will have the tox environments in separate directories and not recreate them.
The have an FAQ entry about this:
https://tox.wiki/en/latest/upgrading.html#re-use-of-environments
> chore: remove tox `envdir` values

- docs/api-usage.rst
- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
This fix a regression introduced on commit
https://github.com/python-gitlab/python-gitlab/commit/1339d645ce58a2e1198b898b9549ba5917b1ff12
(cc @JohnVillalovos)
If page is used, then get_next should be false.
This was found on the mesa ci project, after upgrading the python-gitlab version, the script that monitors the ci was getting killed by consuming too much memory.
> fix(client): regression - do not automatically get_next if page=# and iterator=True/as_list=False are used

- gitlab/client.py
- tests/unit/test_gitlab_http_methods.py
If a caller calls a `list()` method with both `iterator=True` (or `as_list=False`) and `page=X` then emit a `UserWarning` as the options are mutually exclusive.
> chore: add a UserWarning if both `iterator=True` and `page=X` are used

- gitlab/v4/objects/branches.py
For the CLI: add `allow_force_push` as an optional argument for creating a protected branch.
API reference:
https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches
Closes: #2466
> feat(cli): add setting of `allow_force_push` for protected branch

- .github/workflows/test.yml
Add a unit test for Python 3.12. This will use the latest version of Python 3.12 that is available from
https://github.com/actions/python-versions/
At this time it is 3.12.0-alpha.4 but will move forward over time until the final 3.12 release and updates. So 3.12.0, 3.12.1, ... will be matched.
> chore: add Python 3.12 testing

- docs/api-levels.rst
- gitlab/client.py
- pyproject.toml
- tests/unit/test_gitlab_http_methods.py
In order to support some new API calls we need to support the HTTP `PATCH` method.
Closes: #2469
> feat(client): add `http_patch` method

- tox.ini
For users who use `tox` having `pre-commit` as part of the default
environment list is redundant as it will run the same tests again that
are being run in other environments. For example: black, flake8,
pylint, and more.
> chore: remove `pre-commit` as a default `tox` environment

- docs/api-usage-advanced.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/2460
> docs(advanced): fix typo in Gitlab examples

- gitlab/exceptions.py
- requirements-lint.txt
- tests/functional/conftest.py
- tests/unit/objects/test_statistics.py
Update the dependency versions:
black: 23.1.0
commitizen: 2.40.0
They needed to be updated together as just updating `black` caused a dependency conflict.
Updated files by running `black` and committing the changes.
> chore(deps): update black (23.1.0) and commitizen (2.40.0)

- gitlab/v4/cli.py
- tests/functional/api/test_merge_requests.py
- tests/functional/cli/test_cli_repository.py
- tests/functional/conftest.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2448.
Separately, fce790328df81ac61679f40c0142d70e58049703 renames the fixture factory as is done in https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#factories-as-fixtures and adds a fixture that can be reused directly in tests.
> fix(cli): display items when iterator is returned

- .renovaterc.json
Seems like renovate at some point added default ignore paths which included `tests/` so this explicitly sets a narrower array. Also aligns the regex to be more like other renovate paths upstream.
> chore(renovate): do not ignore tests dir

- docs/gl_objects/badges.rst
docs: fix update badge behaviour
Earlier:
badge.image_link = new_link
Now:
badge.image_url = new_image_url
badge.link_url = new_link_url
Fixes #2485
> docs: fix update badge behaviour

- gitlab/_backends/protocol.py
- gitlab/_backends/requests_backend.py
The purpose of this change is to track [api](https://github.com/python-gitlab/python-gitlab/blob/main/docs/api-levels.rst) changes. For example: package versioning and breaking change announcement in case of protocol change.
This is MVP implementation to be used by #2435 
Haven't figured out yet how to implement unit tests for a protocol and its value.
> feat(backends): use PEP544 protocols for structural subtyping

- docs/cli-usage.rst
- gitlab/cli.py
- tests/functional/cli/test_cli_v4.py
> fix(cli): add ability to escape at-prefixed parameter

- gitlab/_backends/requests_backend.py
- gitlab/client.py
- gitlab/v4/objects/groups.py
- tests/unit/_backends/test_requests_backend.py
This will also fix other use cases where an integer is passed in to
MultipartEncoder.
Added unit tests to show it works.
Closes: #2506
> fix: support int for `parent_id` in `import_group`

- CODE_OF_CONDUCT.md
See https://www.contributor-covenant.org/
Instead of crafting our own I just copy/pasted [v2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
I only changed the contact placeholder in Enforcement to add GitHub's report content functionality, which I also just enabled (`Repository admins accept content reports`):
> chore: add Contributor Covenant 2.1 as Code of Conduct

- docs/gl_objects/pipelines_and_jobs.rst
Closes https://github.com/python-gitlab/python-gitlab/issues/2519
> docs(objects): fix typo in pipeline schedules

- codecov.yml
This has been annoying me - with the new integration, we get annotations and status checks, but they seem to get notified early, so CI looks like it's failing until all coverage reports are fully uploaded.
https://docs.codecov.com/docs/codecovyml-reference
> chore(ci): wait for all coverage reports in CI status

- gitlab/v4/objects/merge_request_approvals.py
This can be used instead of 'user_ids'
See: https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule
> feat: usernames support for MR approvals

- .github/workflows/release.yml
- requirements-test.txt
Closes #2554 
Tested on test.pypi.org, I've removed the static PYPI_TOKEN already. We can also remove the deploy token member now IMO
> chore(ci): use OIDC trusted publishing for pypi.org

- gitlab/v4/objects/events.py
Add support for the `scope` parameter in api: "/events?scope=all" that is implemented by https://gitlab.com/gitlab-org/gitlab/-/merge_requests/19816
ex: retrieve all dashboard activity for a given user:
```py
i_t = user.impersonationtokens.create({"name": token_name, 'scopes': ["api"]})
user_gl = gitlab.Gitlab(<url>, private_token=i_t.token)
events = user_gl.events.list(scope="all")
i_t.delete()
```
No other params are documented more than the method signature. So automodule should generate it.
> feat(api): add support for events scope parameter

- gitlab/v4/objects/packages.py
- tests/functional/api/test_packages.py
Add ability to use `select="package_file"` when uploading a generic package as described in:
https://docs.gitlab.com/ee/user/packages/generic_packages/index.html
Closes: #2557
> feat: add support for `select="package_file"` in package upload

- gitlab/v4/objects/files.py
This should be an instant merge
You can see the documentation creating wrong variables here: https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ProjectFileManager.raw
> docs(files): fix minor typo in variable declaration

- .github/workflows/test.yml
- .renovaterc.json
- README.rst
- setup.py
- tox.ini
Python 3.8 is End-of-Life (EOL) as of 2023-06-27 as stated in https://devguide.python.org/versions/ and
https://peps.python.org/pep-0537/
By dropping support for Python 3.7 and requiring Python 3.8 or higher it allows python-gitlab to take advantage of new features in Python 3.8, which are documented at:
https://docs.python.org/3/whatsnew/3.8.html
BREAKING CHANGE: As of python-gitlab 4.0.0, Python 3.7 is no longer
supported. Python 3.8 or higher is required.
> feat: remove support for Python 3.7, require 3.8 or higher

- gitlab/v4/objects/releases.py
This commit adds support for the “new” alias for `filepath`: `direct_asset_path` (added in 15.10) in release links API.
> feat(releases): Add support for direct_asset_path

- docs/faq.rst
- gitlab/v4/cli.py
- gitlab/v4/objects/commits.py
- tests/functional/cli/test_cli_repository.py
BREAKING CHANGE: The `--all` option is no longer available in the CLI. Use `--get-all` instead.
Closes https://github.com/python-gitlab/python-gitlab/issues/2535
> fix(cli): remove deprecated `--all` option in favor of `--get-all`

- gitlab/v4/objects/projects.py
- tests/unit/objects/test_projects.py
BREAKING CHANGE: The deprecated `project.transfer_project()` method is no longer available. Use `project.transfer()` instead.
> refactor(projects): remove deprecated `project.transfer_project()` in favor of `project.transfer()`

- gitlab/v4/objects/groups.py
BREAKING CHANGE: The deprecated `group.add_ldap_group_link()` and `group.delete_ldap_group_link()` methods are no longer available. Use `group.ldap_group_links.create()` and `group.ldap_group_links.delete()` instead.
> refactor(groups): remove deprecated LDAP group link add/delete methods

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/artifacts.py
- tests/functional/cli/test_cli_artifacts.py
- tests/unit/objects/test_job_artifacts.py
BREAKING CHANGE: The deprecated `project.artifacts()` method is no longer available. Use `project.artifacts.download()` instead.
> refactor(artifacts): remove deprecated `artifacts()`in favor of `artifacts.download()`

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/projects.py
- tests/functional/cli/test_cli_artifacts.py
- tests/unit/objects/test_projects.py
BREAKING CHANGE: The deprecated `project.artifact()` method is no longer available. Use `project.artifacts.raw()` instead.
> refactor(artifacts): remove deprecated `artifact()`in favor of `artifacts.raw()`

- gitlab/client.py
- tests/functional/api/test_gitlab.py
BREAKING CHANGE: The deprecated `lint()` method is no longer available. Use `ci_lint.create()` instead.
> refactor(lint): remove deprecated `lint()` in favor of `ci_lint.create()`

- gitlab/client.py
- tests/functional/api/test_gitlab.py
- tests/unit/test_gitlab_http_methods.py
In `list()` calls support for the `as_list` argument has been removed.
`as_list` was previously deprecated and now the use of `iterator` will
be required if wanting to have same functionality as using `as_list`
BREAKING CHANGE: Support for the deprecated `as_list` argument in
`list()` calls has been removed. Use `iterator` instead.
> refactor(list): `as_list` support is removed.

- docs/gl_objects/runners.rst
- docs/gl_objects/users.rst
- gitlab/v4/objects/users.py
- tests/unit/conftest.py
- tests/unit/objects/test_users.py
This PR adds support for GitLab's new runner creation API `POST /user/runners`.
Closes #2606
> feat(api): Add support for new runner creation API

- docs/gl_objects/runners.rst
New linting package update detected the issue.
> docs: correct error with back-ticks

- docs/gl_objects/remote_mirrors.rst
- gitlab/v4/objects/projects.py
- tests/functional/api/test_projects.py
- tests/unit/objects/test_remote_mirrors.py
Adding support for project remote mirror deletion
> feat(api): support project remote mirror deletion

- gitlab/client.py
- gitlab/const.py
- tests/unit/test_gitlab_http_methods.py
Needed for https://docs.gitlab.com/ee/api/project_job_token_scopes.html#patch-a-projects-cicd-job-token-access-settings
> fix(client): support empty 204 responses in http_patch

- gitlab/cli.py
- tests/functional/cli/test_cli.py
display --help actions correctly when there are few actions.
fix #2656
> fix(cli): fix action display in --help when there are few actions

- docs/api-usage-advanced.rst
- gitlab/_backends/__init__.py
- gitlab/_backends/requests_backend.py
- gitlab/client.py
- tests/unit/test_gitlab_auth.py
Use Private / Job / OAuth token auth classes based on requests' `AuthBase` class to provide an encapsulated mechanism for passing authentication credentials.
Additionally this helps with #2425 since we always pass the `auth` argument, so unless hitting redirects requests should always prefer the passed token over netrc credentials.
This does however break the behavior when credentials are set using environment variables and a user wants to set `netrc` to override that (username / password should be discouraged, but users have better ideas...), for example, running in the CI the `CI_JOB_TOKEN` is set it will prevent the netrc creds from being loaded, instead of the old API logic (as can seen in the tests changes)
This changes internal implementation by leveraging standard `requests` …
> feat(client): Use requests AuthBase classes

- gitlab/v4/cli.py
- gitlab/v4/objects/users.py
- tests/functional/cli/test_cli_users.py
setting `_from_parent_attrs` on `UserProjectManager` and using it in its `list` method resolves #2558 and allows specific user's projects to be returned successfully. 
The inspiration for the fix came from `_from_parent_attrs = {"user_id": "id"}` line of `UserProjectManager`.
Tested by running below script with arguments: `user-project list --user-id [user_id]`
```
import gitlab
gl = gitlab.GitLab(...)
gl.auth()
import gitlab.cli as cli
cli.main()
```
> fix(cli): add _from_parent_attrs to user-project manager (#2558)

- gitlab/_backends/requests_backend.py
- gitlab/client.py
- gitlab/v4/objects/packages.py
- tests/functional/api/test_packages.py
- tests/unit/objects/test_packages.py
This commit adds a keyword argument to GenericPackageManager.upload() to allow uploading bytes and file-like objects to the generic package registry. That necessitates changing file path to be a keyword argument as well, which then cascades into a whole slew of checks to not allow passing both and to not allow uploading file-like objects as JSON data.
Closes https://github.com/python-gitlab/python-gitlab/issues/1815
> feat: Allow uploading packages from files and bytes

- docs/gl_objects/packages.rst
- gitlab/v4/objects/packages.py
- tests/unit/objects/test_packages.py
**Warning: This PR is in Draft status, and is pending [the inclusion of ProjectPackagePipelines](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117539) in GitLab 16.0.** Tests and documentation modifications are required before merging.
Add ProjectPackagePipeline, a new API endpoint which is [expected to be included](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117539) in GitLab 16.0.
> Draft: Add ProjectPackagePipeline

- .github/workflows/release.yml
- pyproject.toml
Fixes failure in https://github.com/python-gitlab/python-gitlab/actions/runs/6530439704/job/17729726207.
python-semantic-release uses a very similar config:
https://github.com/python-semantic-release/python-semantic-release/blob/master/pyproject.toml#L329-L331
> chore(ci): update release build for python-semantic-release v8

- .gitlab-ci.yml
- Dockerfile
Adds the [OCI source label](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) to the container image so that downstream tools know where the image comes from. This is for example used by Renovate Bot to fetch the changelog.
> chore: add source label to container image

- docs/gl_objects/users.rst
The examples which show usage of new runner registration api endpoint are missing commas. This change adds the missing commas.
Fix examples in v4 runner registration API docs.
> docs(users): add missing comma in v4 API create runner examples

- .github/workflows/lock.yml
- .pre-commit-config.yaml
- docs/gl_objects/wikis.rst
- gitlab/mixins.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/wikis.py
- requirements-lint.txt
- requirements-test.txt
- tests/functional/api/test_wikis.py
- tests/unit/mixins/test_mixin_methods.py
- tests/unit/objects/test_projects.py
UploadMixin added, inherits from RESTObject;
UploadMixin used in projects.py and wikis.py to upload files; 
Test for upload to wiki api added in tests/functional/api/test_wikis.
Documentation and unit tests not yet added - waiting for corrections/objections 
> feat(api): add support for wiki attachments

- gitlab/const.py
https://docs.gitlab.com/ee/api/pipelines.html
Would be nice to extend the [ProjectPipeline object](https://python-gitlab.readthedocs.io/en/stable/api/gitlab.v4.html#gitlab.v4.objects.ProjectPipeline) with an api to get the status that returns this, but 100% how do that.
> feat: add pipeline status as Enum

- docs/api-objects.rst
- docs/gl_objects/draft_notes.rst
- gitlab/client.py
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/draft_notes.py
- gitlab/v4/objects/merge_requests.py
- tests/unit/objects/test_draft_notes.py
- tests/unit/test_gitlab_http_methods.py
See https://docs.gitlab.com/ee/api/draft_notes.html
Not returning anything in the publish methods as we only get a 204 from gitlab, see below:
https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/api/draft_notes.rb#L215-261
> feat(api): add support for the Draft notes API

- CONTRIBUTING.rst
> docs: fix rst link typo in CONTRIBUTING.rst

- gitlab/cli.py
- tests/unit/test_cli.py
Add a `--no-ssl-verify` option to disable SSL verification
Closes: #2714
> fix(cli): add ability to disable SSL verification

- .github/workflows/test.yml
Add a job to test the development versions of Python 3.13.
> chore(ci): add Python 3.13 development CI job

- docs/gl_objects/group_access_tokens.rst
- docs/gl_objects/personal_access_tokens.rst
- docs/gl_objects/project_access_tokens.rst
- gitlab/v4/objects/group_access_tokens.py
- gitlab/v4/objects/project_access_tokens.py
- tests/unit/objects/conftest.py
- tests/unit/objects/test_group_access_tokens.py
- tests/unit/objects/test_project_access_tokens.py
Adds the single GET endpoints for group and project tokens. Cherrypicked from #2756 to reduce the diff.
> feat(api): support single resource access token get API

- gitlab/cli.py
- tests/functional/cli/test_cli_v4.py
- tests/unit/test_cli.py
Support binary files being used in the CLI with arguments using the
`@` notation. For example `--avatar @/path/to/avatar.png`
Also explicitly catch the common FileNotFoundError and PermissionError
exceptions.
Remove the bare exception handling. We would rather have the full
traceback of any exceptions that we don't know about and add them
later if needed.
Closes: #2752
> fix(cli): support binary files with `@` notation

- docs/gl_objects/group_access_tokens.rst
- docs/gl_objects/personal_access_tokens.rst
- docs/gl_objects/project_access_tokens.rst
- gitlab/exceptions.py
- gitlab/mixins.py
- gitlab/v4/objects/group_access_tokens.py
- gitlab/v4/objects/personal_access_tokens.py
- gitlab/v4/objects/project_access_tokens.py
- tests/unit/objects/conftest.py
- tests/unit/objects/test_group_access_tokens.py
- tests/unit/objects/test_personal_access_tokens.py
- tests/unit/objects/test_project_access_tokens.py
Adds a `RotateMixin` and `ObjectRotateMixin` similar to the delete mixins.
Closes https://github.com/python-gitlab/python-gitlab/issues/2589
Closes https://github.com/python-gitlab/python-gitlab/issues/2746
> feat(api): support access token rotate API

- gitlab/v4/cli.py
- tests/unit/test_cli.py
The CLI takes its arguments from the RequiredOptional, which has three fields: required, optional, and exclusive. In practice, the exclusive options are not defined as either required or optional, and would not be allowed in the CLI. This changes that, so that exclusive options are also added to the argument parser.
Closes #2769
> fix(cli): allow exclusive arguments as optional

- gitlab/v4/objects/jobs.py
When `.play()`ing a `ProjectJob`, its status would not be updated from `manual` to `pending`/`running`/etc.
Fix this by updating the object with the data returned by the api.
> fix(api): update manual job status when playing it

- gitlab/utils.py
- tests/functional/api/test_gitlab.py
- tests/unit/test_gitlab_http_methods.py
Previously would only go to the 2nd level of the stack for determining the offending filename and line number. When it should be showing the first filename outside of the python-gitlab source code. As we want it to show the warning for the user of the libraries code.
Update test to show it works as expected.
This is sort of related to #2799
> fix: user.warn() to show correct filename of issue

- CONTRIBUTING.rst
- tox.ini
tox now has a feature of `labels` which allows running groups of
environments using the command `tox -m LABEL_NAME`. For example
`tox -m lint` which has been setup to run the linters.
Bumped the minimum required version of tox to be 4.0, which was
released over a year ago.
> chore: add tox `labels` to enable running groups of environments

- .pre-commit-config.yaml
- gitlab/utils.py
- requirements-lint.txt
mypy 1.9.0 flagged one issue in the code. Resolve the issue. Current unit tests already check that a `None` value returns `text/plain`. So function is still working as expected.
> chore: update `mypy` to 1.9.0 and resolve one issue

- README.rst
Ref: #2823
Improves the main `README` to give an example as to how to use the Docker image within GitLab CI..
Discussion: https://github.com/python-gitlab/python-gitlab/discussions/2822
Issue: https://github.com/python-gitlab/python-gitlab/issues/2823
> docs: Note how to use the Docker image from within GitLab CI

- docs/gl_objects/personal_access_tokens.rst
Rotate token returns a dict. Change example to print the entire dict.
Closes: #2836
> docs: correct rotate token example

- Dockerfile
This would not leave cache files in the built docker image.
Additionally, also only build the wheel in the build phase.
On my machine, before this PR, size is 74845395; after this PR, size is
72617713.
> build: Add "--no-cache-dir" to pip commands in Dockerfile

- tests/smoke/test_dists.py
Something changed in setuptools so they normalize both sdist and wheel names, https://github.com/pypa/setuptools/issues/3593
This is causing all our smoke test builds to fail atm
> test(smoke): normalize all dist titles for smoke tests

- gitlab/v4/objects/merge_request_approvals.py
- tests/unit/objects/test_project_merge_request_approvals.py
Closes #2548
This seems to work when testing against a GitLab Ultimate test project. I assume that the integration tests run against a Gitlab CE instance, so adding a test for this is not feasible. I am not very sure of the changes I made, but it does seem to work correctly.
Remove custom code and correctly set identifiers for merge request approvals.
> fix(api): fix saving merge request approval rules

- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_jobs.py
- tests/unit/objects/test_resource_groups.py
List query params like 'scope' were not being handled correctly. This change ensures multiple values are appended with '[]', resulting in the correct URL structure.
---
Background:
If one queries for pipeline jobs with `scope=["failed", "success"]`
One gets:
```
GET /api/v4/projects/176/pipelines/1113028/jobs?scope=success&scope=failed
```
But it is supposed to get:
```
GET /api/v4/projects/176/pipelines/1113028/jobs?scope[]=success&scope[]=failed
```
The current version only considers the last element of the list argument.
> fix: Consider scope an ArrayAttribute in PipelineJobManager

- docs/gl_objects/job_token_scope.rst
- gitlab/v4/objects/job_token_scope.py
- tests/functional/api/test_project_job_token_scope.py
- tests/unit/objects/test_job_token_scope.py
Builds ontop of: https://github.com/python-gitlab/python-gitlab/pull/2767 and https://github.com/python-gitlab/python-gitlab/pull/2790
Closes #2762 
Adds support for adding Group to job_token_allowlist: https://docs.gitlab.com/ee/api/project_job_token_scopes.html#add-a-group-to-a-cicd-job-token-allowlist
> feat(job_token_scope): support Groups in job token allowlist API 

- gitlab/v4/objects/merge_request_approvals.py
I don't think commit a2b8c8ccfb5d went far enough to enable usernames support. We create and edit a lot of approval rules based on an external service (similar to CODE_OWNERS), but only have the usernames available, and currently, have to look up each user to get their user ID to populate user_ids for .set_approvers() calls. Would very much like to skip the lookup and just send the usernames, which this change should allow.
See: https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule
- Add a new approver_usernames argument to .set_approvers()
- Pass new arg to GitLab as a list of usernames via their usernames arg
This is not yet tested or documented, wanted to make sure I was on the right track first.
> feat(api): more usernames support for MR approvals

- gitlab/v4/objects/projects.py
Official documentations for the 'import_project' API use a file object.
```python
with open('/tmp/export.tgz', 'rb') as f:
output = gl.projects.import_project(
f, path='my_new_project', name='My New Project'
)
```
However the `import_project` file argument is declared as `str`, breaking Python typings checks.
```bash
src/features/gitlab.py:344: error: Argument 1 to "import_project" of                        
"ProjectManager" has incompatible type "BufferedReader"; expected "str"                                                                                                                 
[arg-type]
file,
^~~~
Found 1 error in 1 file (checked 22 source files)
```
- Detected over `gitlab-projects-migrate` : https://gitlab.com/AdrianDC/gitlab-projects-migrate/-/jobs/6873996382
> fix(projects): fix 'import_project' file argument type for typings

- gitlab/v4/objects/merge_request_approvals.py
Use `iterator=True` when going through the list of current approval rules. This allows it to handle more than the default of 20 approval rules.
Closes: #2825
> fix: handle large number of approval rules

- gitlab/v4/objects/jobs.py
> chore: correct type-hint for `job.trace()`

- gitlab/v4/cli.py
Add help for the following standard operations:
* list: List the GitLab resources
* get: Get a GitLab resource
* create: Create a GitLab resource
* update: Update a GitLab resource
* delete: Delete a GitLab resource
For example:
```
$ gitlab project-key --help
usage: gitlab project-key [-h] {list,get,create,update,delete,enable} ...
options:
-h, --help            show this help message and exit
action:
list
get
create
update
delete
enable
Action to execute on the GitLab resource.
list                List the GitLab resources
get                 Get a GitLab resource
create              Create a GitLab resource
update              Update a GitLab resource
delete              Delete a GitLab resource
```
> chore(cli): add some simple help for the standard operations

- gitlab/cli.py
- gitlab/v4/cli.py
- tests/functional/cli/test_cli.py
This makes it easier for people to map CLI command names to the API.
Looks like this:
```
$ gitlab --help
<snip>
The GitLab resource to manipulate.
application         API endpoint: /applications
application-appearance
API endpoint: /application/appearance
application-settings
API endpoint: /application/settings
application-statistics
API endpoint: /application/statistics
<snip>
```
> chore(cli): on the CLI help show the API endpoint of resources

- gitlab/client.py
Aims to fix the issue described in:
https://github.com/python-gitlab/python-gitlab/issues/2876
> fix: don't raise `RedirectError` for redirected `HEAD` requests

- requirements.txt
We no longer support Python versions before 3.8. So it isn't needed anymore.
> chore: remove typing-extensions from requirements.txt

- docs/gl_objects/iterations.rst
- gitlab/v4/objects/iterations.py
Relates to https://github.com/python-gitlab/python-gitlab/issues/2795
Added "in" parameter to define where te search should be performed in a iteration list.
> feat(api):  add additional parameter to project/group iteration search

- gitlab/cli.py
This gives the ability to not mask credentials when using the
`--debug` argument.
> feat: add `--no-mask-credentials` CLI argument

- gitlab/cli.py
- gitlab/v4/cli.py
- gitlab/v4/objects/deploy_keys.py
- tests/functional/cli/test_cli.py
Now when registering a custom_action can add help text if desired.
Also delete the VerticalHelpFormatter as no longer needed. When the
help value is set to `None` or some other value, the actions will get
printed vertically. Before when the help value was not set the actions
would all get put onto one line.
Add some help text for `gitlab project-key enable`. This both adds
help text and shows how to use the new `help` feature.
Example:
```
$ gitlab project-key --help
usage: gitlab project-key [-h] {list,get,create,update,delete,enable} ...
options:
-h, --help            show this help message and exit
action:
{list,get,create,update,delete,enable}
Action to execute on the GitLab resource.
list                List the GitLab resources
get                 Get a GitLab resource
create …
```
> chore: add ability to set help for custom_actions. Also add help to the `project-key` action

- docs/gl_objects/pipelines_and_jobs.rst
- gitlab/v4/objects/pipelines.py
- tests/unit/objects/test_pipelines.py
Add support for https://docs.gitlab.com/ee/api/pipelines.html#get-the-latest-pipeline
> Feat(api): Add support for latest pipeline

- gitlab/v4/objects/commits.py
- tests/unit/objects/test_commits.py
This implements ["Get the sequence of a commit"](https://docs.gitlab.com/ee/api/commits.html#get-the-sequence-of-a-commit), [introduced](https://gitlab.com/gitlab-org/gitlab/-/issues/438151) in GitLab 16.9.
> feat(api): add support for commit sequence

- gitlab/cli.py
- gitlab/client.py
- gitlab/utils.py
- gitlab/v4/cli.py
- tests/unit/test_utils.py
Previously in the CLI, calls to `list()` would have `get_all=False` by
default. Therefore hiding the fact that not all items are being
returned if there were more than 20 items.
Added `--no-get-all` option to `list` actions. Along with the already
existing `--get-all`.
Closes: #2900
> fix(cli): generate UserWarning if `list` does not return all entries

- gitlab/v4/objects/files.py
- tests/functional/api/test_repository.py
The `ref` parameter for the raw file API was made optional in GitLab v13.11.0.
- Make the `ref` parameter for the corresponding method on `ProjectFileManager` optional to match the API.
- Minor changes to the docstring for this method.
> fix(files): make `ref` parameter optional in get raw file API

- gitlab/mixins.py
- gitlab/v4/objects/issues.py
- tests/functional/api/test_issues.py
- tests/functional/api/test_merge_requests.py
Previously it was using `http_get()` but the `participants` API returns a list of participants. Also by using this then we will warn if only a subset of the participants are returned.
Closes: #2913
> fix: Have `participants()` method use `http_list()`

- .github/workflows/test.yml
Closes #2873
I added `CODECOV_TOKEN` to  https://github.com/python-gitlab/python-gitlab/settings/secrets/actions.
See https://github.com/codecov/codecov-action?tab=readme-ov-file#usage
> chore(ci): use codecov token when available

- .github/workflows/stale.yml
If a `stale` label is manually applied, allow the issue or PR to be closed by the stale job.
Previously it would require the `stale` label and to also have one of 'need info' or 'Waiting for response' labels added.
> chore(ci): stale: allow issues/PRs that have stale label to be closed

- .github/workflows/stale.yml
Saw the following error in the log:
[#2618] Removing the label "Stale" from this issue...
##[error][#2618] Error when removing the label: "Label does not exist"
My theory is that the case doesn't match ("Stale" != "stale") and that is why it failed.  Our label is "stale" so update this to match. Thought of changing the label name on GitHub but then would also require a change here to the "any-of-labels". So it seemed simpler to just change it here.
It is confusing though that it detected the label "stale", but then couldn't delete it.
> chore(ci): specify name of "stale" label

- docs/api-objects.rst
- docs/gl_objects/protected_packages.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/package_protection_rules.py
- gitlab/v4/objects/projects.py
- tests/functional/api/test_packages.py
- tests/unit/objects/test_package_protection_rules.py
https://docs.gitlab.com/ee/api/project_packages_protection_rules.html#list-package-protection-rules
> feat(api): add support for package protection rules

- docs/api-usage.rst
Add a warning about using `sudo` when saving.
Give an example of how to `get` an object, modify it, and then `save` it using `sudo`
Closes: #532
> docs: document how to use `sudo` if modifying an object

- docs/api-objects.rst
- docs/gl_objects/protected_container_repositories.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/package_protection_rules.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/registry_protection_rules.py
- tests/functional/api/test_registry.py
- tests/unit/objects/test_registry_protection_rules.py
https://docs.gitlab.com/ee/user/packages/container_registry/container_protection_rules.html
> feat(api): add support for container registry protection rules

- docs/api-usage.rst
pre-commit incorrectly wants double back-quotes inside the code section. Rather than fight it, just use single quotes.
> chore(ci): make pre-commit check happy

- docs/gl_objects/snippets.rst
- gitlab/v4/objects/snippets.py
- tests/functional/api/test_snippets.py
See https://docs.gitlab.com/ee/api/snippets.html#list-all-snippets
> feat(snippets): add support for listing all instance snippets

- docs/gl_objects/groups.rst
- docs/gl_objects/projects.rst
- gitlab/exceptions.py
- gitlab/v4/objects/hooks.py
- tests/unit/objects/test_hooks.py
Add the ability to trigger tests of project and group hooks.
Fixes #2924 
* Add the ability to trigger tests of project and group hooks
> feat(api): project/group hook test triggering

- tests/functional/cli/test_cli_projects.py
Before we allowed a maximum of around 15 seconds for the project-export. Often times the CI was failing with this value.
Change it to a maximum of around 30 seconds.
> test(cli): allow up to 30 seconds for a project export

- gitlab/v4/objects/members.py
I'm not sure if this PR needs tests or documentation updates. If you think it is necessary - I will add it.
Taken from here: https://docs.gitlab.com/17.3/ee/api/members.html#add-a-member-to-a-group-or-project
> feat(api): add exclusive GET attrs for /groups/:id/members

- docs/api-usage-graphql.rst
- docs/api-usage.rst
- docs/cli-usage.rst
- docs/index.rst
- gitlab/__init__.py
- gitlab/_backends/graphql.py
- gitlab/client.py
- gitlab/utils.py
- pyproject.toml
- requirements.txt
- tests/functional/api/test_graphql.py
- tests/functional/fixtures/set_token.rb
- tests/install/test_install.py
- tests/unit/test_graphql.py
Related to #1357 
Adds a minimal client without any bells and whistles, to keep the diff small and then we can bring in more common handling from the REST client.
> feat: add a minimal GraphQL client

- gitlab/v4/objects/members.py
#2964 introduced support for passing a `username` to `/groups/:id/members`. The same should also be possible for `/projects/:id/members`.
> feat(api): add exclusive GET attrs for /projects/:id/members

- gitlab/v4/objects/files.py
- tests/unit/objects/test_repositories.py
Closes #2976 
The `ProjectFileManager` class current has a `head` method, which throws a 404 error when used, as it doesn't have the same logic for URL path construction that its `get` method has. This is because it is inheriting from `GetMixin`, which inherits from `HeadMixin`. The benefit of having the HEAD request properly support is you can inspect and compare the file without needing to fully download it, as the actual file content is not returned.
This change:
- Removes the `ProjectFileManager` inheritance of `GetMixin`, since we're not making proper use of that class.
- adds a proper `head` method to `ProjectFileManager` that correctly constructs the API query
- Adds a unit test for the new `head` method based on mocked real-world headers
Note that because the HEAD request returns …
> fix(api): head requests for projectfilemanager

- docs/gl_objects/merge_requests.rst
- gitlab/v4/objects/merge_requests.py
- tests/unit/objects/test_merge_requests.py
- This PR introduces `related_issues` for the `merge_requests` object, returning a list of all related issues.
GitLab released `related_issues` ([official docs](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-related-to-the-merge-request)), an endpoint which collects all issues that relate to the current MR. This can be from:
- commit messages on the MR that contain issue links
- issue links commented in the MR
- issue links in the title of the MR
- issues created from discussions in the MR
See the change introduced: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155422
```sh
curl --header "PRIVATE-TOKEN: <your_access_token>" \
--url "https://127.0.0.1:3000/api/v4/projects/7/merge_requests/1/related_issues"
```
Both docs & tests updated
Please consider whether this …
> feat: introduce related_issues to merge requests

- .pre-commit-config.yaml
- pyproject.toml
- requirements-lint.txt
pylint 3.3.1 appears to have added "too-many-positional-arguments" check with a value of 5.
I don't disagree with this, but we have many functions which exceed this value. We might think about converting some of positional arguments over to keyword arguments in the future. But that is for another time.
For now disable the check across the project.
> chore: update pylint to 3.3.1 and resolve issues

- gitlab/v4/objects/files.py
When an error occurs, raise `GitlabHeadError` in
`project.files.head()` method.
Closes: #3004
> fix: raise GitlabHeadError in `project.files.head()` method

- .github/workflows/test.yml
- README.rst
- pyproject.toml
Python 3.8 is End-of-Life (EOL) as of 2024-10 as stated in https://devguide.python.org/versions/ and
https://peps.python.org/pep-0569/#lifespan
By dropping support for Python 3.8 and requiring Python 3.9 or higher it allows python-gitlab to take advantage of new features in Python 3.9, which are documented at:
https://docs.python.org/3/whatsnew/3.9.html
Closes: #2968
BREAKING CHANGE: As of python-gitlab 5.0.0, Python 3.8 is no longer supported. Python 3.9 or higher is required.
> feat: remove support for Python 3.8, require 3.9 or higher

- gitlab/v4/objects/merge_request_approvals.py
- tests/unit/objects/test_project_merge_request_approvals.py
The representation attribute for `ProjectMergeRequestApprovalRule` is `name` (see [here](https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/v4/objects/merge_request_approvals.py#L139)), which makes sense based on the API documentation. However, the API for `ProjectApprovalRule` is [nearly the same](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule), but we don't set the representation attribute to `name` for that class (see [here](https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/v4/objects/merge_request_approvals.py#L55)).
This MR sets `_repr_attr` for the `ProjectApprovalRule` class , as well as adds a unit test for ensure we can list a project's approval rules, and call `repr()` on it.
Please consider whether this PR needs …
> Make repr() of project approval rules consistent with merge request approval rules

- .github/ISSUE_TEMPLATE/issue_template.md
python-gitlab hasn't supported the GitLab v3 API since 2018. The last version of python-gitlab to support it was v1.4
Support was removed in:
commit fe89b949922c028830dd49095432ba627d330186
Author: Gauvain Pocentek <gauvain@pocentek.net>
Date:   Sat May 19 17:10:08 2018 +0200
Drop API v3 support
Drop the code, the tests, and update the documentation.
> chore: remove "v3" question from issue template

- .github/workflows/test.yml
- pyproject.toml
- tox.ini
Mark that Python 3.13 is supported.
Use Python 3.13 for the Mac and Windows tests.
Also remove the 'py38' tox environment. We no longer support Python 3.8.
> chore: add Python 3.13 as supported

- gitlab/v4/objects/files.py
GitLab's Repository Files API supports additional flags that weren't implemented before. Notably, the "start_branch" flag is particularly useful, as previously one had to use the "project-branch" command alongside "project-file" to add a file on a separate branch.
Since this is my first contribution to this project, I'm unsure if there's anything else to add beyond these lines.
[1] https://docs.gitlab.com/ee/api/repository_files.html
> feat(files): add support for more optional flags

- gitlab/v4/objects/service_accounts.py
add DeleteMixin, ListMixin to GroupServiceAccountManager and ObjectDeleteMixin to GroupServiceAccount
> feat(api): support list and delete for group service accounts

- gitlab/mixins.py
Closes https://github.com/python-gitlab/python-gitlab/issues/2766
Adds the register decorator for the relevant objects.
> feat(cli): enable token rotation via CLI

- gitlab/v4/objects/merge_request_approvals.py
While the `ProjectApprovalRuleManager` supports retrieving all approval rules for a given project (using `list()` method from `ListMixin`), attempting to retrieve a specific approval rule ([api docs](https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-a-single-project-level-rule)) on a given project does not appear to be possible.
Based on other objects in this library, I would expect to retrieve a specific approval rule with the `.get()` method exposed by `GetMixin`, but `ProjectApprovalRuleManager` [is not currently inheriting that](https://github.com/python-gitlab/python-gitlab/blob/v5.0.0/gitlab/v4/objects/merge_request_approvals.py#L60). As a result, the user gets an attribute not found error:
> AttributeError: 'ProjectApprovalRuleManager' object has no attribute 'get' …
> feat(api): get single project approval rule

- CHANGELOG.md
With v5.1.0 CHANGELOG.md was updated that mangled v1.10.0 triple backtick codeblock Traceback output that made sphinx [fail](https://github.com/python-gitlab/python-gitlab/actions/runs/12060608158/job/33631303063#step:5:204)  with a non-zero return code.
The resulting docs appears to be processes as text after the failing [line](https://python-gitlab.readthedocs.io/en/v5.1.0/changelog.html#v1-10-0-2019-07-22).  While reviewing other backtick codeblocks fix [v1.8.0](https://python-gitlab.readthedocs.io/en/v5.0.0/changelog.html#id258) to the original traceback.
Fix CHANGELOG triple backtick codeblocks for Traceblock.
Rerunning `sphinx-build -j auto -n -W --keep-going -b html docs …
> chore(docs): Fix CHANGELOG tracebacks codeblocks

- README.rst
- docs/api-usage-graphql.rst
- gitlab/__init__.py
- gitlab/_backends/graphql.py
- gitlab/client.py
- pyproject.toml
- requirements-test.txt
- tests/functional/api/test_graphql.py
- tests/unit/test_graphql.py
Users have been asking for years for some kind of async support. This is pretty easy to do with the GraphQL client as we're only talking to a single endpoint so it's a good start. 
Adds `AsyncGraphQL` and a private base client for common graphql logic. 
Related to https://github.com/python-gitlab/python-gitlab/issues/1357
Related to https://github.com/python-gitlab/python-gitlab/issues/1025
> feat(graphql): add async client

- docs/api-usage.rst
Set correct link to Gitlab's REST API authentication docs.
> docs(api-usage): fix link to Gitlab REST API Authentication Docs

- docs/gl_objects/merge_requests.rst
- docs/gl_objects/templates.rst
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/templates.py
- tests/unit/objects/test_templates.py
Project template classes  have been added to `objects/templates.py` and their respective managers added to the **Project** class in `objects/projects.py` to represent the [project templates API](https://docs.gitlab.com/ee/api/project_templates.html).
The project merge request template, in particular, will facilitate creating merge requests with a [description template](https://docs.gitlab.com/ee/user/project/description_templates.html), like the following example:
```python
mr_description_template = project.merge_request_templates.get("Default")
mr = project.mergerequests.create({'source_branch': 'cool_feature',
'target_branch': 'main',
'title': 'merge cool feature',
'description': mr_description_template.content})
```
Please consider whether this PR needs documentation and tests. **This …
> feat(api): add project templates

- .renovaterc.json
I guess we'll keep getting spammed by renovate if we dont do this for now :)
Related to:
#3058 
https://github.com/lundberg/respx/issues/279
https://github.com/lundberg/respx/pull/278
https://github.com/lundberg/respx/issues/277
> chore(renovate): pin httpx until respx is fixed

- docs/gl_objects/protected_container_repositories.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/registry_repository_protection_rules.py
- tests/functional/api/test_registry.py
- tests/unit/objects/test_registry_protection_rules.py
Gitlab changed from the REST container registry protection endpoint from
`/projects/{project_id}/registry/protection/rules`
to
`/projects/{project_id}/registry/repository/protection/rules`
Not great, but can't blame them as it's still behind a feature flag. This adds the new endpoint pretty much with a copy paste. As of GitLab 17.7 the old endpoint no longer works.
Looked at a few ways to deprecate all the methods but not sure it's worth it, but might do it in a follow-up.
https://www.geeksforgeeks.org/attaching-a-decorator-to-all-functions-within-a-class-in-python/ might work.
> feat(api): support the new registry protection rule endpoint

- gitlab/client.py
Although the GitlabConfigParser supports `keep_base_url`, it could not be configured from a file. This PR adds support for configuring the value from file.
> fix(api): allow configuration of keep_base_url from file

- CHANGELOG.md
- docs/gl_objects/protected_container_repositories.rst
- gitlab/_version.py
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/registry_protection_repository_rules.py
- tests/functional/api/test_registry.py
- tests/unit/objects/test_registry_protection_rules.py
See: https://docs.gitlab.com/ee/api/container_repository_protection_rules.html#list-container-repository-protection-rules
Currently its actually the wrong way around:
Before:
```python
>>> project.registry_repository_protection_rules.list()
DEBUG:http.client:send: b'GET /api/v4/projects/1/registry/repository/protection/rules?per_page=100 HTTP/1.1\r\nHost: gitlab\r\nUser-Agent: python-gitlab/5.3.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\nAuthorization: Bearer [MASKED]\r\n\r\n'
DEBUG:http.client:reply: 'HTTP/1.1 404 Not Found\r\n'
DEBUG:http.client:header: Server: nginx
DEBUG:http.client:header: Date: Tue, 07 Jan 2025 10:48:07 GMT
DEBUG:http.client:header: Content-Type: application/json
DEBUG:http.client:header: …
```
> fix(registry-protection): fix api url

- gitlab/mixins.py
- gitlab/v4/objects/artifacts.py
- gitlab/v4/objects/jobs.py
- gitlab/v4/objects/packages.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/secure_files.py
- gitlab/v4/objects/snippets.py
- tests/functional/api/test_import_export.py
Currently the download methods such as `ProjectJob.artifacts` have return type set to `Optional[Union[bytes, Iterator[Any]]]` which means they return either `None` or `bytes` or `Iterator[Any]`.
However, the actual return type is determined by the passed `streamed` and `iterator` arguments. Using `@typing.overload` decorator it is possible to return a single type based on the passed arguments.
Add overloads in the following order to all download methods:
1. If `streamed=False` and `iterator=False` return `bytes`. This is the default argument values therefore it should be first as it will be used to lookup default arguments.
2. If `iterator=True` return `Iterator[Any]`. This can be combined with both `streamed=True` and `streamed=False`.
3. If `streamed=True` and `iterator=False` return …
> feat(api): Narrow down return type of download methods using typing.overload

- docs/api-usage-advanced.rst
- gitlab/client.py
- tests/unit/objects/test_job_artifacts.py
- tests/unit/test_gitlab_http_methods.py
Currently the only way to manipulate the headers for a request is to use `Gitlab.headers` attribute. However, this makes it very concurrently unsafe because the `Gitlab` object can be shared between multiple requests at the same time.
Instead add a new keyword argument `extra_headers` which will update the headers dictionary with new values just before the request is sent.
For example, this can be used to download a part of a artifacts file using the `Range` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
> feat(api): Add argument that appends extra HTTP headers to a request

- gitlab/v4/objects/files.py
- tests/functional/cli/test_cli_files.py
Add an optional ref parameter for cli project-file raw (https://github.com/python-gitlab/python-gitlab/issues/3032).   The ref parameter was removed in python-gitlab v4.8.0.
Add an optional ref parameter for project-file raw.
closes #3032
> fix(files): add support for optional ref parameter for cli project-file raw

- .github/workflows/test.yml
Currently the functional API test takes around 17 minutes to run. And
the functional CLI test takes around 12 minutes to run.
Occasionally a job gets stuck and will sit until the default 360
minutes job timeout occurs.
Now have a 30 minute timeout for the 'functional' tests.
> chore(ci): set a 30 minute timeout for 'functional' tests

- gitlab/v4/objects/commits.py
- tests/functional/api/test_repository.py
- tests/unit/objects/test_commits.py
Returns the response when calling `ProjectCommit.cherry_pick`.
Fixes #3096
> fix(api): return the new commit when calling cherry_pick

- docs/api-objects.rst
- docs/gl_objects/status_checks.rst
- gitlab/v4/objects/__init__.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/projects.py
- gitlab/v4/objects/status_checks.py
- tests/functional/api/test_projects.py
- tests/unit/objects/test_status_checks.py
Implements https://github.com/python-gitlab/python-gitlab/issues/2632
TODO:
> feat(api): add support for external status check

- gitlab/v4/objects/files.py
This is equivalent to the changes in 44fd9dc1176a2c5529c45cc3186c0e775026175e but for `ProjectFileManager.raw` method that I must have missed in the original commit.
Closes #1806
> feat(api): Narrow down return type of ProjectFileManager.raw using typing.overload

- docs/gl_objects/merge_request_approvals.rst
- gitlab/v4/objects/groups.py
- gitlab/v4/objects/merge_request_approvals.py
- tests/unit/objects/test_group_merge_request_approvals.py
This PR adds support for merge request approval rule in a group setting.
closes #3040
> feat(group): add support for group level merge request approval rule

- gitlab/base.py
- gitlab/mixins.py
- gitlab/v4/cli.py
- gitlab/v4/objects/ldap.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/snippets.py
- gitlab/v4/objects/users.py
- tests/functional/conftest.py
BREAKING CHANGE: Type narrowing of `list()` methods return can become redundant.
Currently the RESTObjectList type hints yielded objects as base RESTObject. However, the ListMixin is now generic and will return the RESTObject subclass based on the RESTManager typing.
Using `typing.Generic` it is possible to make RESTObjectList type hint a specific subclass of the RESTObject.
Iterating over `list()` call the ListMixin will now yield the same object class because both `list` and `RESTObjectList` will have the same type hinted subclass.
Closes #2062
> feat(api)!: Make RESTObjectList typing generic

- gitlab/mixins.py
- gitlab/v4/objects/ldap.py
- gitlab/v4/objects/merge_requests.py
- gitlab/v4/objects/milestones.py
- gitlab/v4/objects/repositories.py
- gitlab/v4/objects/runners.py
- gitlab/v4/objects/users.py
The `all` keyword had a lot of conflicts with other API parameters and was silently deprecated in favour of `get_all`. However, a lot of docstings were not updated to use the new keyword.
> docs: Use get_all keyword arg instead of all in docstrings

- .github/workflows/docs.yml
Closes https://github.com/python-gitlab/python-gitlab/issues/1445
Enabled https://docs.readthedocs.com/platform/stable/guides/pull-requests.html
Keeps the actual docs build in CI just in case.
> chore(ci): replace docs artifact with readthedocs previews

- CONTRIBUTING.rst
- requirements-docs.txt
- tox.ini
This update can be helpful when changing documentation by serving the docs locally to ensure content presentation and format is as-expected.
While working on my last PR locally, I had added these options for the same purpose. Thought it might be helpful for others too. So, opened this PR with the required updates.
> chore(dev): add option for serving docs locally

- docs/api-usage-graphql.rst
Update the example GraphQL query string, as the original one could not be executed successfully.
> docs(api-usage-graphql): fix the example graphql query string

- docs/gl_objects/groups.rst
- docs/gl_objects/projects.rst
- docs/gl_objects/topics.rst
- gitlab/utils.py
- tests/functional/api/test_groups.py
- tests/functional/api/test_projects.py
- tests/functional/api/test_topics.py
When attempting to remove for example a [groups](https://docs.gitlab.com/api/groups/#remove-a-group-avatar), [projects](https://docs.gitlab.com/api/projects/#remove-a-project-avatar) or [topics](https://docs.gitlab.com/api/topics/#remove-a-topic-avatar) avatar by setting it to an empty string, the current implementation raises a validation error about unsupported file formats.
The solution is to add a special condition that checks if the value of a `FileAttribute` is an empty string. If so, it should remain in the `data` dictionary instead of being moved to the `files` dictionary.
Fixes #2933
> feat(api): add support for avatar removal

- gitlab/v4/objects/settings.py
Implement support for https://docs.gitlab.com/administration/silent_mode/
Example:
```bash
gitlab application-settings update --silent-mode-enabled 'true'
gitlab application-settings update --silent-mode-enabled 'false'
```
- Documentation automatically generated and new key matches `signup_enabled` sources
- No test added as most other settings are not implemented in `tests/functional/cli/test_cli_v4.py`
> feat(settings): implement support for 'silent_mode_enabled'

- docs/gl_objects/group_access_tokens.rst
- docs/gl_objects/personal_access_tokens.rst
- docs/gl_objects/project_access_tokens.rst
- gitlab/mixins.py
- tests/unit/objects/test_group_access_tokens.py
- tests/unit/objects/test_personal_access_tokens.py
- tests/unit/objects/test_project_access_tokens.py
This update introduces a new boolean input variable, self-rotation, to the rotate method of the ObjectRotateMixin class. When set to True, the method passes the keyword self to the rotate method of RotateMixin instead of the token ID. This change allows the URL to be composed as specified in the GitLab API documentation: [Self Rotation](https://docs.gitlab.com/api/personal_access_tokens/#self-rotate).
> feat(api): add support for token self-rotation

- docs/gl_objects/users.rst
- gitlab/v4/objects/users.py
- tests/unit/objects/test_users.py
This PR implements an endpoint for listing a user's contributed projects (related issue #3119):
```http
GET /users/:user_id/contributed_projects
```
GitLab docs: https://docs.gitlab.com/api/projects/#list-projects-a-user-has-contributed-to
**API usage**
```python
projects = user.contributed_projects.list()
```
**CLI usage**
```bash
gitlab -g something user-contributed-project list --user-id username
```
**Modified files:**
* "docs/gl_objects/users.rst" - explain the added method.
* "gitlab/v4/objects/users.py" - the API implementation.
* "tests/unit/objects/test_users.py" - add a unit test
> feat(api): add listing user contributed projects

- docs/gl_objects/protected_branches.rst
- gitlab/v4/objects/branches.py
- gitlab/v4/objects/groups.py
- tests/functional/api/test_groups.py
- Adds `protectedbranches` attr to the [Group]() class objects. This allows one to retrieve (`.list()`) or set (`.create()`) protected branches to trickle downstream to sub-groups/projects.
- Ref: https://docs.gitlab.com/api/group_protected_branches/
Closes #3164
> feat: add protectedbranches to group class (#3164)

- gitlab/v4/objects/tags.py
Added _list_filters attribute to `gitlab.v4.objects.tags.ProjectTagManager` to support defined api list filters: `order_by`, `sort` and `search`.
Closes #3156
> Add support for project tag list filters

- .github/workflows/release.yml
The previous 'python-semantic-release/upload-to-gh-release' action has been deprecated.
Closes: #3210
> build(release): use correct python-semantic-release/publish-action

- gitlab/v4/objects/users.py
Implement support `admins` in `list` : https://docs.gitlab.com/api/users/#as-an-administrator
```bash
gitlab user list --admins true
gitlab user list --admins false
```
* Documentation automatically generated and new key matches `admins` sources
* No test added as most other settings are not implemented in tests/functional/cli/test_cli_v4.py
> feat(users): implement support for 'admins' in administrators 'list'
